# Assignment Question No 1:

##### Write a python program to display all the header tags from ‘en.wikipedia.org/wiki/Main_Page’.

In [496]:
#importing necessary libraries
from bs4 import BeautifulSoup
import requests

In [497]:
# requesting on page 
page=requests.get('https://en.wikipedia.org/wiki/Main_Page')
page

In [498]:
# reading content of page
#page.content

In [499]:
soup=BeautifulSoup(page.content)
# print(soup)

In [500]:
# beautifying content in proper look
#print(soup.prettify())

In [501]:
#First we will extract the HTML tag where we have the first job title 
header_h1 =soup.find_all('h1',class_='firstHeading')
header_h1

In [502]:
# converting header_h1 into list
Header_H1=[]
for i in header_h1:
    Header_H1.append(i.text)
Header_H1

['Main Page']

In [503]:
#extracting second header column
header_h2 =soup.find_all('h2',class_='mp-h2')
header_h2

[<h2 class="mp-h2" id="mp-tfa-h2"><span id="From_today.27s_featured_article"></span><span class="mw-headline" id="From_today's_featured_article">From today's featured article</span></h2>,
 <h2 class="mp-h2" id="mp-dyk-h2"><span class="mw-headline" id="Did_you_know_...">Did you know ...</span></h2>,
 <h2 class="mp-h2" id="mp-itn-h2"><span class="mw-headline" id="In_the_news">In the news</span></h2>,
 <h2 class="mp-h2" id="mp-otd-h2"><span class="mw-headline" id="On_this_day">On this day</span></h2>,
 <h2 class="mp-h2" id="mp-tfp-h2"><span id="Today.27s_featured_picture"></span><span class="mw-headline" id="Today's_featured_picture">Today's featured picture</span></h2>,
 <h2 class="mp-h2" id="mp-other"><span class="mw-headline" id="Other_areas_of_Wikipedia">Other areas of Wikipedia</span></h2>,
 <h2 class="mp-h2" id="mp-sister"><span id="Wikipedia.27s_sister_projects"></span><span class="mw-headline" id="Wikipedia's_sister_projects">Wikipedia's sister projects</span></h2>,
 <h2 class="mp-h2" id="mp-lang"><span class="mw-headline" id="Wikipedia_languages">Wikipedia languages</span></h2>]

In [504]:
# converting header_h2 into list
Header_H2=[]
for i in header_h2:
    Header_H2.append(i.text)
Header_H2

["From today's featured article",
 'Did you know\xa0...',
 'In the news',
 'On this day',
 "Today's featured picture",
 'Other areas of Wikipedia',
 "Wikipedia's sister projects",
 'Wikipedia languages']

In [505]:
#extracting third header column
header_h3 =soup.find_all('h3',class_='vector-menu-heading')
header_h3

[<h3 class="vector-menu-heading" id="p-personal-label">
 <span>Personal tools</span>
 </h3>,
 <h3 class="vector-menu-heading" id="p-namespaces-label">
 <span>Namespaces</span>
 </h3>,
 <h3 class="vector-menu-heading" id="p-variants-label">
 <span>Variants</span>
 </h3>,
 <h3 class="vector-menu-heading" id="p-views-label">
 <span>Views</span>
 </h3>,
 <h3 class="vector-menu-heading" id="p-cactions-label">
 <span>More</span>
 </h3>,
 <h3 class="vector-menu-heading" id="p-navigation-label">
 <span>Navigation</span>
 </h3>,
 <h3 class="vector-menu-heading" id="p-interaction-label">
 <span>Contribute</span>
 </h3>,
 <h3 class="vector-menu-heading" id="p-tb-label">
 <span>Tools</span>
 </h3>,
 <h3 class="vector-menu-heading" id="p-coll-print_export-label">
 <span>Print/export</span>
 </h3>,
 <h3 class="vector-menu-heading" id="p-wikibase-otherprojects-label">
 <span>In other projects</span>
 </h3>,
 <h3 class="vector-menu-heading" id="p-lang-label">
 <span>Languages</span>
 </h3>]

In [506]:
# converting header_h3 into list
Header_H3=[]
for i in header_h3:
    Header_H3.append(i.text.replace('\n',''))
Header_H3

['Personal tools',
 'Namespaces',
 'Variants',
 'Views',
 'More',
 'Navigation',
 'Contribute',
 'Tools',
 'Print/export',
 'In other projects',
 'Languages']

In [507]:
#extracting headlines
headline=soup.find_all('span',class_='mw-headline')
headline

[<span class="mw-headline" id="From_today's_featured_article">From today's featured article</span>,
 <span class="mw-headline" id="Did_you_know_...">Did you know ...</span>,
 <span class="mw-headline" id="In_the_news">In the news</span>,
 <span class="mw-headline" id="On_this_day">On this day</span>,
 <span class="mw-headline" id="Today's_featured_picture">Today's featured picture</span>,
 <span class="mw-headline" id="Other_areas_of_Wikipedia">Other areas of Wikipedia</span>,
 <span class="mw-headline" id="Wikipedia's_sister_projects">Wikipedia's sister projects</span>,
 <span class="mw-headline" id="Wikipedia_languages">Wikipedia languages</span>]

In [508]:
# converting headlines into list
Headlines=[]
for i in headline:
    Headlines.append(i.text)
Headlines

["From today's featured article",
 'Did you know\xa0...',
 'In the news',
 'On this day',
 "Today's featured picture",
 'Other areas of Wikipedia',
 "Wikipedia's sister projects",
 'Wikipedia languages']

# Assignment Question No 2:

##### Write a python program to display IMDB’s Top rated 100 movies’ data (i.e. Name, IMDB rating, Year of release) and save it in form of a CSV file.

In [509]:
# sending request to the webpage 
page2=requests.get('https://www.imdb.com/chart/top/')
page2

In [510]:
# content of page

#page2.content

In [511]:

soup2=BeautifulSoup(page2.content)
#soup2

In [512]:
# pretiffying our coude in proper format
#print(soup2.prettify)

In [513]:
# reading the names of all movies
name1=soup2.find_all('td',class_='titleColumn')
name1

[<td class="titleColumn">
       1.
       <a href="/title/tt0111161/" title="Frank Darabont (dir.), Tim Robbins, Morgan Freeman">The Shawshank Redemption</a>
 <span class="secondaryInfo">(1994)</span>
 </td>,
 <td class="titleColumn">
       2.
       <a href="/title/tt0068646/" title="Francis Ford Coppola (dir.), Marlon Brando, Al Pacino">The Godfather</a>
 <span class="secondaryInfo">(1972)</span>
 </td>,
 <td class="titleColumn">
       3.
       <a href="/title/tt0071562/" title="Francis Ford Coppola (dir.), Al Pacino, Robert De Niro">The Godfather: Part II</a>
 <span class="secondaryInfo">(1974)</span>
 </td>,
 <td class="titleColumn">
       4.
       <a href="/title/tt0468569/" title="Christopher Nolan (dir.), Christian Bale, Heath Ledger">The Dark Knight</a>
 <span class="secondaryInfo">(2008)</span>
 </td>,
 <td class="titleColumn">
       5.
       <a href="/title/tt0050083/" title="Sidney Lumet (dir.), Henry Fonda, Lee J. Cobb">12 Angry Men</a>
 <span class="secondaryInfo">(1957)</span>
 </td>,
 <td class="titleColumn">
       6.
       <a href="/title/tt0108052/" title="Steven Spielberg (dir.), Liam Neeson, Ralph Fiennes">Schindler's List</a>
 <span class="secondaryInfo">(1993)</span>
 </td>,
 <td class="titleColumn">
       7.
       <a href="/title/tt0167260/" title="Peter Jackson (dir.), Elijah Wood, Viggo Mortensen">The Lord of the Rings: The Return of the King</a>
 <span class="secondaryInfo">(2003)</span>
 </td>,
 <td class="titleColumn">
       8.
       <a href="/title/tt0110912/" title="Quentin Tarantino (dir.), John Travolta, Uma Thurman">Pulp Fiction</a>
 <span class="secondaryInfo">(1994)</span>
 </td>,
 <td class="titleColumn">
       9.
       <a href="/title/tt0060196/" title="Sergio Leone (dir.), Clint Eastwood, Eli Wallach">Il buono, il brutto, il cattivo</a>
 <span class="secondaryInfo">(1966)</span>
 </td>,
 <td class="titleColumn">
       10.
       <a href="/title/tt0120737/" title="Peter Jackson (dir.), Elijah Wood, Ian McKellen">The Lord of the Rings: The Fellowship of the Ring</a>
 <span class="secondaryInfo">(2001)</span>
 </td>,
 <td class="titleColumn">
       11.
       <a href="/title/tt0137523/" title="David Fincher (dir.), Brad Pitt, Edward Norton">Fight Club</a>
 <span class="secondaryInfo">(1999)</span>
 </td>,
 <td class="titleColumn">
       12.
       <a href="/title/tt0109830/" title="Robert Zemeckis (dir.), Tom Hanks, Robin Wright">Forrest Gump</a>
 <span class="secondaryInfo">(1994)</span>
 </td>,
 <td class="titleColumn">
       13.
       <a href="/title/tt1375666/" title="Christopher Nolan (dir.), Leonardo DiCaprio, Joseph Gordon-Levitt">Inception</a>
 <span class="secondaryInfo">(2010)</span>
 </td>,
 <td class="titleColumn">
       14.
       <a href="/title/tt0167261/" title="Peter Jackson (dir.), Elijah Wood, Ian McKellen">The Lord of the Rings: The Two Towers</a>
 <span class="secondaryInfo">(2002)</span>
 </td>,
 <td class="titleColumn">
       15.
       <a href="/title/tt0080684/" title="Irvin Kershner (dir.), Mark Hamill, Harrison Ford">Star Wars: Episode V - The Empire Strikes Back</a>
 <span class="secondaryInfo">(1980)</span>
 </td>,
 <td class="titleColumn">
       16.
       <a href="/title/tt0133093/" title="Lana Wachowski (dir.), Keanu Reeves, Laurence Fishburne">The Matrix</a>
 <span class="secondaryInfo">(1999)</span>
 </td>,
 <td class="titleColumn">
       17.
       <a href="/title/tt0099685/" title="Martin Scorsese (dir.), Robert De Niro, Ray Liotta">Goodfellas</a>
 <span class="secondaryInfo">(1990)</span>
 </td>,
 <td class="titleColumn">
       18.
       <a href="/title/tt0073486/" title="Milos Forman (dir.), Jack Nicholson, Louise Fletcher">One Flew Over the Cuckoo's Nest</a>
 <span class="secondaryInfo">(1975)</span>
 </td>,
 <td class="titleColumn">
       19.
       <a href="/title/tt0047478/" title="Akira Kurosawa (dir.), Toshirô Mifune, Takashi Shimura">Shichinin no samurai</a>
 <span class="secondaryInfo">(1954)</span>
 </td>,
 <td class="titleColumn">
       20.
       <a href="/title/tt0114369/" title="David Fincher (dir.), Morgan Freeman, Brad Pitt">Se7en</a>
 <span class="secondaryInfo">(1995)</span>
 </td>,
 <td class="titleColumn">
       21.
       <a href="/title/tt0118799/" title="Roberto Benigni (dir.), Roberto Benigni, Nicoletta Braschi">La vita è bella</a>
 <span class="secondaryInfo">(1997)</span>
 </td>,
 <td class="titleColumn">
       22.
       <a href="/title/tt0317248/" title="Fernando Meirelles (dir.), Alexandre Rodrigues, Leandro Firmino">Cidade de Deus</a>
 <span class="secondaryInfo">(2002)</span>
 </td>,
 <td class="titleColumn">
       23.
       <a href="/title/tt0102926/" title="Jonathan Demme (dir.), Jodie Foster, Anthony Hopkins">The Silence of the Lambs</a>
 <span class="secondaryInfo">(1991)</span>
 </td>,
 <td class="titleColumn">
       24.
       <a href="/title/tt0038650/" title="Frank Capra (dir.), James Stewart, Donna Reed">It's a Wonderful Life</a>
 <span class="secondaryInfo">(1946)</span>
 </td>,
 <td class="titleColumn">
       25.
       <a href="/title/tt0120815/" title="Steven Spielberg (dir.), Tom Hanks, Matt Damon">Saving Private Ryan</a>
 <span class="secondaryInfo">(1998)</span>
 </td>,
 <td class="titleColumn">
       26.
       <a href="/title/tt0076759/" title="George Lucas (dir.), Mark Hamill, Harrison Ford">Star Wars</a>
 <span class="secondaryInfo">(1977)</span>
 </td>,
 <td class="titleColumn">
       27.
       <a href="/title/tt0120689/" title="Frank Darabont (dir.), Tom Hanks, Michael Clarke Duncan">The Green Mile</a>
 <span class="secondaryInfo">(1999)</span>
 </td>,
 <td class="titleColumn">
       28.
       <a href="/title/tt0245429/" title="Hayao Miyazaki (dir.), Daveigh Chase, Suzanne Pleshette">Sen to Chihiro no kamikakushi</a>
 <span class="secondaryInfo">(2001)</span>
 </td>,
 <td class="titleColumn">
       29.
       <a href="/title/tt0816692/" title="Christopher Nolan (dir.), Matthew McConaughey, Anne Hathaway">Interstellar</a>
 <span class="secondaryInfo">(2014)</span>
 </td>,
 <td class="titleColumn">
       30.
       <a href="/title/tt6751668/" title="Bong Joon Ho (dir.), Kang-ho Song, Sun-kyun Lee">Gisaengchung</a>
 <span class="secondaryInfo">(2019)</span>
 </td>,
 <td class="titleColumn">
       31.
       <a href="/title/tt0110413/" title="Luc Besson (dir.), Jean Reno, Gary Oldman">Léon</a>
 <span class="secondaryInfo">(1994)</span>
 </td>,
 <td class="titleColumn">
       32.
       <a href="/title/tt0056058/" title="Masaki Kobayashi (dir.), Tatsuya Nakadai, Akira Ishihama">Seppuku</a>
 <span class="secondaryInfo">(1962)</span>
 </td>,
 <td class="titleColumn">
       33.
       <a href="/title/tt0110357/" title="Roger Allers (dir.), Matthew Broderick, Jeremy Irons">The Lion King</a>
 <span class="secondaryInfo">(1994)</span>
 </td>,
 <td class="titleColumn">
       34.
       <a href="/title/tt0114814/" title="Bryan Singer (dir.), Kevin Spacey, Gabriel Byrne">The Usual Suspects</a>
 <span class="secondaryInfo">(1995)</span>
 </td>,
 <td class="titleColumn">
       35.
       <a href="/title/tt0253474/" title="Roman Polanski (dir.), Adrien Brody, Thomas Kretschmann">The Pianist</a>
 <span class="secondaryInfo">(2002)</span>
 </td>,
 <td class="titleColumn">
       36.
       <a href="/title/tt0103064/" title="James Cameron (dir.), Arnold Schwarzenegger, Linda Hamilton">Terminator 2: Judgment Day</a>
 <span class="secondaryInfo">(1991)</span>
 </td>,
 <td class="titleColumn">
       37.
       <a href="/title/tt0088763/" title="Robert Zemeckis (dir.), Michael J. Fox, Christopher Lloyd">Back to the Future</a>
 <span class="secondaryInfo">(1985)</span>
 </td>,
 <td class="titleColumn">
       38.
       <a href="/title/tt0120586/" title="Tony Kaye (dir.), Edward Norton, Edward Furlong">American History X</a>
 <span class="secondaryInfo">(1998)</span>
 </td>,
 <td class="titleColumn">
       39.
       <a href="/title/tt0027977/" title="Charles Chaplin (dir.), Charles Chaplin, Paulette Goddard">Modern Times</a>
 <span class="secondaryInfo">(1936)</span>
 </td>,
 <td class="titleColumn">
       40.
       <a href="/title/tt0172495/" title="Ridley Scott (dir.), Russell Crowe, Joaquin Phoenix">Gladiator</a>
 <span class="secondaryInfo">(2000)</span>
 </td>,
 <td class="titleColumn">
       41.
       <a href="/title/tt0054215/" title="Alfred Hitchcock (dir.), Anthony Perkins, Janet Leigh">Psycho</a>
 <span class="secondaryInfo">(1960)</span>
 </td>,
 <td class="titleColumn">
       42.
       <a href="/title/tt0407887/" title="Martin Scorsese (dir.), Leonardo DiCaprio, Matt Damon">The Departed</a>
 <span class="secondaryInfo">(2006)</span>
 </td>,
 <td class="titleColumn">
       43.
       <a href="/title/tt0021749/" title="Charles Chaplin (dir.), Charles Chaplin, Virginia Cherrill">City Lights</a>
 <span class="secondaryInfo">(1931)</span>
 </td>,
 <td class="titleColumn">
       44.
       <a href="/title/tt2582802/" title="Damien Chazelle (dir.), Miles Teller, J.K. Simmons">Whiplash</a>
 <span class="secondaryInfo">(2014)</span>
 </td>,
 <td class="titleColumn">
       45.
       <a href="/title/tt1675434/" title="Olivier Nakache (dir.), François Cluzet, Omar Sy">The Intouchables</a>
 <span class="secondaryInfo">(2011)</span>
 </td>,
 <td class="titleColumn">
       46.
       <a href="/title/tt0095327/" title="Isao Takahata (dir.), Tsutomu Tatsumi, Ayano Shiraishi">Hotaru no haka</a>
 <span class="secondaryInfo">(1988)</span>
 </td>,
 <td class="titleColumn">
       47.
       <a href="/title/tt0482571/" title="Christopher Nolan (dir.), Christian Bale, Hugh Jackman">The Prestige</a>
 <span class="secondaryInfo">(2006)</span>
 </td>,
 <td class="titleColumn">
       48.
       <a href="/title/tt0064116/" title="Sergio Leone (dir.), Henry Fonda, Charles Bronson">Once Upon a Time in the West</a>
 <span class="secondaryInfo">(1968)</span>
 </td>,
 <td class="titleColumn">
       49.
       <a href="/title/tt0034583/" title="Michael Curtiz (dir.), Humphrey Bogart, Ingrid Bergman">Casablanca</a>
 <span class="secondaryInfo">(1942)</span>
 </td>,
 <td class="titleColumn">
       50.
       <a href="/title/tt0095765/" title="Giuseppe Tornatore (dir.), Philippe Noiret, Enzo Cannavale">Nuovo Cinema Paradiso</a>
 <span class="secondaryInfo">(1988)</span>
 </td>,
 <td class="titleColumn">
       51.
       <a href="/title/tt0047396/" title="Alfred Hitchcock (dir.), James Stewart, Grace Kelly">Rear Window</a>
 <span class="secondaryInfo">(1954)</span>
 </td>,
 <td class="titleColumn">
       52.
       <a href="/title/tt0078748/" title="Ridley Scott (dir.), Sigourney Weaver, Tom Skerritt">Alien</a>
 <span class="secondaryInfo">(1979)</span>
 </td>,
 <td class="titleColumn">
       53.
       <a href="/title/tt0078788/" title="Francis Ford Coppola (dir.), Martin Sheen, Marlon Brando">Apocalypse Now</a>
 <span class="secondaryInfo">(1979)</span>
 </td>,
 <td class="titleColumn">
       54.
       <a href="/title/tt0209144/" title="Christopher Nolan (dir.), Guy Pearce, Carrie-Anne Moss">Memento</a>
 <span class="secondaryInfo">(2000)</span>
 </td>,
 <td class="titleColumn">
       55.
       <a href="/title/tt0032553/" title="Charles Chaplin (dir.), Charles Chaplin, Paulette Goddard">The Great Dictator</a>
 <span class="secondaryInfo">(1940)</span>
 </td>,
 <td class="titleColumn">
       56.
       <a href="/title/tt0082971/" title="Steven Spielberg (dir.), Harrison Ford, Karen Allen">Raiders of the Lost Ark</a>
 <span class="secondaryInfo">(1981)</span>
 </td>,
 <td class="titleColumn">
       57.
       <a href="/title/tt1853728/" title="Quentin Tarantino (dir.), Jamie Foxx, Christoph Waltz">Django Unchained</a>
 <span class="secondaryInfo">(2012)</span>
 </td>,
 <td class="titleColumn">
       58.
       <a href="/title/tt0405094/" title="Florian Henckel von Donnersmarck (dir.), Ulrich Mühe, Martina Gedeck">The Lives of Others</a>
 <span class="secondaryInfo">(2006)</span>
 </td>,
 <td class="titleColumn">
       59.
       <a href="/title/tt0050825/" title="Stanley Kubrick (dir.), Kirk Douglas, Ralph Meeker">Paths of Glory</a>
 <span class="secondaryInfo">(1957)</span>
 </td>,
 <td class="titleColumn">
       60.
       <a href="/title/tt0910970/" title="Andrew Stanton (dir.), Ben Burtt, Elissa Knight">WALL·E</a>
 <span class="secondaryInfo">(2008)</span>
 </td>,
 <td class="titleColumn">
       61.
       <a href="/title/tt7286456/" title="Todd Phillips (dir.), Joaquin Phoenix, Robert De Niro">Joker</a>
 <span class="secondaryInfo">(2019)</span>
 </td>,
 <td class="titleColumn">
       62.
       <a href="/title/tt8503618/" title="Thomas Kail (dir.), Lin-Manuel Miranda, Phillipa Soo">Hamilton</a>
 <span class="secondaryInfo">(2020)</span>
 </td>,
 <td class="titleColumn">
       63.
       <a href="/title/tt0081505/" title="Stanley Kubrick (dir.), Jack Nicholson, Shelley Duvall">The Shining</a>
 <span class="secondaryInfo">(1980)</span>
 </td>,
 <td class="titleColumn">
       64.
       <a href="/title/tt4154756/" title="Anthony Russo (dir.), Robert Downey Jr., Chris Hemsworth">Avengers: Infinity War</a>
 <span class="secondaryInfo">(2018)</span>
 </td>,
 <td class="titleColumn">
       65.
       <a href="/title/tt0043014/" title="Billy Wilder (dir.), William Holden, Gloria Swanson">Sunset Blvd.</a>
 <span class="secondaryInfo">(1950)</span>
 </td>,
 <td class="titleColumn">
       66.
       <a href="/title/tt0051201/" title="Billy Wilder (dir.), Tyrone Power, Marlene Dietrich">Witness for the Prosecution</a>
 <span class="secondaryInfo">(1957)</span>
 </td>,
 <td class="titleColumn">
       67.
       <a href="/title/tt4633694/" title="Bob Persichetti (dir.), Shameik Moore, Jake Johnson">Spider-Man: Into the Spider-Verse</a>
 <span class="secondaryInfo">(2018)</span>
 </td>,
 <td class="titleColumn">
       68.
       <a href="/title/tt0364569/" title="Chan-wook Park (dir.), Choi Min-sik, Yoo Ji-Tae">Oldeuboi</a>
 <span class="secondaryInfo">(2003)</span>
 </td>,
 <td class="titleColumn">
       69.
       <a href="/title/tt0119698/" title="Hayao Miyazaki (dir.), Yôji Matsuda, Yuriko Ishida">Mononoke-hime</a>
 <span class="secondaryInfo">(1997)</span>
 </td>,
 <td class="titleColumn">
       70.
       <a href="/title/tt0057012/" title="Stanley Kubrick (dir.), Peter Sellers, George C. Scott">Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb</a>
 <span class="secondaryInfo">(1964)</span>
 </td>,
 <td class="titleColumn">
       71.
       <a href="/title/tt1345836/" title="Christopher Nolan (dir.), Christian Bale, Tom Hardy">The Dark Knight Rises</a>
 <span class="secondaryInfo">(2012)</span>
 </td>,
 <td class="titleColumn">
       72.
       <a href="/title/tt0087843/" title="Sergio Leone (dir.), Robert De Niro, James Woods">Once Upon a Time in America</a>
 <span class="secondaryInfo">(1984)</span>
 </td>,
 <td class="titleColumn">
       73.
       <a href="/title/tt5311514/" title="Makoto Shinkai (dir.), Ryûnosuke Kamiki, Mone Kamishiraishi">Kimi no na wa.</a>
 <span class="secondaryInfo">(2016)</span>
 </td>,
 <td class="titleColumn">
       74.
       <a href="/title/tt2380307/" title="Lee Unkrich (dir.), Anthony Gonzalez, Gael García Bernal">Coco</a>
 <span class="secondaryInfo">(2017)</span>
 </td>,
 <td class="titleColumn">
       75.
       <a href="/title/tt0090605/" title="James Cameron (dir.), Sigourney Weaver, Michael Biehn">Aliens</a>
 <span class="secondaryInfo">(1986)</span>
 </td>,
 <td class="titleColumn">
       76.
       <a href="/title/tt4154796/" title="Anthony Russo (dir.), Robert Downey Jr., Chris Evans">Avengers: Endgame</a>
 <span class="secondaryInfo">(2019)</span>
 </td>,
 <td class="titleColumn">
       77.
       <a href="/title/tt8267604/" title="Nadine Labaki (dir.), Zain Al Rafeea, Yordanos Shiferaw">Capharnaüm</a>
 <span class="secondaryInfo">(2018)</span>
 </td>,
 <td class="titleColumn">
       78.
       <a href="/title/tt0169547/" title="Sam Mendes (dir.), Kevin Spacey, Annette Bening">American Beauty</a>
 <span class="secondaryInfo">(1999)</span>
 </td>,
 <td class="titleColumn">
       79.
       <a href="/title/tt0112573/" title="Mel Gibson (dir.), Mel Gibson, Sophie Marceau">Braveheart</a>
 <span class="secondaryInfo">(1995)</span>
 </td>,
 <td class="titleColumn">
       80.
       <a href="/title/tt0057565/" title="Akira Kurosawa (dir.), Toshirô Mifune, Yutaka Sada">Tengoku to jigoku</a>
 <span class="secondaryInfo">(1963)</span>
 </td>,
 <td class="titleColumn">
       81.
       <a href="/title/tt0114709/" title="John Lasseter (dir.), Tom Hanks, Tim Allen">Toy Story</a>
 <span class="secondaryInfo">(1995)</span>
 </td>,
 <td class="titleColumn">
       82.
       <a href="/title/tt1187043/" title="Rajkumar Hirani (dir.), Aamir Khan, Madhavan">3 Idiots</a>
 <span class="secondaryInfo">(2009)</span>
 </td>,
 <td class="titleColumn">
       83.
       <a href="/title/tt0082096/" title="Wolfgang Petersen (dir.), Jürgen Prochnow, Herbert Grönemeyer">Das Boot</a>
 <span class="secondaryInfo">(1981)</span>
 </td>,
 <td class="titleColumn">
       84.
       <a href="/title/tt0086879/" title="Milos Forman (dir.), F. Murray Abraham, Tom Hulce">Amadeus</a>
 <span class="secondaryInfo">(1984)</span>
 </td>,
 <td class="titleColumn">
       85.
       <a href="/title/tt0361748/" title="Quentin Tarantino (dir.), Brad Pitt, Diane Kruger">Inglourious Basterds</a>
 <span class="secondaryInfo">(2009)</span>
 </td>,
 <td class="titleColumn">
       86.
       <a href="/title/tt0119217/" title="Gus Van Sant (dir.), Robin Williams, Matt Damon">Good Will Hunting</a>
 <span class="secondaryInfo">(1997)</span>
 </td>,
 <td class="titleColumn">
       87.
       <a href="/title/tt0086190/" title="Richard Marquand (dir.), Mark Hamill, Harrison Ford">Star Wars: Episode VI - Return of the Jedi</a>
 <span class="secondaryInfo">(1983)</span>
 </td>,
 <td class="titleColumn">
       88.
       <a href="/title/tt0986264/" title="Aamir Khan (dir.), Darsheel Safary, Aamir Khan">Taare Zameen Par</a>
 <span class="secondaryInfo">(2007)</span>
 </td>,
 <td class="titleColumn">
       89.
       <a href="/title/tt0105236/" title="Quentin Tarantino (dir.), Harvey Keitel, Tim Roth">Reservoir Dogs</a>
 <span class="secondaryInfo">(1992)</span>
 </td>,
 <td class="titleColumn">
       90.
       <a href="/title/tt0062622/" title="Stanley Kubrick (dir.), Keir Dullea, Gary Lockwood">2001: A Space Odyssey</a>
 <span class="secondaryInfo">(1968)</span>
 </td>,
 <td class="titleColumn">
       91.
       <a href="/title/tt0180093/" title="Darren Aronofsky (dir.), Ellen Burstyn, Jared Leto">Requiem for a Dream</a>
 <span class="secondaryInfo">(2000)</span>
 </td>,
 <td class="titleColumn">
       92.
       <a href="/title/tt2106476/" title="Thomas Vinterberg (dir.), Mads Mikkelsen, Thomas Bo Larsen">Jagten</a>
 <span class="secondaryInfo">(2012)</span>
 </td>,
 <td class="titleColumn">
       93.
       <a href="/title/tt0052357/" title="Alfred Hitchcock (dir.), James Stewart, Kim Novak">Vertigo</a>
 <span class="secondaryInfo">(1958)</span>
 </td>,
 <td class="titleColumn">
       94.
       <a href="/title/tt0022100/" title="Fritz Lang (dir.), Peter Lorre, Ellen Widmann">M - Eine Stadt sucht einen Mörder</a>
 <span class="secondaryInfo">(1931)</span>
 </td>,
 <td class="titleColumn">
       95.
       <a href="/title/tt0338013/" title="Michel Gondry (dir.), Jim Carrey, Kate Winslet">Eternal Sunshine of the Spotless Mind</a>
 <span class="secondaryInfo">(2004)</span>
 </td>,
 <td class="titleColumn">
       96.
       <a href="/title/tt0033467/" title="Orson Welles (dir.), Orson Welles, Joseph Cotten">Citizen Kane</a>
 <span class="secondaryInfo">(1941)</span>
 </td>,
 <td class="titleColumn">
       97.
       <a href="/title/tt5074352/" title="Nitesh Tiwari (dir.), Aamir Khan, Sakshi Tanwar">Dangal</a>
 <span class="secondaryInfo">(2016)</span>
 </td>,
 <td class="titleColumn">
       98.

In [514]:
# removing the \n
temp_name=[]      # empty list in this list the data will be stored 
cnt=0
for i in name1:
    if cnt<100:
        temp_name.append(i.text.replace('\n',''))           # converting text into list and replacing the '\n'
        cnt+=1
temp_name[0:5]

['      1.      The Shawshank Redemption(1994)',
 '      2.      The Godfather(1972)',
 '      3.      The Godfather: Part II(1974)',
 '      4.      The Dark Knight(2008)',
 '      5.      12 Angry Men(1957)']

In [515]:

final_name=[]            # declaring empty list to save names
years=[]                 # declaring empty list to save years     
names=''                    # declaring empty string for storing list item as string
fname=''                  # declaring another empty string for saving splitted string  
for i in range(0,100):
    names=temp_name[i]            # declaring individual item of list in a string
    fname=names.split('(')          # splitting the string into list
    final_name.append(fname[0])     # appending the list items with the movie name and removing extra space using .lstrip()
    years.append(fname[1].replace(')',''))         #

In [516]:
# REMOVING THE NUMBERS AND EXTRA SPACE

final_name=[]
names               # declaring empty string for converting list item into individual list    
fname
for i in range(0,100):
    names=temp_name[i]            # declaring individual item of list in a string
    fname=names.split('.')          # splitting the string into list
    final_name.append(fname[1].lstrip())     # appending the list items with the movie name and removing extra space

In [517]:
final_name[0:5]

['The Shawshank Redemption(1994)',
 'The Godfather(1972)',
 'The Godfather: Part II(1974)',
 'The Dark Knight(2008)',
 '12 Angry Men(1957)']

In [518]:
years[0:5]

['1994', '1972', '1974', '2008', '1957']

In [519]:
rating=soup2.find_all('td',class_='ratingColumn imdbRating')
rating

[<td class="ratingColumn imdbRating">
 <strong title="9.2 based on 2,386,317 user ratings">9.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="9.1 based on 1,653,843 user ratings">9.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="9.0 based on 1,150,490 user ratings">9.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="9.0 based on 2,349,446 user ratings">9.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.9 based on 704,416 user ratings">8.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.9 based on 1,233,659 user ratings">8.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.9 based on 1,669,019 user ratings">8.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.8 based on 1,858,477 user ratings">8.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.8 based on 699,065 user ratings">8.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.8 based on 1,689,664 user ratings">8.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.8 based on 1,887,734 user ratings">8.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.8 based on 1,846,266 user ratings">8.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.7 based on 2,107,877 user ratings">8.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.7 based on 1,509,375 user ratings">8.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.7 based on 1,176,578 user ratings">8.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.6 based on 1,706,413 user ratings">8.6</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.6 based on 1,040,247 user ratings">8.6</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.6 based on 931,695 user ratings">8.6</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.6 based on 320,791 user ratings">8.6</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.6 based on 1,473,355 user ratings">8.6</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.6 based on 635,368 user ratings">8.6</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.6 based on 708,273 user ratings">8.6</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.6 based on 1,295,272 user ratings">8.6</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.6 based on 411,775 user ratings">8.6</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.6 based on 1,259,442 user ratings">8.6</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.6 based on 1,248,645 user ratings">8.6</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 1,170,685 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 668,431 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 1,552,495 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 601,240 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 1,053,913 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 44,724 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 959,262 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 1,005,597 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 746,594 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 1,008,910 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 1,078,865 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 1,047,852 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 222,212 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 1,363,167 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 614,314 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 1,210,277 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 170,806 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 736,195 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 776,529 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 242,130 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 1,212,545 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 307,319 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 529,622 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 235,830 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 451,093 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 801,238 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 616,163 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 1,142,580 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 206,514 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 895,774 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 1,385,426 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 364,688 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 181,595 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 1,016,851 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 991,682 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 63,651 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 915,202 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 872,624 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 204,996 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 111,606 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 397,088 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 525,559 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 351,582 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 456,628 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 1,541,667 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 317,476 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 207,103 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 403,130 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 661,725 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 867,104 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 68,196 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 1,083,179 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 971,441 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 36,419 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 902,674 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 352,355 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 235,206 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 374,339 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 1,294,255 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 877,663 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 964,324 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 173,580 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 933,724 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 613,295 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 778,676 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 291,159 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 370,604 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 146,081 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 925,313 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 411,549 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 161,870 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 62,323 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 116,029 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 222,679 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 149,645 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 685,047 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 70,386 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 792,972 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 756,158 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 303,405 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 768,562 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 51,967 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 457,280 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 154,798 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 739,269 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 224,621 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 244,960 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 768,338 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 272,196 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 162,535 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 712,555 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 167,364 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 236,518 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 145,968 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 297,237 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 951,308 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 701,052 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 588,602 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 539,592 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 401,702 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 803,135 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 1,329,677 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 113,453 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 155,447 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 506,809 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 335,620 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 67,194 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 115,111 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 381,683 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 247,617 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 343,801 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 122,420 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 474,986 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 1,219,600 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 862,756 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 228,052 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 626,699 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 528,015 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 196,589 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 70,977 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 543,030 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 326,738 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 299,344 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 116,024 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 161,275 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 1,156,236 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 447,747 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 103,054 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 299,729 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 874,468 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 80,725 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 1,046,658 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 377,641 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 631,230 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 223,817 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 922,398 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 168,665 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 882,580 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 111,728 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 441,666 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 642,526 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 959,686 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 294,126 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 962,933 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 146,802 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 120,024 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 1,016,717 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 98,551 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 704,009 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 627,783 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 206,380 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 181,461 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 54,816 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 728,919 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 380,669 user ratings">8.1</strong>
 </td>,

In [520]:
Ratings=[]      # declaring an empty list to store the data
cnt=0
for i in rating:
    if cnt<100:
        Ratings.append(i.text.replace('\n',''))
        cnt+=1
Ratings[0:5]

['9.2', '9.1', '9.0', '9.0', '8.9']

In [521]:
print(len(final_name),len(years),len(Ratings))

100 100 100

In [522]:
# storing the name, rating and year in the dataframe
import pandas as pd
imdb_top_100_movies=pd.DataFrame({})
imdb_top_100_movies['Name']=final_name
imdb_top_100_movies['IMDB rating']=Ratings
imdb_top_100_movies['Year of release']=years

In [523]:
imdb_top_100_movies #dataframe

                              Name IMDB rating Year of release
0   The Shawshank Redemption(1994)         9.2            1994
1              The Godfather(1972)         9.1            1972
2     The Godfather: Part II(1974)         9.0            1974
3            The Dark Knight(2008)         9.0            2008
4               12 Angry Men(1957)         8.9            1957
..                             ...         ...             ...
95              Citizen Kane(1941)         8.3            1941
96                    Dangal(2016)         8.3            2016
97              Idi i smotri(1985)         8.2            1985
98                   The Kid(1921)         8.2            1921
99       Singin' in the Rain(1952)         8.2            1952

[100 rows x 3 columns]

In [524]:
# strong the DataFrame into csv
imdb_top_100_movies.to_csv("imdb_top_100_movies.csv",index=False)

# Assignment Question No 3:

##### Write a python program to display IMDB’s Top rated 100 Indian movies’ data (i.e. Name, IMDB rating, Year of release) and save it in form of a CSV file.

In [525]:
# sending request to the webpage
page3=requests.get('https://www.imdb.com/india/top-rated-indian-movies/')
page3

In [526]:
# reading content of page

#page3.content

In [527]:
soup3=BeautifulSoup(page3.content)
#soup3

In [528]:
# pretiffying the content of page in proper order
#print(soup3.prettify())

In [529]:
# finding all the names of movies
names=soup3.find_all('td',class_='titleColumn')
names

[<td class="titleColumn">
       1.
       <a href="/title/tt0048473/" title="Satyajit Ray (dir.), Kanu Bannerjee, Karuna Bannerjee">Pather Panchali</a>
 <span class="secondaryInfo">(1955)</span>
 </td>,
 <td class="titleColumn">
       2.
       <a href="/title/tt0079221/" title="Hrishikesh Mukherjee (dir.), Amol Palekar, Bindiya Goswami">Gol Maal</a>
 <span class="secondaryInfo">(1979)</span>
 </td>,
 <td class="titleColumn">
       3.
       <a href="/title/tt0093603/" title="Mani Ratnam (dir.), Kamal Haasan, Saranya Ponvannan">Nayakan</a>
 <span class="secondaryInfo">(1987)</span>
 </td>,
 <td class="titleColumn">
       4.
       <a href="/title/tt0367495/" title="Sundar C. (dir.), Kamal Haasan, Madhavan">Anbe Sivam</a>
 <span class="secondaryInfo">(2003)</span>
 </td>,
 <td class="titleColumn">
       5.
       <a href="/title/tt0052572/" title="Satyajit Ray (dir.), Soumitra Chatterjee, Sharmila Tagore">Apur Sansar</a>
 <span class="secondaryInfo">(1959)</span>
 </td>,
 <td class="titleColumn">
       6.
       <a href="/title/tt8176054/" title="Mari Selvaraj (dir.), Kathir, Anandhi">Pariyerum Perumal</a>
 <span class="secondaryInfo">(2018)</span>
 </td>,
 <td class="titleColumn">
       7.
       <a href="/title/tt7391996/" title="Venkatesh Maha (dir.), Radha Bessy, Subba Rao Vepada">C/o Kancharapalem</a>
 <span class="secondaryInfo">(2018)</span>
 </td>,
 <td class="titleColumn">
       8.
       <a href="/title/tt5311546/" title="Mahesh Manjrekar (dir.), Nana Patekar, Medha Manjrekar">Natsamrat</a>
 <span class="secondaryInfo">(2016)</span>
 </td>,
 <td class="titleColumn">
       9.
       <a href="/title/tt12361178/" title="Jeethu Joseph (dir.), Mohanlal, Meena">Drishyam 2</a>
 <span class="secondaryInfo">(2021)</span>
 </td>,
 <td class="titleColumn">
       10.
       <a href="/title/tt0237376/" title="Sibi Malayil (dir.), Mohanlal, Thilakan">Kireedam</a>
 <span class="secondaryInfo">(1989)</span>
 </td>,
 <td class="titleColumn">
       11.
       <a href="/title/tt0214915/" title="Fazil (dir.), Mohanlal, Shobana">Manichitrathazhu</a>
 <span class="secondaryInfo">(1993)</span>
 </td>,
 <td class="titleColumn">
       12.
       <a href="/title/tt0400234/" title="Anurag Kashyap (dir.), Kay Kay Menon, Pawan Malhotra">Black Friday</a>
 <span class="secondaryInfo">(2004)</span>
 </td>,
 <td class="titleColumn">
       13.
       <a href="/title/tt0105575/" title="Bharathan (dir.), Kamal Haasan, Shivaji Ganesan">Thevar Magan</a>
 <span class="secondaryInfo">(1992)</span>
 </td>,
 <td class="titleColumn">
       14.
       <a href="/title/tt7019842/" title="C. Prem Kumar (dir.), Vijay Sethupathi, Adithya Bhaskar">96</a>
 <span class="secondaryInfo">(2018)</span>
 </td>,
 <td class="titleColumn">
       15.
       <a href="/title/tt8413338/" title="Madhu C. Narayanan (dir.), Shane Nigam, Soubin Shahir">Kumbalangi Nights</a>
 <span class="secondaryInfo">(2019)</span>
 </td>,
 <td class="titleColumn">
       16.
       <a href="/title/tt1187043/" title="Rajkumar Hirani (dir.), Aamir Khan, Madhavan">3 Idiots</a>
 <span class="secondaryInfo">(2009)</span>
 </td>,
 <td class="titleColumn">
       17.
       <a href="/title/tt0986264/" title="Aamir Khan (dir.), Darsheel Safary, Aamir Khan">Taare Zameen Par</a>
 <span class="secondaryInfo">(2007)</span>
 </td>,
 <td class="titleColumn">
       18.
       <a href="/title/tt4991384/" title="Vetrimaaran (dir.), Dinesh, Samuthirakani">Visaaranai</a>
 <span class="secondaryInfo">(2015)</span>
 </td>,
 <td class="titleColumn">
       19.
       <a href="/title/tt5074352/" title="Nitesh Tiwari (dir.), Aamir Khan, Sakshi Tanwar">Dangal</a>
 <span class="secondaryInfo">(2016)</span>
 </td>,
 <td class="titleColumn">
       20.
       <a href="/title/tt7060344/" title="Ram Kumar (dir.), Vishnu Vishal, Amala Paul">Ratsasan</a>
 <span class="secondaryInfo">(2018)</span>
 </td>,
 <td class="titleColumn">
       21.
       <a href="/title/tt0101649/" title="Mani Ratnam (dir.), Rajinikanth, Mammootty">Thalapathi</a>
 <span class="secondaryInfo">(1991)</span>
 </td>,
 <td class="titleColumn">
       22.
       <a href="/title/tt0048956/" title="Satyajit Ray (dir.), Pinaki Sengupta, Smaran Ghosal">Aparajito</a>
 <span class="secondaryInfo">(1956)</span>
 </td>,
 <td class="titleColumn">
       23.
       <a href="/title/tt0085743/" title="Kundan Shah (dir.), Naseeruddin Shah, Ravi Baswani">Jaane Bhi Do Yaaro</a>
 <span class="secondaryInfo">(1983)</span>
 </td>,
 <td class="titleColumn">
       24.
       <a href="/title/tt0050870/" title="Guru Dutt (dir.), Guru Dutt, Waheeda Rehman">Pyaasa</a>
 <span class="secondaryInfo">(1957)</span>
 </td>,
 <td class="titleColumn">
       25.
       <a href="/title/tt0059246/" title="Vijay Anand (dir.), Dev Anand, Waheeda Rehman">Guide</a>
 <span class="secondaryInfo">(1965)</span>
 </td>,
 <td class="titleColumn">
       26.
       <a href="/title/tt8948790/" title="Gowtam Tinnanuri (dir.), Nani, Shraddha Srinath">Jersey</a>
 <span class="secondaryInfo">(2019)</span>
 </td>,
 <td class="titleColumn">
       27.
       <a href="/title/tt0312859/" title="Mani Ratnam (dir.), Madhavan, Simran">Kannathil Muthamittal</a>
 <span class="secondaryInfo">(2002)</span>
 </td>,
 <td class="titleColumn">
       28.
       <a href="/title/tt0072783/" title="Hrishikesh Mukherjee (dir.), Dharmendra, Sharmila Tagore">Chupke Chupke</a>
 <span class="secondaryInfo">(1975)</span>
 </td>,
 <td class="titleColumn">
       29.
       <a href="/title/tt9477520/" title="Vetrimaaran (dir.), Dhanush, Manju Warrier">Asuran</a>
 <span class="secondaryInfo">(2019)</span>
 </td>,
 <td class="titleColumn">
       30.
       <a href="/title/tt9900782/" title="Lokesh Kanagaraj (dir.), Karthi, Narain">Kaithi</a>
 <span class="secondaryInfo">(2019)</span>
 </td>,
 <td class="titleColumn">
       31.
       <a href="/title/tt4987556/" title="Mohan Raja (dir.), Jayam Ravi, Arvind Swamy">Thani Oruvan</a>
 <span class="secondaryInfo">(2015)</span>
 </td>,
 <td class="titleColumn">
       32.
       <a href="/title/tt0066763/" title="Hrishikesh Mukherjee (dir.), Rajesh Khanna, Amitabh Bachchan">Anand</a>
 <span class="secondaryInfo">(1971)</span>
 </td>,
 <td class="titleColumn">
       33.
       <a href="/title/tt5959980/" title="Vetrimaaran (dir.), Dhanush, Ameer Sultan">Vada Chennai</a>
 <span class="secondaryInfo">(2018)</span>
 </td>,
 <td class="titleColumn">
       34.
       <a href="/title/tt7738784/" title="Ram (dir.), Mammootty, Sadhana">Peranbu</a>
 <span class="secondaryInfo">(2018)</span>
 </td>,
 <td class="titleColumn">
       35.
       <a href="/title/tt3417422/" title="Jeethu Joseph (dir.), Mohanlal, Meena">Drishyam</a>
 <span class="secondaryInfo">(2013)</span>
 </td>,
 <td class="titleColumn">
       36.
       <a href="/title/tt6148156/" title="Gayatri (dir.), Madhavan, Vijay Sethupathi">Vikram Vedha</a>
 <span class="secondaryInfo">(2017)</span>
 </td>,
 <td class="titleColumn">
       37.
       <a href="/title/tt10189514/" title="Sudha Kongara (dir.), Suriya, Madhavan">Soorarai Pottru</a>
 <span class="secondaryInfo">(2020)</span>
 </td>,
 <td class="titleColumn">
       38.
       <a href="/title/tt0119385/" title="Mani Ratnam (dir.), Mohanlal, Prakash Raj">Iruvar</a>
 <span class="secondaryInfo">(1997)</span>
 </td>,
 <td class="titleColumn">
       39.
       <a href="/title/tt5867800/" title="Arun Prabhu Purushothaman (dir.), Aditi Balan, Padmashri Mohammad Ali">Aruvi</a>
 <span class="secondaryInfo">(2016)</span>
 </td>,
 <td class="titleColumn">
       40.
       <a href="/title/tt0466460/" title="Dibakar Banerjee (dir.), Anupam Kher, Boman Irani">Khosla Ka Ghosla!</a>
 <span class="secondaryInfo">(2006)</span>
 </td>,
 <td class="titleColumn">
       41.
       <a href="/title/tt7019942/" title="Thiagarajan Kumararaja (dir.), Vijay Sethupathi, Samantha Akkineni">Super Deluxe</a>
 <span class="secondaryInfo">(2019)</span>
 </td>,
 <td class="titleColumn">
       42.
       <a href="/title/tt10214826/" title="Swaroop Rsj (dir.), Naveen Polishetty, Shruti Sharma">Agent Sai Srinivasa Athreya</a>
 <span class="secondaryInfo">(2019)</span>
 </td>,
 <td class="titleColumn">
       43.
       <a href="/title/tt8239946/" title="Rahi Anil Barve (dir.), Sohum Shah, Jyoti Malshe">Tumbbad</a>
 <span class="secondaryInfo">(2018)</span>
 </td>,
 <td class="titleColumn">
       44.
       <a href="/title/tt7465992/" title="Nag Ashwin (dir.), Keerthy Suresh, Dulquer Salmaan">Mahanati</a>
 <span class="secondaryInfo">(2018)</span>
 </td>,
 <td class="titleColumn">
       45.
       <a href="/title/tt8108198/" title="Sriram Raghavan (dir.), Ayushmann Khurrana, Tabu">Andhadhun</a>
 <span class="secondaryInfo">(2018)</span>
 </td>,
 <td class="titleColumn">
       46.
       <a href="/title/tt3973410/" title="M. Manikandan (dir.), Ramesh, J. Vignesh">Kaakkaa Muttai</a>
 <span class="secondaryInfo">(2014)</span>
 </td>,
 <td class="titleColumn">
       47.
       <a href="/title/tt4679210/" title="Alphonse Puthren (dir.), Nivin Pauly, Sai Pallavi">Premam</a>
 <span class="secondaryInfo">(2015)</span>
 </td>,
 <td class="titleColumn">
       48.
       <a href="/title/tt0195231/" title="Ram Gopal Varma (dir.), J.D. Chakravarthi, Manoj Bajpayee">Satya</a>
 <span class="secondaryInfo">(1998)</span>
 </td>,
 <td class="titleColumn">
       49.
       <a href="/title/tt2181831/" title="Hansal Mehta (dir.), Rajkummar Rao, Prabhleen Sandhu">Shahid</a>
 <span class="secondaryInfo">(2012)</span>
 </td>,
 <td class="titleColumn">
       50.
       <a href="/title/tt0376127/" title="S. Shankar (dir.), Vikram, Sada">Anniyan</a>
 <span class="secondaryInfo">(2005)</span>
 </td>,
 <td class="titleColumn">
       51.
       <a href="/title/tt6380520/" title="Karthick Naren (dir.), Rahman, Prakash Raghavan">Dhuruvangal Pathinaaru</a>
 <span class="secondaryInfo">(2016)</span>
 </td>,
 <td class="titleColumn">
       52.
       <a href="/title/tt3668162/" title="Anjali Menon (dir.), Nazriya Nazim, Nivin Pauly">Bangalore Days</a>
 <span class="secondaryInfo">(2014)</span>
 </td>,
 <td class="titleColumn">
       53.
       <a href="/title/tt0220656/" title="S. Shankar (dir.), Arjun Sarja, Manisha Koirala">Mudhalvan</a>
 <span class="secondaryInfo">(1999)</span>
 </td>,
 <td class="titleColumn">
       54.
       <a href="/title/tt4429128/" title="Jeethu Joseph (dir.), Kamal Haasan, Gautami">Papanasam</a>
 <span class="secondaryInfo">(2015)</span>
 </td>,
 <td class="titleColumn">
       55.
       <a href="/title/tt2877108/" title="Nalan Kumarasamy (dir.), Vijay Sethupathi, Sanchita Shetty">Soodhu Kavvum</a>
 <span class="secondaryInfo">(2013)</span>
 </td>,
 <td class="titleColumn">
       56.
       <a href="/title/tt1954470/" title="Anurag Kashyap (dir.), Manoj Bajpayee, Richa Chadha">Gangs of Wasseypur</a>
 <span class="secondaryInfo">(2012)</span>
 </td>,
 <td class="titleColumn">
       57.
       <a href="/title/tt3569782/" title="Karthik Subbaraj (dir.), Siddharth, Bobby Simha">Jigarthanda</a>
 <span class="secondaryInfo">(2014)</span>
 </td>,
 <td class="titleColumn">
       58.
       <a href="/title/tt2356180/" title="Rakeysh Omprakash Mehra (dir.), Farhan Akhtar, Sonam Kapoor">Bhaag Milkha Bhaag</a>
 <span class="secondaryInfo">(2013)</span>
 </td>,
 <td class="titleColumn">
       59.
       <a href="/title/tt5312232/" title="Nagraj Manjule (dir.), Rinku Rajguru, Akash Thosar">Sairat</a>
 <span class="secondaryInfo">(2016)</span>
 </td>,
 <td class="titleColumn">
       60.
       <a href="/title/tt1620933/" title="Tigmanshu Dhulia (dir.), Irrfan Khan, Mahie Gill">Paan Singh Tomar</a>
 <span class="secondaryInfo">(2012)</span>
 </td>,
 <td class="titleColumn">
       61.
       <a href="/title/tt0073707/" title="Ramesh Sippy (dir.), Sanjeev Kumar, Dharmendra">Sholay</a>
 <span class="secondaryInfo">(1975)</span>
 </td>,
 <td class="titleColumn">
       62.
       <a href="/title/tt0367110/" title="Ashutosh Gowariker (dir.), Shah Rukh Khan, Gayatri Joshi">Swades: We, the People</a>
 <span class="secondaryInfo">(2004)</span>
 </td>,
 <td class="titleColumn">
       63.
       <a href="/title/tt4934950/" title="Meghna Gulzar (dir.), Irrfan Khan, Konkona Sen Sharma">Talvar</a>
 <span class="secondaryInfo">(2015)</span>
 </td>,
 <td class="titleColumn">
       64.
       <a href="/title/tt0242519/" title="Priyadarshan (dir.), Akshay Kumar, Sunil Shetty">Hera Pheri</a>
 <span class="secondaryInfo">(2000)</span>
 </td>,
 <td class="titleColumn">
       65.
       <a href="/title/tt0376076/" title="Bala (dir.), Vikram, Suriya">Pithamagan</a>
 <span class="secondaryInfo">(2003)</span>
 </td>,
 <td class="titleColumn">
       66.
       <a href="/title/tt0057935/" title="Satyajit Ray (dir.), Soumitra Chatterjee, Madhabi Mukherjee">Charulata</a>
 <span class="secondaryInfo">(1964)</span>
 </td>,
 <td class="titleColumn">
       67.
       <a href="/title/tt4430212/" title="Nishikant Kamat (dir.), Ajay Devgn, Shriya Saran">Drishyam</a>
 <span class="secondaryInfo">(2015)</span>
 </td>,
 <td class="titleColumn">
       68.
       <a href="/title/tt5005684/" title="Ashwiny Iyer Tiwari (dir.), Swara Bhaskar, Ratna Pathak Shah">Nil Battey Sannata</a>
 <span class="secondaryInfo">(2015)</span>
 </td>,
 <td class="titleColumn">
       69.
       <a href="/title/tt0871510/" title="Shimit Amin (dir.), Shah Rukh Khan, Vidya Malvade">Chak De! India</a>
 <span class="secondaryInfo">(2007)</span>
 </td>,
 <td class="titleColumn">
       70.
       <a href="/title/tt0375611/" title="Sanjay Leela Bhansali (dir.), Amitabh Bachchan, Rani Mukerji">Black</a>
 <span class="secondaryInfo">(2005)</span>
 </td>,
 <td class="titleColumn">
       71.
       <a href="/title/tt0054098/" title="K. Asif (dir.), Prithviraj Kapoor, Madhubala">Mughal-E-Azam</a>
 <span class="secondaryInfo">(1960)</span>
 </td>,
 <td class="titleColumn">
       72.
       <a href="/title/tt0104561/" title="Mansoor Khan (dir.), Aamir Khan, Ayesha Jhulka">Jo Jeeta Wohi Sikandar</a>
 <span class="secondaryInfo">(1992)</span>
 </td>,
 <td class="titleColumn">
       73.
       <a href="/title/tt1639426/" title="Vikramaditya Motwane (dir.), Rajat Barmecha, Ronit Roy">Udaan</a>
 <span class="secondaryInfo">(2010)</span>
 </td>,
 <td class="titleColumn">
       74.
       <a href="/title/tt2218988/" title="Anwar Rasheed (dir.), Dulquer Salmaan, Thilakan">Ustad Hotel</a>
 <span class="secondaryInfo">(2012)</span>
 </td>,
 <td class="titleColumn">
       75.
       <a href="/title/tt1562872/" title="Zoya Akhtar (dir.), Hrithik Roshan, Farhan Akhtar">Zindagi Na Milegi Dobara</a>
 <span class="secondaryInfo">(2011)</span>
 </td>,
 <td class="titleColumn">
       76.
       <a href="/title/tt1280558/" title="Neeraj Pandey (dir.), Anupam Kher, Naseeruddin Shah">A Wednesday</a>
 <span class="secondaryInfo">(2008)</span>
 </td>,
 <td class="titleColumn">
       77.
       <a href="/title/tt10324144/" title="Anubhav Sinha (dir.), Ayushmann Khurrana, Nassar">Article 15</a>
 <span class="secondaryInfo">(2019)</span>
 </td>,
 <td class="titleColumn">
       78.
       <a href="/title/tt3322420/" title="Vikas Bahl (dir.), Kangana Ranaut, Rajkummar Rao">Queen</a>
 <span class="secondaryInfo">(2013)</span>
 </td>,
 <td class="titleColumn">
       79.
       <a href="/title/tt0405508/" title="Rakeysh Omprakash Mehra (dir.), Aamir Khan, Soha Ali Khan">Rang De Basanti</a>
 <span class="secondaryInfo">(2006)</span>
 </td>,
 <td class="titleColumn">
       80.
       <a href="/title/tt0374887/" title="Rajkumar Hirani (dir.), Sanjay Dutt, Arshad Warsi">Munna Bhai M.B.B.S.</a>
 <span class="secondaryInfo">(2003)</span>
 </td>,
 <td class="titleColumn">
       81.
       <a href="/title/tt0292490/" title="Farhan Akhtar (dir.), Aamir Khan, Saif Ali Khan">Dil Chahta Hai</a>
 <span class="secondaryInfo">(2001)</span>
 </td>,
 <td class="titleColumn">
       82.
       <a href="/title/tt0200087/" title="John Mathew Matthan (dir.), Aamir Khan, Naseeruddin Shah">Sarfarosh</a>
 <span class="secondaryInfo">(1999)</span>
 </td>,
 <td class="titleColumn">
       83.
       <a href="/title/tt4851630/" title="Dileesh Pothan (dir.), Fahadh Faasil, Aparna Balamurali">Maheshinte Prathikaaram</a>
 <span class="secondaryInfo">(2016)</span>
 </td>,
 <td class="titleColumn">
       84.
       <a href="/title/tt4635372/" title="Neeraj Ghaywan (dir.), Richa Chadha, Sanjay Mishra">Masaan</a>
 <span class="secondaryInfo">(2015)</span>
 </td>,
 <td class="titleColumn">
       85.
       <a href="/title/tt2283748/" title="Umesh Shukla (dir.), Paresh Rawal, Akshay Kumar">OMG: Oh My God!</a>
 <span class="secondaryInfo">(2012)</span>
 </td>,
 <td class="titleColumn">
       86.
       <a href="/title/tt0109117/" title="Rajkumar Santoshi (dir.), Aamir Khan, Salman Khan">Andaz Apna Apna</a>
 <span class="secondaryInfo">(1994)</span>
 </td>,
 <td class="titleColumn">
       87.
       <a href="/title/tt0105271/" title="Mani Ratnam (dir.), Arvind Swamy, Madhoo">Roja</a>
 <span class="secondaryInfo">(1992)</span>
 </td>,
 <td class="titleColumn">
       88.
       <a href="/title/tt0242256/" title="Mani Ratnam (dir.), Madhavan, Shalini">Alai Payuthey</a>
 <span class="secondaryInfo">(2000)</span>
 </td>,
 <td class="titleColumn">
       89.
       <a href="/title/tt0169102/" title="Ashutosh Gowariker (dir.), Aamir Khan, Raghuvir Yadav">Lagaan: Once Upon a Time in India</a>
 <span class="secondaryInfo">(2001)</span>
 </td>,
 <td class="titleColumn">
       90.
       <a href="/title/tt0139876/" title="Suresh Krishna (dir.), Rajinikanth, Nagma">Baasha</a>
 <span class="secondaryInfo">(1995)</span>
 </td>,
 <td class="titleColumn">
       91.
       <a href="/title/tt7060460/" title="H. Vinoth (dir.), Karthi, Rakul Preet Singh">Theeran adhigaaram ondru</a>
 <span class="secondaryInfo">(2017)</span>
 </td>,
 <td class="titleColumn">
       92.
       <a href="/title/tt1821480/" title="Sujoy Ghosh (dir.), Vidya Balan, Parambrata Chattopadhyay">Kahaani</a>
 <span class="secondaryInfo">(2012)</span>
 </td>,
 <td class="titleColumn">
       93.
       <a href="/title/tt2338151/" title="Rajkumar Hirani (dir.), Aamir Khan, Anushka Sharma">PK</a>
 <span class="secondaryInfo">(2014)</span>
 </td>,
 <td class="titleColumn">
       94.
       <a href="/title/tt2358592/" title="Pawan Kumar (dir.), Sathish Neenasam, Sruthi Hariharan">Lucia</a>
 <span class="secondaryInfo">(2013)</span>
 </td>,
 <td class="titleColumn">
       95.
       <a href="/title/tt0453729/" title="Nagesh Kukunoor (dir.), Shreyas Talpade, Naseeruddin Shah">Iqbal</a>
 <span class="secondaryInfo">(2005)</span>
 </td>,
 <td class="titleColumn">
       96.
       <a href="/title/tt8291224/" title="Aditya Dhar (dir.), Vicky Kaushal, Paresh Rawal">Uri: The Surgical Strike</a>
 <span class="secondaryInfo">(2018)</span>
 </td>,
 <td class="titleColumn">
       97.
       <a href="/title/tt0319736/" title="Rajkumar Santoshi (dir.), Ajay Devgn, Sushant Singh">The Legend of Bhagat Singh</a>
 <span class="secondaryInfo">(2002)</span>
 </td>,
 <td class="titleColumn">
       98.
       <a href="/title/tt2082197/" title="Anurag Basu (dir.), Ranbir Kapoor, Priyanka Chopra">Barfi!</a>
 <span class="secondaryInfo">(2012)</span>
 </td>,
 <td class="titleColumn">
       99.
       <a href="/title/tt5571734/" title="Aniruddha Roy Chowdhury (dir.), Taapsee Pannu, Amitabh Bachchan">Pink</a>
 <span class="secondaryInfo">(2016)</span>
 </td>,
 <td class="titleColumn">
       100.
       <a href="/title/tt0843326/" title="Bhaskar (dir.), Siddharth, Genelia D'Souza">Bommarillu</a>
 <span class="secondaryInfo">(2006)</span>
 </td>,
 <td class="titleColumn">
       101.
       <a href="/title/tt0112553/" title="Mani Ratnam (dir.), Arvind Swamy, Manisha Koirala">Bombay</a>
 <span class="secondaryInfo">(1995)</span>
 </td>,
 <td class="titleColumn">
       102.
       <a href="/title/tt0379370/" title="Vishal Bhardwaj (dir.), Irrfan Khan, Tabu">Maqbool</a>

In [530]:
# storing 100 names into list
cnt=0
name=[]
for i in names:
    if cnt<100:
        name.append(i.text)
        cnt +=1

In [531]:
# storing temp name into name
temp_name=name
temp_name[0:5]

['\n      1.\n      Pather Panchali\n(1955)\n',
 '\n      2.\n      Gol Maal\n(1979)\n',
 '\n      3.\n      Nayakan\n(1987)\n',
 '\n      4.\n      Anbe Sivam\n(2003)\n',
 '\n      5.\n      Apur Sansar\n(1959)\n']

In [532]:

pure_final_name=[]                # declaring empty list for storing final names
years=[]                           # declaring empty list for storing years
fname=''                        # declaring empty string for temporary saving name 

for i in range(0,100):
    fname=temp_name[i]
    #print(fname)
    nnames=fname.split('\n')           # splitting the column using '\n' character
    #print(nnames)
    pure_final_name.append(nnames[2].lstrip())
    years.append(nnames[3])

In [533]:
#wait don;t do this

final_name=[]       # declaring empty list for storing list item   
names               # declaring empty string for converting list item into individual list    
fname
for i in range(0,100):
    names=temp_name[i]            # declaring individual item of list in a string
    fname=names.split('.')          # splitting the string into list
    final_name.append(fname[1].lstrip())     # appending the list items with the movie name and removing extra space

In [534]:
pure_final_name[0:5]

['Pather Panchali', 'Gol Maal', 'Nayakan', 'Anbe Sivam', 'Apur Sansar']

In [535]:
years[0:5]

['(1955)', '(1979)', '(1987)', '(2003)', '(1959)']

In [536]:
pyear=[]          # defining temporary list for saving years after replacing ')' with empty character
for i in range(0,100):
    pyear.append(years[i].replace(')',''))

pure_final_year=[]    # defining temporary list for saving years after replacing '(' with empty character
for i in range(0,100):
    pure_final_year.append(pyear[i].replace('(',''))

In [537]:
pure_final_year[0:5]

['1955', '1979', '1987', '2003', '1959']

In [538]:
rating=soup3.find_all('td',class_='ratingColumn imdbRating')
rating

[<td class="ratingColumn imdbRating">
 <strong title="8.5 based on 24,343 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 18,215 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 16,888 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 17,499 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.5 based on 12,466 user ratings">8.5</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 9,759 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 5,001 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 5,530 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 23,412 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 6,433 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 9,097 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 19,202 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 5,762 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 20,799 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 10,036 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.4 based on 352,355 user ratings">8.4</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 173,580 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 8,243 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 161,870 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 28,066 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 10,479 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 12,042 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 13,356 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 5,693 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 7,545 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 9,457 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.3 based on 7,676 user ratings">8.3</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 11,804 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 13,723 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 13,800 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 17,232 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 31,467 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 11,957 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 13,314 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 34,934 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 29,921 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 59,474 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 5,146 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 11,400 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 22,503 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 10,639 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 9,017 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 30,101 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 10,176 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 75,528 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 5,927 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 17,711 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 13,687 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 15,458 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 15,128 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 13,092 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 17,078 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.2 based on 6,726 user ratings">8.2</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 6,249 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 9,263 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 84,464 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 10,504 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 61,888 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 11,596 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 33,706 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 51,929 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 84,198 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 31,779 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 58,241 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 5,518 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 5,337 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 73,148 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 5,897 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 75,050 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 33,628 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 7,432 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 21,926 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 42,823 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 12,147 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 69,221 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 74,515 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 24,668 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 61,371 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 113,691 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 74,954 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 67,554 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 24,209 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 7,189 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 24,401 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 52,577 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 49,815 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 11,964 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 5,530 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 106,294 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 9,125 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 10,922 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 58,493 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 166,020 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 11,595 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 16,036 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 44,557 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.1 based on 15,045 user ratings">8.1</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 76,682 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 40,195 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 8,753 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 11,603 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 9,830 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 19,433 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 12,507 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 43,666 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 35,714 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 11,050 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 10,246 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 76,902 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 64,302 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 14,099 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 6,345 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 6,161 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 50,968 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 5,114 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 12,301 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 8,692 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 20,485 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 5,242 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 5,055 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 32,988 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 5,915 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="8.0 based on 19,506 user ratings">8.0</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 51,676 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 6,827 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 29,054 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 5,026 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 28,814 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 5,327 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 6,915 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 73,591 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 12,843 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 7,157 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 10,465 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 10,453 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 14,669 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 21,698 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 6,726 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 39,009 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 18,001 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 7,084 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 99,716 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 64,217 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 48,400 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 6,023 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.9 based on 6,291 user ratings">7.9</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 5,105 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 113,550 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 5,314 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 14,131 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 22,001 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 8,401 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 21,101 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 5,743 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 5,117 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 21,941 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 6,833 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 104,623 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 53,332 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 53,329 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 11,693 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 34,048 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 6,406 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 8,669 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 15,965 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 24,054 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 10,141 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 51,534 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 11,688 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 8,290 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 21,433 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.8 based on 23,245 user ratings">7.8</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.7 based on 8,979 user ratings">7.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.7 based on 12,896 user ratings">7.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.7 based on 14,305 user ratings">7.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.7 based on 14,656 user ratings">7.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.7 based on 40,159 user ratings">7.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.7 based on 26,009 user ratings">7.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.7 based on 27,607 user ratings">7.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.7 based on 11,455 user ratings">7.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.7 based on 6,396 user ratings">7.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.7 based on 12,620 user ratings">7.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">
 <strong title="7.7 based on 21,048 user ratings">7.7</strong>
 </td>,
 <td class="ratingColumn imdbRating">

In [539]:
final_Ratings=[]
cnt=0
for i in rating:
    if cnt<100:
        final_Ratings.append(i.text.replace('\n',''))
        cnt += 1

In [540]:
final_Ratings[0:5]

['8.5', '8.5', '8.5', '8.5', '8.5']

In [541]:
print(len(pure_final_name),len(pure_final_year),len(final_Ratings))

100 100 100

In [542]:
import pandas as pd
IMDB_TOP_100_INDIAN_MOVIES= pd.DataFrame({})
IMDB_TOP_100_INDIAN_MOVIES['Name']=pure_final_name
IMDB_TOP_100_INDIAN_MOVIES['IMDB Ratings']=final_Ratings
IMDB_TOP_100_INDIAN_MOVIES['Year of release']=pure_final_year

In [543]:
IMDB_TOP_100_INDIAN_MOVIES

                          Name IMDB Ratings Year of release
0              Pather Panchali          8.5            1955
1                     Gol Maal          8.5            1979
2                      Nayakan          8.5            1987
3                   Anbe Sivam          8.5            2003
4                  Apur Sansar          8.5            1959
..                         ...          ...             ...
95    Uri: The Surgical Strike          8.1            2018
96  The Legend of Bhagat Singh          8.1            2002
97                      Barfi!          8.0            2012
98                        Pink          8.0            2016
99                  Bommarillu          8.0            2006

[100 rows x 3 columns]

In [544]:
IMDB_TOP_100_INDIAN_MOVIES.to_csv('IMDB_TOP_100_INDIAN_MOVIES.csv',index=False)

# Assignment Question No 4:

##### Write a python program to scrap book name, author name, genre and book review of any 5 books from ‘www.bookpage.com’

In [545]:
page4=requests.get('https://bookpage.com/')
page4

In [546]:
soup4=BeautifulSoup(page4.content)

In [547]:
names=soup4.find_all('h4',class_='italic')            #
names

[<h4 class="italic">
 <a href="/behind-the-book/26332-china-then-now-mystery-suspense">China, then and now</a>
 </h4>,
 <h4 class="italic">
 <a href="/interviews/26331-katy-birchall-romance">Katy Birchall</a>
 </h4>,
 <h4 class="italic">
 <a href="/reviews/26206-daniel-james-brown-facing-mountain-history"> <span style="font-style:normal;">★ </span>Facing the Mountain</a>
 </h4>,
 <h4 class="italic">
 <a href="/reviews/26241-jamie-pacton-lucky-girl-ya">Lucky Girl</a>
 </h4>,
 <h4 class="italic">
 <a href="/reviews/26242-remy-lai-pawcasso-childrens">Pawcasso</a>
 </h4>,
 <h4 class="italic">
 <a href="/reviews/26211-annette-gordon-reed-juneteenth-history"> <span style="font-style:normal;">★ </span>On Juneteenth</a>
 </h4>]

In [548]:
book_name=[]
for i in names:
    book_name.append(i.text.replace('\n',''))
book_name

['China, then and now',
 'Katy Birchall',
 ' ★ Facing the Mountain',
 'Lucky Girl',
 'Pawcasso',
 ' ★ On Juneteenth']

In [549]:
del book_name[1]

In [550]:
book_name

['China, then and now',
 ' ★ Facing the Mountain',
 'Lucky Girl',
 'Pawcasso',
 ' ★ On Juneteenth']

In [551]:
genres=soup4.find_all('p',class_='genre-links hidden-phone')
genres

[<p class="genre-links hidden-phone">
 <a href="/search?book_genre=mystery_suspense">Mystery &amp; Suspense</a>
  /
 <a href="/search?book_genre=mystery">Mystery</a>
 </p>,
 <p class="genre-links hidden-phone">
 <a href="/search?book_genre=romance">Romance</a>
  /
 <a href="/search?book_genre=contemporary_romance">Contemporary Romance</a>
 </p>,
 <p class="genre-links hidden-phone">
 <a href="/search?book_genre=nonfiction">Nonfiction</a>
  /
 <a href="/search?book_genre=history">History</a>
  /
 <a href="/search?book_genre=american_history">American History</a>
 </p>,
 <p class="genre-links hidden-phone">
 <a href="/search?book_genre=ya_fiction">YA Fiction</a>
  /
 <a href="/search?book_genre=ya">YA</a>
 </p>,
 <p class="genre-links hidden-phone">
 <a href="/search?book_genre=children_s">Children's</a>
  /
 <a href="/search?book_genre=middle_grade">Middle Grade</a>
 </p>,
 <p class="genre-links hidden-phone">
 <a href="/search?book_genre=nonfiction">Nonfiction</a>
  /
 <a href="/search?book_genre=history">History</a>
  /
 <a href="/search?book_genre=american_history">American History</a>
 </p>]

In [552]:
genre=[]
for i in genres:
    genre.append(i.text.replace('\n',''))
genre

['Mystery & Suspense / Mystery',
 'Romance / Contemporary Romance',
 'Nonfiction / History / American History',
 'YA Fiction / YA',
 "Children's / Middle Grade",
 'Nonfiction / History / American History']

In [553]:
del genre[1]

In [554]:
#extracted links from the page

link_list=['https://bookpage.com/behind-the-book/26332-china-then-now-mystery-suspense#.YJTlALUzZPY',
           'https://bookpage.com/reviews/26242-remy-lai-pawcasso-childrens#.YJTTmLUzZPY',
           'https://bookpage.com/reviews/26211-annette-gordon-reed-juneteenth-nonfiction#.YJTjULUzZPY',
           'https://bookpage.com/reviews/26198-chanel-cleeton-most-beautiful-girl-cuba-fiction#.YJTjwrUzZPY',
           'https://bookpage.com/reviews/26164-sean-flynn-why-peacocks-nonfiction#.YJTkLrUzZPY']

In [555]:
# function to search items

def function_book(soup_object):
        name1=soup_object.find('h1',class_='italic')
        author1=book1_soup.find('h4',class_='sans')
        reviews=book1_soup.find_all('p')
        name=name1.text.replace('\n','')
        author=author1.text.replace('\n','')
        book1_review=[]
        for i in range(1,10):
            book1_review.append(reviews[i].text.replace('\n',''))
            book1_review
        book_review=book1_review
        dict1=dict({})
        dict1['name_of_book']=name
        dict1['author_of_book']=author
        dict1['review']=book_review
        return(dict1)

In [556]:
# finding author names from all the pges through link_list
author_name=[]
for i in link_list:
    page_book=requests.get(i)
    book_soup=BeautifulSoup(page_book.content)
    author1=book_soup.find('h4',class_='sans')
    print(author1)
    author_name.append(author1)

<h4 class="sans">
China, then and now
</h4>
<h4 class="sans">
Remy Lai
</h4>
<h4 class="sans">
Annette Gordon-Reed
</h4>
<h4 class="sans">
Chanel Cleeton
</h4>
<h4 class="sans">
Sean Flynn
</h4>

In [557]:
Author_name=[]
for i in author_name:
    Author_name.append(i.text.replace('\n',''))
Author_name

['China, then and now',
 'Remy Lai',
 'Annette Gordon-Reed',
 'Chanel Cleeton',
 'Sean Flynn']

In [558]:
# function to convert  list item as a string for review column
def convert(s):
    # initialization of string to ""
    new = ""
  
    # traverse in the string 
    for x in s:
        new += x 
  
    # return string 
    return new

In [559]:
sf_review=[]             # empty list to store reviews
for i in link_list:
    page_book=requests.get(i)
    book_soup=BeautifulSoup(page_book.content)
    reviews=book_soup.find_all('p')
    #print(reviews)
    semi_review=[]
    for i in range(0,10):
        semi_review.append(reviews[i].text.replace('\n',''))        # appending reviews in a list
    #print(semi_review)
    ssf=convert(semi_review)
    print(ssf)
    sf_review.append(ssf)       # appending reviews as a list item

Behind the bookBookPage Behind the Book byBrian KlingborgMay 04, 2021Brian Klingborg’s Thief of Souls follows Inspector Lu Fei as he hunts a serial killer operating around a tiny town in northeast China. In this essay, Klingborg explores his enduring fascination with China and the unique combination of factors that make it a perfect setting for a mystery.I first visited China in the summer of 1987 and took a three-week odyssey by sleeper train from Guangzhou to Nanjing, Shanghai, Xian—home of the famous terra-cotta warriors—and finally to Beijing.Despite economic reforms launched in 1978, the country seemed caught in a time warp during that hot, humid summer. Most businesses remained state-owned, and the nefarious “iron rice bowl” system was in full effect—many workers enjoyed job security, but low wages and a lack of merit pay led to poor motivation.Like the country itself, Shanghai was frozen in time. Grandiose European buildings dating to the late 19th and early 20th centuries lined the Bund but were mostly derelict. Beijing was a city of expansive highways, nearly devoid of vehicles. The pickings were slim in food aisles. If you wanted chocolate or other import items, you had to go to a “Friendship Store”—where no Chinese citizens were allowed to shop—and pay with “foreign exchange certificates.” Tiananmen Square was vast and empty, and viewing Mao’s corpse required only a short wait in line.My, how times have changed . . .Shanghai is now a city of towering skyscrapers and blinding lights. Private industry is booming, and upward mobility is the name of the game. Foreign goods are widely available, and judging from the Louis Vuitton handbags and designer clothes in evidence, people have the money to pay for them. Beijing’s roads are clogged with stop-and-go traffic, much of it consisting of imported luxury cars. And you can forget about visiting Mao—the line currently stretches for what seems like the entire length of the Great Wall.
Book reviewsReview bySharon VerbetenMay 07, 2021Pawcasso is a joyful graphic novel from acclaimed author-illustrator Remy Lai (Pie in the Sky) that abounds with silliness, camaraderie and a few white lies.A dog wanders around town, holding a basket in his mouth. There’s a shopping list inside the basket, but why is the dog shopping on his own? Where is his owner? And where will he go next? Jo is bored, upset that her father has left on yet another extended work trip and eager for a distraction. When she sees the dog pass by her house, she slips out of her yard and follows him into the cleverly named Dog Ears bookstore, where a children’s painting class is being held in an upstairs meeting room.The class is so enamored with the charming dog that they name him Pawcasso and invite both him and Jo back for the next class, under the mistaken impression that the dog belongs to Jo. Though she wonders where his owners are, Jo effectively adopts Pawcasso, going so far as to give him a bath after he rolls in something stinky. She quickly comes to love the attention she receives when everyone believes that Pawcasso is her dog.But not all of Jo’s neighbors find Pawcasso charming. It turns out that the Duchamp family has submitted a petition to the city council that would require all dogs to be leashed, and the town quickly becomes divided over the issue. How can Jo protect Pawcasso when he doesn’t even belong to her?All over town, children and adults work together to support their side of the debate in an excellent depiction of civic engagement. Characters respectfully stand up for their beliefs, gather support and follow through. Lai’s candy-colored, cartoon-style illustrations are a delightful complement to this cute, clever romp. The book is full of well-executed canine puns and jokes, including Jo’s fabulously phrased apology: “I made a Chihuahua-sized lie, but it snowballed into a Great Dane-sized lie.”Readers who enjoyed Lai’s two previous illustrated middle grade novels will love Pawcasso, her first graphic novel. It’s a gentle story of community, forgiveness and redemption.
Book reviewsReview byDeborah MasonMay 2021Annette Gordon-Reed opens On Juneteenth by reflecting on her conflicted emotions about Juneteenth becoming a national celebration. It is, she notes, a distinctly Texan holiday, since it commemorates the day in June 1865 when Major General Gordon Granger arrived in Galveston to announce the end of legalized slavery in the United States—two months after Lee surrendered to Grant at Appomattox. It’s also a deeply personal holiday, one that Black Texans have celebrated with family and friends ever since Granger read out his proclamation. And yet, Gordon-Reed acknowledges, it’s also a profoundly American holiday, just as Texas is perhaps the most profoundly American state.This ambivalence inspires Gordon-Reed to explore the significance of this holiday within the broader context of Texan history. On Juneteenth is a collection of historical essays, ranging from the Spanish conquest to the present, that investigates what it means to be Texan. Against the background of the archetypal white cowboy and the ten-gallon hat oilman, Gordon-Reed demonstrates how the history of Texas is also the history of African Americans, Native Americans and Mexican Americans. Indeed, slavery was integral to the formation of the Republic of Texas—as well as the state of Texas. Understanding this truth, Gordon-Reed argues, is key to understanding the role racism continues to play in Texas and, by extension, the nation.As the Carl W. Loeb Professor of history at Harvard, Gordon-Reed is no stranger to illuminating the uncomfortable truths of our past. She won the Pulitzer Prize and the National Book Award for The Hemingses of Monticello: An American Family, a groundbreaking multigenerational history of the descendants of Thomas Jefferson and Sally Hemings, an enslaved African American woman.On Juneteenth is written on a smaller and more personal scale than her previous work, but it is no less powerful. Gordon-Reed’s essays seamlessly merge history and memoir into a complex portrait of her beloved, turbulent Texas, revealing new truths about a state that, more than any other, embodies all the virtues and faults of America. ByAnnette Gordon-ReedLiveright$15.95ISBN9781631498831Published05/04/2021
Book reviewsReview byAmy ScribnerMay 2021Through her popular historical novels, bestselling author Chanel Cleeton offers a fresh glimpse into Cuba’s tumultuous past. Her latest, The Most Beautiful Girl in Cuba, is set on the eve of the Spanish-American War, as the island country is ravaged by conflict between Cuban revolutionaries and the Spanish military.The story unfolds through the eyes of three women: Evangelina Cisneros, a beautiful socialite who finds herself in the infamous Recogidas prison after rebuffing the advances of a Spanish military official; Marina Perez, who along with her husband is aiding the revolutionaries while living in deplorable conditions at a reconcentration camp; and Grace Harrington, a cub reporter trying to make her mark at William Randolph Hearst’s New York newspaper.The women all come from wealthy families yet have chosen their own paths as they seek more than the comfort provided by their privilege. This is a recurring theme in Cleeton’s work: women turning their lives upside down to fight for what they believe in. For Evangelina and Marina, they’re fighting for the dream of a liberated Cuba. For Grace, it’s a career as a serious journalist in an era when few women (aside from Nellie Bly and Ida B. Wells) could imagine working for a newspaper. Their fates intersect when Hearst places Grace on the Cuba beat, reporting from the front lines.The heart of The Most Beautiful Girl in Cuba is ostensibly Evangelina, who is the title character and based on a real person. And indeed, her story is fascinating. She was briefly the most famous woman in New York after a daring rescue landed her stateside to advocate for Cuban independence. But Cleeton’s examination of the state of journalism at the turn of the century is an equally compelling part of this engrossing book. The battle of Hearst versus Joseph Pulitzer for the biggest circulation is fascinating. Both of their newspapers used the discord in Cuba to bolster their sales and arguably influenced the conflict more than was appropriate for a supposedly neutral press.Cleeton delivers a sweeping story of love and courage, as well as a sobering reminder of the power and responsibility of the media.ByChanel Cleeton
Book reviewsReview bySarah McCraw CrowMay 2021Have you ever thought, What my household needs is a few peacocks? Me neither. But that didn’t stop me from enjoying Sean Flynn’s Why Peacocks? An Unlikely Search for Meaning in the World’s Most Magnificent Bird, which details what happened after his family took on some pet peacocks. Flynn; his wife, Louise; and their two young sons already had two chickens, a dog and a cat—so when a friend asked if they wanted a peacock, they didn’t immediately say no. Before long, the family had adopted three: Carl, Mr. Pickle and Ethel.Flynn, a longtime magazine journalist, often writes about emotional subjects, such as Arizona firefighters who died battling a wildfire or the 2011 domestic terrorist attack in Norway, and he doesn’t shy away from sentiment here either. Still, he approaches his subject with a science writer’s eye for detail. “The noise began in the middle of April,” he writes about the peacocks’ mating calls, for instance. “Mr. Pickle, a rising two-note burst, E above middle C, up to G, a quick slur down to F-sharp . . . not a plaintive cry, desperate and whiny, but assertive, a robust announcement; I am here.”Flynn charts his own increasing obsession with the birds, the hours he spends each day in a lawn chair, aiming to entice the skittish peacocks to eat a blueberry out of his hand. When Carl becomes gravely ill, the endeavor to treat the peacock will be familiar to any pet owner who’s pondered the price of veterinary care, and yet far stranger. The narrative of Why Peacocks? alternates between this family’s story and more journalistic accounts, as Flynn leads us through a natural and cultural history of peacocks, including the evolution of male peacocks’ shimmering feather trains and the roles peacocks have played in religious traditions, making entertaining digressions along the way. He visits Palos Verdes, California, where peacocks have become a nuisance, and Dunfermline, Scotland, where a long-ago gift from Andrew Carnegie led to iconic peacocks in a public park.Although this book is a quick read, it’s well researched with an extensive bibliography. Sweet and often funny, Why Peacocks? is an engaging mix of memoir, history and journalism.BySean Flynn

In [560]:
sf_review

['Behind the bookBookPage Behind the Book byBrian KlingborgMay 04, 2021Brian Klingborg’s Thief of Souls follows Inspector Lu Fei as he hunts a serial killer operating around a tiny town in northeast China. In this essay, Klingborg explores his enduring fascination with China and the unique combination of factors that make it a perfect setting for a mystery.I first visited China in the summer of 1987 and took a three-week odyssey by sleeper train from Guangzhou to Nanjing, Shanghai, Xian—home of the famous terra-cotta warriors—and finally to Beijing.Despite economic reforms launched in 1978, the country seemed caught in a time warp during that hot, humid summer. Most businesses remained state-owned, and the nefarious “iron rice bowl” system was in full effect—many workers enjoyed job security, but low wages and a lack of merit pay led to poor motivation.Like the country itself, Shanghai was frozen in time. Grandiose European buildings dating to the late 19th and early 20th centuries lined the Bund but were mostly derelict. Beijing was a city of expansive highways, nearly devoid of vehicles. The pickings were slim in food aisles. If you wanted chocolate or other import items, you had to go to a “Friendship Store”—where no Chinese citizens were allowed to shop—and pay with “foreign exchange certificates.” Tiananmen Square was vast and empty, and viewing Mao’s corpse required only a short wait in line.My, how times have changed . . .Shanghai is now a city of towering skyscrapers and blinding lights. Private industry is booming, and upward mobility is the name of the game. Foreign goods are widely available, and judging from the Louis Vuitton handbags and designer clothes in evidence, people have the money to pay for them. Beijing’s roads are clogged with stop-and-go traffic, much of it consisting of imported luxury cars. And you can forget about visiting Mao—the line currently stretches for what seems like the entire length of the Great Wall.',
 'Book reviewsReview bySharon VerbetenMay 07, 2021Pawcasso is a joyful graphic novel from acclaimed author-illustrator Remy Lai (Pie in the Sky) that abounds with silliness, camaraderie and a few white lies.A dog wanders around town, holding a basket in his mouth. There’s a shopping list inside the basket, but why is the dog shopping on his own? Where is his owner? And where will he go next? Jo is bored, upset that her father has left on yet another extended work trip and eager for a distraction. When she sees the dog pass by her house, she slips out of her yard and follows him into the cleverly named Dog Ears bookstore, where a children’s painting class is being held in an upstairs meeting room.The class is so enamored with the charming dog that they name him Pawcasso and invite both him and Jo back for the next class, under the mistaken impression that the dog belongs to Jo. Though she wonders where his owners are, Jo effectively adopts Pawcasso, going so far as to give him a bath after he rolls in something stinky. She quickly comes to love the attention she receives when everyone believes that Pawcasso is her dog.But not all of Jo’s neighbors find Pawcasso charming. It turns out that the Duchamp family has submitted a petition to the city council that would require all dogs to be leashed, and the town quickly becomes divided over the issue. How can Jo protect Pawcasso when he doesn’t even belong to her?All over town, children and adults work together to support their side of the debate in an excellent depiction of civic engagement. Characters respectfully stand up for their beliefs, gather support and follow through. Lai’s candy-colored, cartoon-style illustrations are a delightful complement to this cute, clever romp. The book is full of well-executed canine puns and jokes, including Jo’s fabulously phrased apology: “I made a Chihuahua-sized lie, but it snowballed into a Great Dane-sized lie.”Readers who enjoyed Lai’s two previous illustrated middle grade novels will love Pawcasso, her first graphic novel. It’s a gentle story of community, forgiveness and redemption.',
 'Book reviewsReview byDeborah MasonMay 2021Annette Gordon-Reed opens On Juneteenth by reflecting on her conflicted emotions about Juneteenth becoming a national celebration. It is, she notes, a distinctly Texan holiday, since it commemorates the day in June 1865 when Major General Gordon Granger arrived in Galveston to announce the end of legalized slavery in the United States—two months after Lee surrendered to Grant at Appomattox. It’s also a deeply personal holiday, one that Black Texans have celebrated with family and friends ever since Granger read out his proclamation. And yet, Gordon-Reed acknowledges, it’s also a profoundly American holiday, just as Texas is perhaps the most profoundly American state.This ambivalence inspires Gordon-Reed to explore the significance of this holiday within the broader context of Texan history. On Juneteenth is a collection of historical essays, ranging from the Spanish conquest to the present, that investigates what it means to be Texan. Against the background of the archetypal white cowboy and the ten-gallon hat oilman, Gordon-Reed demonstrates how the history of Texas is also the history of African Americans, Native Americans and Mexican Americans. Indeed, slavery was integral to the formation of the Republic of Texas—as well as the state of Texas. Understanding this truth, Gordon-Reed argues, is key to understanding the role racism continues to play in Texas and, by extension, the nation.As the Carl W. Loeb Professor of history at Harvard, Gordon-Reed is no stranger to illuminating the uncomfortable truths of our past. She won the Pulitzer Prize and the National Book Award for The Hemingses of Monticello: An American Family, a groundbreaking multigenerational history of the descendants of Thomas Jefferson and Sally Hemings, an enslaved African American woman.On Juneteenth is written on a smaller and more personal scale than her previous work, but it is no less powerful. Gordon-Reed’s essays seamlessly merge history and memoir into a complex portrait of her beloved, turbulent Texas, revealing new truths about a state that, more than any other, embodies all the virtues and faults of America.\xa0ByAnnette Gordon-ReedLiveright$15.95ISBN9781631498831Published05/04/2021',
 'Book reviewsReview byAmy ScribnerMay 2021Through her popular historical novels, bestselling author Chanel Cleeton offers a fresh glimpse into Cuba’s tumultuous past. Her latest, The Most Beautiful Girl in Cuba, is set on the eve of the Spanish-American War, as the island country is ravaged by conflict between Cuban revolutionaries and the Spanish military.The story unfolds through the eyes of three women: Evangelina Cisneros, a beautiful socialite who finds herself in the infamous Recogidas prison after rebuffing the advances of a Spanish military official; Marina Perez, who along with her husband is aiding the revolutionaries while living in deplorable conditions at a reconcentration camp; and Grace Harrington, a cub reporter trying to make her mark at William Randolph Hearst’s New York newspaper.The women all come from wealthy families yet have chosen their own paths as they seek more than the comfort provided by their privilege. This is a recurring theme in Cleeton’s work: women turning their lives upside down to fight for what they believe in. For Evangelina and Marina, they’re fighting for the dream of a liberated Cuba. For Grace, it’s a career as a serious journalist in an era when few women (aside from Nellie Bly and Ida B. Wells) could imagine working for a newspaper. Their fates intersect when Hearst places Grace on the Cuba beat, reporting from the front lines.The heart of The Most Beautiful Girl in Cuba is ostensibly Evangelina, who is the title character and based on a real person. And indeed, her story is fascinating. She was briefly the most famous woman in New York after a daring rescue landed her stateside to advocate for Cuban independence. But Cleeton’s examination of the state of journalism at the turn of the century is an equally compelling part of this engrossing book. The battle of Hearst versus Joseph Pulitzer for the biggest circulation is fascinating. Both of their newspapers used the discord in Cuba to bolster their sales and arguably influenced the conflict more than was appropriate for a supposedly neutral press.Cleeton delivers a sweeping story of love and courage, as well as a sobering reminder of the power and responsibility of the media.ByChanel Cleeton',
 'Book reviewsReview bySarah McCraw CrowMay 2021Have you ever thought, What my household needs is a few peacocks? Me neither. But that didn’t stop me from enjoying Sean Flynn’s Why Peacocks? An Unlikely Search for Meaning in the World’s Most Magnificent Bird, which details what happened after his family took on some pet peacocks. Flynn; his wife, Louise; and their two young sons already had two chickens, a dog and a cat—so when a friend asked if they wanted a peacock, they didn’t immediately say no. Before long, the family had adopted three: Carl, Mr. Pickle and Ethel.Flynn, a longtime magazine journalist, often writes about emotional subjects, such as Arizona firefighters who died battling a wildfire or the 2011 domestic terrorist attack in Norway, and he doesn’t shy away from sentiment here either. Still, he approaches his subject with a science writer’s eye for detail. “The noise began in the middle of April,” he writes about the peacocks’ mating calls, for instance. “Mr. Pickle, a rising two-note burst, E above middle C, up to G, a quick slur down to F-sharp . . . not a plaintive cry, desperate and whiny, but assertive, a robust announcement; I am here.”Flynn charts his own increasing obsession with the birds, the hours he spends each day in a lawn chair, aiming to entice the skittish peacocks to eat a blueberry out of his hand. When Carl becomes gravely ill, the endeavor to treat the peacock will be familiar to any pet owner who’s pondered the price of veterinary care, and yet far stranger.\xa0The narrative of Why Peacocks? alternates between this family’s story and more journalistic accounts, as Flynn leads us through a natural and cultural history of peacocks, including the evolution of male peacocks’ shimmering feather trains and the roles peacocks have played in religious traditions, making entertaining digressions along the way. He visits Palos Verdes, California, where peacocks have become a nuisance, and Dunfermline, Scotland, where a long-ago gift from Andrew Carnegie led to iconic peacocks in a public park.Although this book is a quick read, it’s well researched with an extensive bibliography. Sweet and often funny, Why Peacocks? is an engaging mix of memoir, history and journalism.BySean Flynn']

In [561]:
import pandas as pd
book_table=pd.DataFrame({})
book_table['Book Name']=book_name
book_table['Author Name']=Author_name
book_table['Genre']=genre
book_table['Review']=sf_review

In [562]:
book_table

,Book Name,Author Name,Genre,Review
0,"China, then and now","China, then and now",Mystery & Suspense / Mystery,Behind the bookBookPage Behind the Book byBria...
1,★ Facing the Mountain,Remy Lai,Nonfiction / History / American History,"Book reviewsReview bySharon VerbetenMay 07, 20..."
2,Lucky Girl,Annette Gordon-Reed,YA Fiction / YA,Book reviewsReview byDeborah MasonMay 2021Anne...
3,Pawcasso,Chanel Cleeton,Children's / Middle Grade,Book reviewsReview byAmy ScribnerMay 2021Throu...
4,★ On Juneteenth,Sean Flynn,Nonfiction / History / American History,Book reviewsReview bySarah McCraw CrowMay 2021...

In [563]:
book_table['Author Name'][0]='Brian Klingborg'

In [564]:
book_table

,Book Name,Author Name,Genre,Review
0,"China, then and now",Brian Klingborg,Mystery & Suspense / Mystery,Behind the bookBookPage Behind the Book byBria...
1,★ Facing the Mountain,Remy Lai,Nonfiction / History / American History,"Book reviewsReview bySharon VerbetenMay 07, 20..."
2,Lucky Girl,Annette Gordon-Reed,YA Fiction / YA,Book reviewsReview byDeborah MasonMay 2021Anne...
3,Pawcasso,Chanel Cleeton,Children's / Middle Grade,Book reviewsReview byAmy ScribnerMay 2021Throu...
4,★ On Juneteenth,Sean Flynn,Nonfiction / History / American History,Book reviewsReview bySarah McCraw CrowMay 2021...

# Assignment Question No 5

Write a python program to scrape cricket rankings from ‘www.icc-cricket.com’.

You have to scrape:
    
    i) Top 10 ODI teams in men’s cricket along with the records for matches, points and rating. 
    
    ii) Top 10 ODI Batsmen in men along with the records of their team and rating.
    
    iii) Top 10 ODI bowlers along with the records of their team and rating

In [565]:
page5=requests.get('https://www.icc-cricket.com/rankings/mens/team-rankings/odi')
page5

In [566]:
# printing the content of the page
#page5.content

In [567]:
soup5=BeautifulSoup(page5.content)
#soup5

In [568]:
#print(soup5.prettify())

In [569]:
name=soup5.find_all('span',class_='u-hide-phablet')
name

[<span class="u-hide-phablet">New Zealand</span>,
 <span class="u-hide-phablet">Australia</span>,
 <span class="u-hide-phablet">India</span>,
 <span class="u-hide-phablet">England</span>,
 <span class="u-hide-phablet">South Africa</span>,
 <span class="u-hide-phablet">Pakistan</span>,
 <span class="u-hide-phablet">Bangladesh</span>,
 <span class="u-hide-phablet">West Indies</span>,
 <span class="u-hide-phablet">Sri Lanka</span>,
 <span class="u-hide-phablet">Afghanistan</span>,
 <span class="u-hide-phablet">Netherlands</span>,
 <span class="u-hide-phablet">Ireland</span>,
 <span class="u-hide-phablet">Zimbabwe</span>,
 <span class="u-hide-phablet">Oman</span>,
 <span class="u-hide-phablet">Scotland</span>,
 <span class="u-hide-phablet">Nepal</span>,
 <span class="u-hide-phablet">UAE</span>,
 <span class="u-hide-phablet">Namibia</span>,
 <span class="u-hide-phablet">United States</span>,
 <span class="u-hide-phablet">Papua New Guinea</span>,
 <span class="icn icn-facebook-circle u-hide-phablet"></span>,
 <span class="icn icn-twitter-circle u-hide-phablet"></span>,
 <span class="icn icn-instagram-circle u-hide-phablet"></span>,
 <span class="icn icn-youtube-circle u-hide-phablet"></span>,
 <span class="icn icn-tiktok-circle u-hide-phablet"></span>]

In [570]:
team_name=[]             
cnt=0
for i in name:
    if cnt<10:
        team_name.append(i.text.replace('\n',''))
        cnt+=1
team_name

['New Zealand',
 'Australia',
 'India',
 'England',
 'South Africa',
 'Pakistan',
 'Bangladesh',
 'West Indies',
 'Sri Lanka',
 'Afghanistan']

In [571]:
match=soup5.find_all('td',class_='rankings-block__banner--matches')
match

In [572]:
matches=soup5.find_all('td',class_='table-body__cell u-center-text')
matches

[<td class="table-body__cell u-center-text">25</td>,
 <td class="table-body__cell u-center-text">2,945</td>,
 <td class="table-body__cell u-center-text">29</td>,
 <td class="table-body__cell u-center-text">3,344</td>,
 <td class="table-body__cell u-center-text">27</td>,
 <td class="table-body__cell u-center-text">3,100</td>,
 <td class="table-body__cell u-center-text">20</td>,
 <td class="table-body__cell u-center-text">2,137</td>,
 <td class="table-body__cell u-center-text">24</td>,
 <td class="table-body__cell u-center-text">2,323</td>,
 <td class="table-body__cell u-center-text">24</td>,
 <td class="table-body__cell u-center-text">2,157</td>,
 <td class="table-body__cell u-center-text">27</td>,
 <td class="table-body__cell u-center-text">2,222</td>,
 <td class="table-body__cell u-center-text">21</td>,
 <td class="table-body__cell u-center-text">1,652</td>,
 <td class="table-body__cell u-center-text">17</td>,
 <td class="table-body__cell u-center-text">1,054</td>,
 <td class="table-body__cell u-center-text">2</td>,
 <td class="table-body__cell u-center-text">99</td>,
 <td class="table-body__cell u-center-text">18</td>,
 <td class="table-body__cell u-center-text">818</td>,
 <td class="table-body__cell u-center-text">15</td>,
 <td class="table-body__cell u-center-text">588</td>,
 <td class="table-body__cell u-center-text">7</td>,
 <td class="table-body__cell u-center-text">240</td>,
 <td class="table-body__cell u-center-text">5</td>,
 <td class="table-body__cell u-center-text">148</td>,
 <td class="table-body__cell u-center-text">5</td>,
 <td class="table-body__cell u-center-text">119</td>,
 <td class="table-body__cell u-center-text">9</td>,
 <td class="table-body__cell u-center-text">190</td>,
 <td class="table-body__cell u-center-text">6</td>,
 <td class="table-body__cell u-center-text">97</td>,
 <td class="table-body__cell u-center-text">8</td>,
 <td class="table-body__cell u-center-text">93</td>,
 <td class="table-body__cell u-center-text">5</td>,
 <td class="table-body__cell u-center-text">0</td>]

###### as we can observe that  'table-body__cell u-center-text' is for both matches and point so we will work with alternate index

In [573]:
no_of_matches=['17']             
points =['2054']
cnt=0
for i in range(1,20):
    if cnt<19:
        if i%2==0:
            no_of_matches.append(matches[i].text.replace('\n',''))
        else:
            points.append(matches[i].text.replace('\n',''))
cnt+=1

In [574]:
no_of_matches

['17', '29', '27', '20', '24', '24', '27', '21', '17', '2']

In [575]:
points

['2054',
 '2,945',
 '3,344',
 '3,100',
 '2,137',
 '2,323',
 '2,157',
 '2,222',
 '1,652',
 '1,054',
 '99']

In [576]:

ratings=soup5.find('td',class_='rankings-block__banner--rating u-text-right')
ratings

<td class="rankings-block__banner--rating u-text-right">
                            121
                            <span class="circle-branding circle-branding--top"></span>
<span class="circle-branding circle-branding--bottom"></span>
</td>

In [577]:
print(ratings.text)

                            121

In [578]:
ratings=soup5.find_all('td','table-body__cell u-text-right rating')
ratings

[<td class="table-body__cell u-text-right rating">118</td>,
 <td class="table-body__cell u-text-right rating">115</td>,
 <td class="table-body__cell u-text-right rating">115</td>,
 <td class="table-body__cell u-text-right rating">107</td>,
 <td class="table-body__cell u-text-right rating">97</td>,
 <td class="table-body__cell u-text-right rating">90</td>,
 <td class="table-body__cell u-text-right rating">82</td>,
 <td class="table-body__cell u-text-right rating">79</td>,
 <td class="table-body__cell u-text-right rating">62</td>,
 <td class="table-body__cell u-text-right rating">50</td>,
 <td class="table-body__cell u-text-right rating">45</td>,
 <td class="table-body__cell u-text-right rating">39</td>,
 <td class="table-body__cell u-text-right rating">34</td>,
 <td class="table-body__cell u-text-right rating">30</td>,
 <td class="table-body__cell u-text-right rating">24</td>,
 <td class="table-body__cell u-text-right rating">21</td>,
 <td class="table-body__cell u-text-right rating">16</td>,
 <td class="table-body__cell u-text-right rating">12</td>,
 <td class="table-body__cell u-text-right rating">0</td>]

In [579]:
ratings_no=['121']
cnt=1
for i in ratings:
    if cnt<10:
        ratings_no.append(i.text)
    cnt +=1

In [580]:
ratings_no

['121', '118', '115', '115', '107', '97', '90', '82', '79', '62']

In [581]:
print(len(team_name),len(no_of_matches),len(points),len(ratings_no))

10 10 11 10

In [582]:
points.remove('99')

In [583]:
print(len(team_name),len(no_of_matches),len(points),len(ratings_no))

10 10 10 10

In [584]:
import pandas as pd
Top_10_ODI_Teams=pd.DataFrame({})
Top_10_ODI_Teams['Team']=team_name
Top_10_ODI_Teams['Matches']=no_of_matches
Top_10_ODI_Teams['Points']=points
Top_10_ODI_Teams['Rating']=ratings_no

In [585]:
Top_10_ODI_Teams

           Team Matches Points Rating
0   New Zealand      17   2054    121
1     Australia      29  2,945    118
2         India      27  3,344    115
3       England      20  3,100    115
4  South Africa      24  2,137    107
5      Pakistan      24  2,323     97
6    Bangladesh      27  2,157     90
7   West Indies      21  2,222     82
8     Sri Lanka      17  1,652     79
9   Afghanistan       2  1,054     62

#### 5.2  Top 10 ODI Batsmen in men along with the records of their team and rating.

In [586]:
page5_2=requests.get('https://www.icc-cricket.com/rankings/mens/player-rankings/odi/batting')
page5_2

In [587]:
#page5_2.content

In [588]:
soup5_2=BeautifulSoup(page5_2.content)
#soup5_2

In [589]:
#print(soup5_2.prettify())

In [590]:
name=soup5_2.find('div',class_='rankings-block__banner--name-large')
name

In [591]:
name=soup5_2.find_all('td',class_='table-body__cell rankings-table__name name')
name

[<td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/164">Virat Kohli</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/107">Rohit Sharma</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/226">Ross Taylor</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/167">Aaron Finch</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/506">Jonny Bairstow</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/3801">Fakhar Zaman</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/24">Francois du Plessis</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/170">David Warner</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/2751">Shai Hope</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/834">Quinton de Kock</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/440">Kane Williamson</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1568">Imam-ul-Haq</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/887">Joe Root</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/271">Steve Smith</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/431">Martin Guptill</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/41">Shikhar Dhawan</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/491">Mushfiqur Rahim</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1906">Jason Roy</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/282">Glenn Maxwell</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/526">Paul Stirling</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1277">Rassie van der Dussen</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/287">Tamim Iqbal</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/948">Usman Khawaja</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1154">Ben Stokes</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/201">Shakib Al Hasan</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/197">Eoin Morgan</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1125">Lokesh Rahul</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/3882">Alex Carey</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/187">David Miller</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1705">Shimron Hetmyer</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/509">Jos Buttler</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1140">Tom Latham</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1703">Nicholas Pooran</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/855">Haris Sohail</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1141">Kyle Coetzer</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/2890">Henry Nicholls</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/3893">Aqib Ilyas</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/217">Angelo Mathews</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/492">Mahmudullah</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/530">Brendan Taylor</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/2740">Hardik Pandya</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1102">Sean Williams</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/297">Kedar Jadhav</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/872">Evin Lewis</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1250">Rahmat Shah</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1596">Litton Das</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1670">Kusal Mendis</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1863">Danushka Gunathilaka</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/441">Mohammad Hafeez</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1919">Soumya Sarkar</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1190">Andrew Balbirnie</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1129">Sikandar Raza</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/2760">Imad Wasim</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1738">Kusal Perera</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/964">Marcus Stoinis</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1156">Calum MacLeod</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/">Mohammad Shahzad</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/846">Sarfaraz Ahmed</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/820">Colin de Grandhomme</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/620">Najibullah Zadran</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/4029">Marnus Labuschagne</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/236">Chris Gayle</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/3084">Avishka Fernando</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/2884">Hashmatullah Shaidi</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/971">Jimmy Neesham</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/191">Shaun Marsh</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/522">Kevin O'Brien</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/618">Mohammad Nabi</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/221">Mitchell Marsh</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/932">Peter Handscomb</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1563">Shreyas Iyer</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/611">Asghar Afghan</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1143">Richard Berrington</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/515">William Porterfield</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/3216">Muhammad Usman</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/773">Colin Munro</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/533">Craig Ervine</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1903">Mitchell Santner</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/3869">Heinrich Klaasen</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/502">Lahiru Thirimanne</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1667">Aiden Markram</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1662">Andile Phehlukwayo</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/215">Thisara Perera</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1075">Jason Holder</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1734">Sabbir Rahman</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1733">Mithun Ali</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/833">Temba Bavuma</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1403">Assad Vala</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/9">Ravindra Jadeja</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1295">Dhananjaya de Silva</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/230">Dinesh Chandimal</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/2972">Rishabh Pant</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/2885">Rashid Khan</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/3333">Rovman Powell</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1188">Matthew Cross</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1404">Tony Ura</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/613">Gulbadin Naib</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/967">Chris Woakes</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/2756">Sam Billings</a>
 </td>]

In [592]:
batsman_name=['Babar Azam']             
cnt=1
for i in name:
    if cnt<10:
        batsman_name.append(i.text.replace('\n',''))
        cnt+=1
batsman_name

['Babar Azam',
 'Virat Kohli',
 'Rohit Sharma',
 'Ross Taylor',
 'Aaron Finch',
 'Jonny Bairstow',
 'Fakhar Zaman',
 'Francois du Plessis',
 'David Warner',
 'Shai Hope']

In [593]:
team=soup5_2.find('div',class_='rankings-block__banner--nationality')
team.text

'\n\nPAK\n                    '

In [594]:
Team=soup5_2.find_all('span',class_='table-body__logo-text')
Team

[<span class="table-body__logo-text">IND</span>,
 <span class="table-body__logo-text">IND</span>,
 <span class="table-body__logo-text">NZ</span>,
 <span class="table-body__logo-text">AUS</span>,
 <span class="table-body__logo-text">ENG</span>,
 <span class="table-body__logo-text">PAK</span>,
 <span class="table-body__logo-text">SA</span>,
 <span class="table-body__logo-text">AUS</span>,
 <span class="table-body__logo-text">WI</span>,
 <span class="table-body__logo-text">SA</span>,
 <span class="table-body__logo-text">NZ</span>,
 <span class="table-body__logo-text">PAK</span>,
 <span class="table-body__logo-text">ENG</span>,
 <span class="table-body__logo-text">AUS</span>,
 <span class="table-body__logo-text">NZ</span>,
 <span class="table-body__logo-text">IND</span>,
 <span class="table-body__logo-text">BAN</span>,
 <span class="table-body__logo-text">ENG</span>,
 <span class="table-body__logo-text">AUS</span>,
 <span class="table-body__logo-text">IRE</span>,
 <span class="table-body__logo-text">SA</span>,
 <span class="table-body__logo-text">BAN</span>,
 <span class="table-body__logo-text">AUS</span>,
 <span class="table-body__logo-text">ENG</span>,
 <span class="table-body__logo-text">BAN</span>,
 <span class="table-body__logo-text">ENG</span>,
 <span class="table-body__logo-text">IND</span>,
 <span class="table-body__logo-text">AUS</span>,
 <span class="table-body__logo-text">SA</span>,
 <span class="table-body__logo-text">WI</span>,
 <span class="table-body__logo-text">ENG</span>,
 <span class="table-body__logo-text">NZ</span>,
 <span class="table-body__logo-text">WI</span>,
 <span class="table-body__logo-text">PAK</span>,
 <span class="table-body__logo-text">SCO</span>,
 <span class="table-body__logo-text">NZ</span>,
 <span class="table-body__logo-text">OMA</span>,
 <span class="table-body__logo-text">SL</span>,
 <span class="table-body__logo-text">BAN</span>,
 <span class="table-body__logo-text">ZIM</span>,
 <span class="table-body__logo-text">IND</span>,
 <span class="table-body__logo-text">ZIM</span>,
 <span class="table-body__logo-text">IND</span>,
 <span class="table-body__logo-text">WI</span>,
 <span class="table-body__logo-text">AFG</span>,
 <span class="table-body__logo-text">BAN</span>,
 <span class="table-body__logo-text">SL</span>,
 <span class="table-body__logo-text">SL</span>,
 <span class="table-body__logo-text">PAK</span>,
 <span class="table-body__logo-text">BAN</span>,
 <span class="table-body__logo-text">IRE</span>,
 <span class="table-body__logo-text">ZIM</span>,
 <span class="table-body__logo-text">PAK</span>,
 <span class="table-body__logo-text">SL</span>,
 <span class="table-body__logo-text">AUS</span>,
 <span class="table-body__logo-text">SCO</span>,
 <span class="table-body__logo-text">AFG</span>,
 <span class="table-body__logo-text">PAK</span>,
 <span class="table-body__logo-text">NZ</span>,
 <span class="table-body__logo-text">AFG</span>,
 <span class="table-body__logo-text">AUS</span>,
 <span class="table-body__logo-text">WI</span>,
 <span class="table-body__logo-text">SL</span>,
 <span class="table-body__logo-text">AFG</span>,
 <span class="table-body__logo-text">NZ</span>,
 <span class="table-body__logo-text">AUS</span>,
 <span class="table-body__logo-text">IRE</span>,
 <span class="table-body__logo-text">AFG</span>,
 <span class="table-body__logo-text">AUS</span>,
 <span class="table-body__logo-text">AUS</span>,
 <span class="table-body__logo-text">IND</span>,
 <span class="table-body__logo-text">AFG</span>,
 <span class="table-body__logo-text">SCO</span>,
 <span class="table-body__logo-text">IRE</span>,
 <span class="table-body__logo-text">UAE</span>,
 <span class="table-body__logo-text">NZ</span>,
 <span class="table-body__logo-text">ZIM</span>,
 <span class="table-body__logo-text">NZ</span>,
 <span class="table-body__logo-text">SA</span>,
 <span class="table-body__logo-text">SL</span>,
 <span class="table-body__logo-text">SA</span>,
 <span class="table-body__logo-text">SA</span>,
 <span class="table-body__logo-text">SL</span>,
 <span class="table-body__logo-text">WI</span>,
 <span class="table-body__logo-text">BAN</span>,
 <span class="table-body__logo-text">BAN</span>,
 <span class="table-body__logo-text">SA</span>,
 <span class="table-body__logo-text">PNG</span>,
 <span class="table-body__logo-text">IND</span>,
 <span class="table-body__logo-text">SL</span>,
 <span class="table-body__logo-text">SL</span>,
 <span class="table-body__logo-text">IND</span>,
 <span class="table-body__logo-text">AFG</span>,
 <span class="table-body__logo-text">WI</span>,
 <span class="table-body__logo-text">SCO</span>,
 <span class="table-body__logo-text">PNG</span>,
 <span class="table-body__logo-text">AFG</span>,
 <span class="table-body__logo-text">ENG</span>,
 <span class="table-body__logo-text">ENG</span>]

In [595]:
team_name=['PAK']            
cnt=1
for i in Team:
    if cnt<10:
        team_name.append(i.text.replace('\n',''))
        cnt+=1
team_name

['PAK', 'IND', 'IND', 'NZ', 'AUS', 'ENG', 'PAK', 'SA', 'AUS', 'WI']

In [596]:
rating =soup5_2.find('div',class_='rankings-block__banner--rating')
rating.text

'865'

In [597]:
Rating=soup5_2.find_all('td',class_='table-body__cell rating')
Rating

[<td class="table-body__cell rating">857</td>,
 <td class="table-body__cell rating">825</td>,
 <td class="table-body__cell rating">801</td>,
 <td class="table-body__cell rating">791</td>,
 <td class="table-body__cell rating">785</td>,
 <td class="table-body__cell rating">778</td>,
 <td class="table-body__cell rating">778</td>,
 <td class="table-body__cell rating">773</td>,
 <td class="table-body__cell rating">773</td>,
 <td class="table-body__cell rating">756</td>,
 <td class="table-body__cell rating">754</td>,
 <td class="table-body__cell rating">751</td>,
 <td class="table-body__cell rating">723</td>,
 <td class="table-body__cell rating">707</td>,
 <td class="table-body__cell rating">707</td>,
 <td class="table-body__cell rating">706</td>,
 <td class="table-body__cell rating">698</td>,
 <td class="table-body__cell rating">689</td>,
 <td class="table-body__cell rating">684</td>,
 <td class="table-body__cell rating">684</td>,
 <td class="table-body__cell rating">680</td>,
 <td class="table-body__cell rating">678</td>,
 <td class="table-body__cell rating">675</td>,
 <td class="table-body__cell rating">668</td>,
 <td class="table-body__cell rating">659</td>,
 <td class="table-body__cell rating">655</td>,
 <td class="table-body__cell rating">646</td>,
 <td class="table-body__cell rating">644</td>,
 <td class="table-body__cell rating">640</td>,
 <td class="table-body__cell rating">633</td>,
 <td class="table-body__cell rating">627</td>,
 <td class="table-body__cell rating">624</td>,
 <td class="table-body__cell rating">614</td>,
 <td class="table-body__cell rating">603</td>,
 <td class="table-body__cell rating">588</td>,
 <td class="table-body__cell rating">581</td>,
 <td class="table-body__cell rating">578</td>,
 <td class="table-body__cell rating">575</td>,
 <td class="table-body__cell rating">571</td>,
 <td class="table-body__cell rating">571</td>,
 <td class="table-body__cell rating">561</td>,
 <td class="table-body__cell rating">561</td>,
 <td class="table-body__cell rating">560</td>,
 <td class="table-body__cell rating">559</td>,
 <td class="table-body__cell rating">559</td>,
 <td class="table-body__cell rating">553</td>,
 <td class="table-body__cell rating">549</td>,
 <td class="table-body__cell rating">546</td>,
 <td class="table-body__cell rating">546</td>,
 <td class="table-body__cell rating">537</td>,
 <td class="table-body__cell rating">537</td>,
 <td class="table-body__cell rating">536</td>,
 <td class="table-body__cell rating">533</td>,
 <td class="table-body__cell rating">531</td>,
 <td class="table-body__cell rating">525</td>,
 <td class="table-body__cell rating">522</td>,
 <td class="table-body__cell rating">519</td>,
 <td class="table-body__cell rating">512</td>,
 <td class="table-body__cell rating">507</td>,
 <td class="table-body__cell rating">506</td>,
 <td class="table-body__cell rating">506</td>,
 <td class="table-body__cell rating">504</td>,
 <td class="table-body__cell rating">502</td>,
 <td class="table-body__cell rating">498</td>,
 <td class="table-body__cell rating">495</td>,
 <td class="table-body__cell rating">495</td>,
 <td class="table-body__cell rating">495</td>,
 <td class="table-body__cell rating">494</td>,
 <td class="table-body__cell rating">486</td>,
 <td class="table-body__cell rating">483</td>,
 <td class="table-body__cell rating">479</td>,
 <td class="table-body__cell rating">479</td>,
 <td class="table-body__cell rating">478</td>,
 <td class="table-body__cell rating">475</td>,
 <td class="table-body__cell rating">471</td>,
 <td class="table-body__cell rating">468</td>,
 <td class="table-body__cell rating">464</td>,
 <td class="table-body__cell rating">460</td>,
 <td class="table-body__cell rating">457</td>,
 <td class="table-body__cell rating">456</td>,
 <td class="table-body__cell rating">454</td>,
 <td class="table-body__cell rating">450</td>,
 <td class="table-body__cell rating">446</td>,
 <td class="table-body__cell rating">445</td>,
 <td class="table-body__cell rating">444</td>,
 <td class="table-body__cell rating">444</td>,
 <td class="table-body__cell rating">444</td>,
 <td class="table-body__cell rating">443</td>,
 <td class="table-body__cell rating">440</td>,
 <td class="table-body__cell rating">436</td>,
 <td class="table-body__cell rating">436</td>,
 <td class="table-body__cell rating">432</td>,
 <td class="table-body__cell rating">432</td>,
 <td class="table-body__cell rating">426</td>,
 <td class="table-body__cell rating">416</td>,
 <td class="table-body__cell rating">415</td>,
 <td class="table-body__cell rating">415</td>,
 <td class="table-body__cell rating">411</td>,
 <td class="table-body__cell rating">409</td>]

In [598]:
Ratings=['865']            
cnt=1
for i in Rating:
    if cnt<10:
        Ratings.append(i.text.replace('\n',''))
        cnt+=1
Ratings

['865', '857', '825', '801', '791', '785', '778', '778', '773', '773']

In [599]:
print(len(batsman_name),len(team_name),len(Ratings))

10 10 10

In [600]:
import pandas as pd
Top_10_ODI_Batsman=pd.DataFrame({})
Top_10_ODI_Batsman['Name']=batsman_name
Top_10_ODI_Batsman['Team']=team_name
Top_10_ODI_Batsman['Rating']=Ratings

In [601]:
Top_10_ODI_Batsman

                  Name Team Rating
0           Babar Azam  PAK    865
1          Virat Kohli  IND    857
2         Rohit Sharma  IND    825
3          Ross Taylor   NZ    801
4          Aaron Finch  AUS    791
5       Jonny Bairstow  ENG    785
6         Fakhar Zaman  PAK    778
7  Francois du Plessis   SA    778
8         David Warner  AUS    773
9            Shai Hope   WI    773

##### 5.3  Top 10 ODI bowlers along with the records of their team and rating.

In [602]:
page5_3=requests.get('https://www.icc-cricket.com/rankings/mens/player-rankings/odi/bowling')
page5_3

In [603]:
#page5_3.content

In [604]:
soup5_3=BeautifulSoup(page5_3.content)

In [605]:
#print(soup5_3.prettify())

In [606]:
name=soup5_3.find('div',class_='rankings-block__banner--name-large')
name.text

'Trent Boult'

In [607]:
name=soup5_3.find_all('td',class_='table-body__cell rankings-table__name name')
name

[<td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/4572">Mujeeb Ur Rahman</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1505">Matt Henry</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1124">Jasprit Bumrah</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1597">Mehedi Hasan</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1664">Kagiso Rabada</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/967">Chris Woakes</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/857">Josh Hazlewood</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/488">Pat Cummins</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/2896">Mohammad Amir</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/4530">Shaheen Afridi</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/116">Bhuvneshwar Kumar</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/3502">Jofra Archer</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/2885">Rashid Khan</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/958">Adam Zampa</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/201">Shakib Al Hasan</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/3729">Lachlan Ferguson</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1594">Mustafizur Rahman</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/490">Mitchell Starc</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/3746">Lungi Ngidi</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/588">Akila Dananjaya</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/618">Mohammad Nabi</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/2749">Mark Wood</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/111">Yuzvendra Chahal</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1903">Mitchell Santner</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/94">Mohammad Shami</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/3098">Alzarri Joseph</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/261">Kuldeep Yadav</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/9">Ravindra Jadeja</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1309">Sheldon Cottrell</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1842">Liam Plunkett</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1365">Andy McBrine</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1258">Ahmed Raza</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/796">Adil Rashid</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/3046">Shadab Khan</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/837">Dwaine Pretorius</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/820">Colin de Grandhomme</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1662">Andile Phehlukwayo</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/307">Tim Southee</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1304">Ish Sodhi</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/2760">Imad Wasim</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1097">Tendai Chatara</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1461">Usman Khan</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/3781">Jhye Richardson</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1650">Mark Watt</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1735">Moeen Ali</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/524">Boyd Rankin</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/391">Mashrafe Mortaza</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/2915">Mohammad Mohammad Saifuddin</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1417">Safyaan Sharif</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/505">Nuwan Pradeep</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1215">Rohan Mustafa</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/2758">David Willey</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/3325">Hasan Ali</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/3309">Tabraiz Shamsi</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/840">Nathan Coulter-Nile</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/4208">Faheem Ashraf</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1075">Jason Holder</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/993">Suranga Lakmal</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/836">Chris Morris</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/797">Nathan Lyon</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/971">Jimmy Neesham</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/534">Kyle Jarvis</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/988">Wahab Riaz</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/981">Junaid Khan</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/4324">Simi Simi Singh</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1129">Sikandar Raza</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1154">Ben Stokes</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/3082">Wanindu De Silva</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1146">Josh Davey</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/410">Kemar Roach</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/817">Dushmantha Chameera</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/612">Dawlat Zadran</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1102">Sean Williams</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/5433">Anrich Nortje</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/798">Kane Richardson</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1455">Aftab Alam</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1911">Yasir Shah</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/215">Thisara Perera</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1135">Rubel Hossain</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1745">Shardul Thakur</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/937">Jason Behrendorff</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/2740">Hardik Pandya</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/517">George Dockrell</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/613">Gulbadin Naib</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/3313">Barry McCarthy</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/221">Mitchell Marsh</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/3646">Tom Curran</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1898">Ashley Nurse</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/614">Hamid Hassan</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/4590">Blessing Muzarabani</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1295">Dhananjaya de Silva</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1904">Taijul Islam</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/964">Marcus Stoinis</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/935">Ashton Agar</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/3195">Mohammad Nawaz</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1852">Donald Tiripano</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/3171">Bradley Wheal</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1185">Alasdair Evans</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/mens/player-rankings/1403">Assad Vala</a>
 </td>]

In [608]:
bowler_name=['Trent Boult']             
cnt=1
for i in name:
    if cnt<10:
        bowler_name.append(i.text.replace('\n',''))
        cnt+=1
bowler_name

['Trent Boult',
 'Mujeeb Ur Rahman',
 'Matt Henry',
 'Jasprit Bumrah',
 'Mehedi Hasan',
 'Kagiso Rabada',
 'Chris Woakes',
 'Josh Hazlewood',
 'Pat Cummins',
 'Mohammad Amir']

In [609]:
team=soup5_3.find('div',class_='rankings-block__banner--nationality')
team.text

'\n\nNZ\n                    '

In [610]:
Team=soup5_3.find_all('span',class_='table-body__logo-text')
Team

[<span class="table-body__logo-text">AFG</span>,
 <span class="table-body__logo-text">NZ</span>,
 <span class="table-body__logo-text">IND</span>,
 <span class="table-body__logo-text">BAN</span>,
 <span class="table-body__logo-text">SA</span>,
 <span class="table-body__logo-text">ENG</span>,
 <span class="table-body__logo-text">AUS</span>,
 <span class="table-body__logo-text">AUS</span>,
 <span class="table-body__logo-text">PAK</span>,
 <span class="table-body__logo-text">PAK</span>,
 <span class="table-body__logo-text">IND</span>,
 <span class="table-body__logo-text">ENG</span>,
 <span class="table-body__logo-text">AFG</span>,
 <span class="table-body__logo-text">AUS</span>,
 <span class="table-body__logo-text">BAN</span>,
 <span class="table-body__logo-text">NZ</span>,
 <span class="table-body__logo-text">BAN</span>,
 <span class="table-body__logo-text">AUS</span>,
 <span class="table-body__logo-text">SA</span>,
 <span class="table-body__logo-text">SL</span>,
 <span class="table-body__logo-text">AFG</span>,
 <span class="table-body__logo-text">ENG</span>,
 <span class="table-body__logo-text">IND</span>,
 <span class="table-body__logo-text">NZ</span>,
 <span class="table-body__logo-text">IND</span>,
 <span class="table-body__logo-text">WI</span>,
 <span class="table-body__logo-text">IND</span>,
 <span class="table-body__logo-text">IND</span>,
 <span class="table-body__logo-text">WI</span>,
 <span class="table-body__logo-text">ENG</span>,
 <span class="table-body__logo-text">IRE</span>,
 <span class="table-body__logo-text">UAE</span>,
 <span class="table-body__logo-text">ENG</span>,
 <span class="table-body__logo-text">PAK</span>,
 <span class="table-body__logo-text">SA</span>,
 <span class="table-body__logo-text">NZ</span>,
 <span class="table-body__logo-text">SA</span>,
 <span class="table-body__logo-text">NZ</span>,
 <span class="table-body__logo-text"></span>,
 <span class="table-body__logo-text">PAK</span>,
 <span class="table-body__logo-text">ZIM</span>,
 <span class="table-body__logo-text">PAK</span>,
 <span class="table-body__logo-text">AUS</span>,
 <span class="table-body__logo-text">SCO</span>,
 <span class="table-body__logo-text">ENG</span>,
 <span class="table-body__logo-text">IRE</span>,
 <span class="table-body__logo-text">BAN</span>,
 <span class="table-body__logo-text">BAN</span>,
 <span class="table-body__logo-text">SCO</span>,
 <span class="table-body__logo-text">SL</span>,
 <span class="table-body__logo-text">UAE</span>,
 <span class="table-body__logo-text">ENG</span>,
 <span class="table-body__logo-text">PAK</span>,
 <span class="table-body__logo-text">SA</span>,
 <span class="table-body__logo-text">AUS</span>,
 <span class="table-body__logo-text">PAK</span>,
 <span class="table-body__logo-text">WI</span>,
 <span class="table-body__logo-text">SL</span>,
 <span class="table-body__logo-text">SA</span>,
 <span class="table-body__logo-text">AUS</span>,
 <span class="table-body__logo-text">NZ</span>,
 <span class="table-body__logo-text">ZIM</span>,
 <span class="table-body__logo-text">PAK</span>,
 <span class="table-body__logo-text">PAK</span>,
 <span class="table-body__logo-text">IRE</span>,
 <span class="table-body__logo-text">ZIM</span>,
 <span class="table-body__logo-text">ENG</span>,
 <span class="table-body__logo-text">SL</span>,
 <span class="table-body__logo-text">SCO</span>,
 <span class="table-body__logo-text">WI</span>,
 <span class="table-body__logo-text">SL</span>,
 <span class="table-body__logo-text">AFG</span>,
 <span class="table-body__logo-text">ZIM</span>,
 <span class="table-body__logo-text">SA</span>,
 <span class="table-body__logo-text">AUS</span>,
 <span class="table-body__logo-text">AFG</span>,
 <span class="table-body__logo-text">PAK</span>,
 <span class="table-body__logo-text">SL</span>,
 <span class="table-body__logo-text">BAN</span>,
 <span class="table-body__logo-text">IND</span>,
 <span class="table-body__logo-text">AUS</span>,
 <span class="table-body__logo-text">IND</span>,
 <span class="table-body__logo-text">IRE</span>,
 <span class="table-body__logo-text">AFG</span>,
 <span class="table-body__logo-text">IRE</span>,
 <span class="table-body__logo-text">AUS</span>,
 <span class="table-body__logo-text">ENG</span>,
 <span class="table-body__logo-text">WI</span>,
 <span class="table-body__logo-text">AFG</span>,
 <span class="table-body__logo-text">ZIM</span>,
 <span class="table-body__logo-text">SL</span>,
 <span class="table-body__logo-text">BAN</span>,
 <span class="table-body__logo-text">AUS</span>,
 <span class="table-body__logo-text">AUS</span>,
 <span class="table-body__logo-text">PAK</span>,
 <span class="table-body__logo-text">ZIM</span>,
 <span class="table-body__logo-text">SCO</span>,
 <span class="table-body__logo-text">SCO</span>,
 <span class="table-body__logo-text">PNG</span>]

In [611]:
team_name=['NZ']            
cnt=1
for i in Team:
    if cnt<10:
        team_name.append(i.text.replace('\n',''))
        cnt+=1
team_name

['NZ', 'AFG', 'NZ', 'IND', 'BAN', 'SA', 'ENG', 'AUS', 'AUS', 'PAK']

In [612]:
rating =soup5_3.find('div',class_='rankings-block__banner--rating')
rating.text

'737'

In [613]:
Rating=soup5_3.find_all('td',class_='table-body__cell rating')
Rating

[<td class="table-body__cell rating">708</td>,
 <td class="table-body__cell rating">691</td>,
 <td class="table-body__cell rating">690</td>,
 <td class="table-body__cell rating">668</td>,
 <td class="table-body__cell rating">666</td>,
 <td class="table-body__cell rating">665</td>,
 <td class="table-body__cell rating">660</td>,
 <td class="table-body__cell rating">646</td>,
 <td class="table-body__cell rating">638</td>,
 <td class="table-body__cell rating">634</td>,
 <td class="table-body__cell rating">632</td>,
 <td class="table-body__cell rating">627</td>,
 <td class="table-body__cell rating">626</td>,
 <td class="table-body__cell rating">623</td>,
 <td class="table-body__cell rating">620</td>,
 <td class="table-body__cell rating">619</td>,
 <td class="table-body__cell rating">619</td>,
 <td class="table-body__cell rating">611</td>,
 <td class="table-body__cell rating">606</td>,
 <td class="table-body__cell rating">603</td>,
 <td class="table-body__cell rating">596</td>,
 <td class="table-body__cell rating">594</td>,
 <td class="table-body__cell rating">584</td>,
 <td class="table-body__cell rating">583</td>,
 <td class="table-body__cell rating">574</td>,
 <td class="table-body__cell rating">569</td>,
 <td class="table-body__cell rating">564</td>,
 <td class="table-body__cell rating">559</td>,
 <td class="table-body__cell rating">558</td>,
 <td class="table-body__cell rating">546</td>,
 <td class="table-body__cell rating">536</td>,
 <td class="table-body__cell rating">531</td>,
 <td class="table-body__cell rating">529</td>,
 <td class="table-body__cell rating">523</td>,
 <td class="table-body__cell rating">515</td>,
 <td class="table-body__cell rating">508</td>,
 <td class="table-body__cell rating">506</td>,
 <td class="table-body__cell rating">500</td>,
 <td class="table-body__cell rating">496</td>,
 <td class="table-body__cell rating">495</td>,
 <td class="table-body__cell rating">490</td>,
 <td class="table-body__cell rating">489</td>,
 <td class="table-body__cell rating">488</td>,
 <td class="table-body__cell rating">486</td>,
 <td class="table-body__cell rating">486</td>,
 <td class="table-body__cell rating">485</td>,
 <td class="table-body__cell rating">483</td>,
 <td class="table-body__cell rating">482</td>,
 <td class="table-body__cell rating">481</td>,
 <td class="table-body__cell rating">481</td>,
 <td class="table-body__cell rating">477</td>,
 <td class="table-body__cell rating">475</td>,
 <td class="table-body__cell rating">473</td>,
 <td class="table-body__cell rating">470</td>,
 <td class="table-body__cell rating">470</td>,
 <td class="table-body__cell rating">469</td>,
 <td class="table-body__cell rating">465</td>,
 <td class="table-body__cell rating">463</td>,
 <td class="table-body__cell rating">462</td>,
 <td class="table-body__cell rating">462</td>,
 <td class="table-body__cell rating">458</td>,
 <td class="table-body__cell rating">458</td>,
 <td class="table-body__cell rating">454</td>,
 <td class="table-body__cell rating">449</td>,
 <td class="table-body__cell rating">448</td>,
 <td class="table-body__cell rating">443</td>,
 <td class="table-body__cell rating">442</td>,
 <td class="table-body__cell rating">439</td>,
 <td class="table-body__cell rating">431</td>,
 <td class="table-body__cell rating">431</td>,
 <td class="table-body__cell rating">429</td>,
 <td class="table-body__cell rating">427</td>,
 <td class="table-body__cell rating">426</td>,
 <td class="table-body__cell rating">425</td>,
 <td class="table-body__cell rating">422</td>,
 <td class="table-body__cell rating">422</td>,
 <td class="table-body__cell rating">418</td>,
 <td class="table-body__cell rating">412</td>,
 <td class="table-body__cell rating">412</td>,
 <td class="table-body__cell rating">411</td>,
 <td class="table-body__cell rating">410</td>,
 <td class="table-body__cell rating">403</td>,
 <td class="table-body__cell rating">401</td>,
 <td class="table-body__cell rating">399</td>,
 <td class="table-body__cell rating">397</td>,
 <td class="table-body__cell rating">395</td>,
 <td class="table-body__cell rating">391</td>,
 <td class="table-body__cell rating">388</td>,
 <td class="table-body__cell rating">387</td>,
 <td class="table-body__cell rating">387</td>,
 <td class="table-body__cell rating">386</td>,
 <td class="table-body__cell rating">385</td>,
 <td class="table-body__cell rating">383</td>,
 <td class="table-body__cell rating">377</td>,
 <td class="table-body__cell rating">376</td>,
 <td class="table-body__cell rating">373</td>,
 <td class="table-body__cell rating">372</td>,
 <td class="table-body__cell rating">366</td>,
 <td class="table-body__cell rating">363</td>]

In [614]:
Ratings=['865']            
cnt=1
for i in Rating:
    if cnt<10:
        Ratings.append(i.text.replace('\n',''))
        cnt+=1
Ratings

['865', '708', '691', '690', '668', '666', '665', '660', '646', '638']

In [615]:
print(len(bowler_name),len(team_name),len(Ratings))

10 10 10

In [616]:
import pandas as pd
Top_10_ODI_Bowlers=pd.DataFrame({})
Top_10_ODI_Bowlers['Name']=bowler_name
Top_10_ODI_Bowlers['Team']=team_name
Top_10_ODI_Bowlers['Rating']=Ratings

In [617]:
Top_10_ODI_Bowlers

               Name Team Rating
0       Trent Boult   NZ    865
1  Mujeeb Ur Rahman  AFG    708
2        Matt Henry   NZ    691
3    Jasprit Bumrah  IND    690
4      Mehedi Hasan  BAN    668
5     Kagiso Rabada   SA    666
6      Chris Woakes  ENG    665
7    Josh Hazlewood  AUS    660
8       Pat Cummins  AUS    646
9     Mohammad Amir  PAK    638

# Assignment Question No 6

6. Write a python program to scrape cricket rankings from ‘www.icc-cricket.com’.

You have to scrape:
    
    i) Top 10 ODI teams in women’s cricket along with the records for matches, points and rating. 
    
    ii) Top 10 women’s ODI players along with the records of their team and rating.  
    
    iii) Top 10 women’s ODI all-rounder along with the records of their team and rating

In [618]:
page6_1=requests.get('https://www.icc-cricket.com/rankings/womens/team-rankings/odi')
page6_1

In [619]:
#page6_1.content

In [620]:
soup6_1=BeautifulSoup(page6_1.content)

In [621]:
#print(soup6_1.prettify())

In [622]:
name=soup6_1.find_all('span',class_='u-hide-phablet')
name

[<span class="u-hide-phablet">Australia</span>,
 <span class="u-hide-phablet">South Africa</span>,
 <span class="u-hide-phablet">England</span>,
 <span class="u-hide-phablet">India</span>,
 <span class="u-hide-phablet">New Zealand</span>,
 <span class="u-hide-phablet">West Indies</span>,
 <span class="u-hide-phablet">Pakistan</span>,
 <span class="u-hide-phablet">Bangladesh</span>,
 <span class="u-hide-phablet">Sri Lanka</span>,
 <span class="u-hide-phablet">Ireland</span>,
 <span class="icn icn-facebook-circle u-hide-phablet"></span>,
 <span class="icn icn-twitter-circle u-hide-phablet"></span>,
 <span class="icn icn-instagram-circle u-hide-phablet"></span>,
 <span class="icn icn-youtube-circle u-hide-phablet"></span>,
 <span class="icn icn-tiktok-circle u-hide-phablet"></span>]

In [623]:
team_name=[]             
cnt=0
for i in name:
    if cnt<10:
        team_name.append(i.text.replace('\n',''))
        cnt+=1
team_name

['Australia',
 'South Africa',
 'England',
 'India',
 'New Zealand',
 'West Indies',
 'Pakistan',
 'Bangladesh',
 'Sri Lanka',
 'Ireland']

In [624]:
match=soup6_1.find_all('td',class_='rankings-block__banner--matches')
match

In [625]:
matches=soup6_1.find_all('td',class_='table-body__cell u-center-text')
matches

[<td class="table-body__cell u-center-text">24</td>,
 <td class="table-body__cell u-center-text">2,828</td>,
 <td class="table-body__cell u-center-text">17</td>,
 <td class="table-body__cell u-center-text">1,993</td>,
 <td class="table-body__cell u-center-text">20</td>,
 <td class="table-body__cell u-center-text">2,226</td>,
 <td class="table-body__cell u-center-text">21</td>,
 <td class="table-body__cell u-center-text">1,947</td>,
 <td class="table-body__cell u-center-text">12</td>,
 <td class="table-body__cell u-center-text">1,025</td>,
 <td class="table-body__cell u-center-text">15</td>,
 <td class="table-body__cell u-center-text">1,101</td>,
 <td class="table-body__cell u-center-text">5</td>,
 <td class="table-body__cell u-center-text">306</td>,
 <td class="table-body__cell u-center-text">11</td>,
 <td class="table-body__cell u-center-text">519</td>,
 <td class="table-body__cell u-center-text">2</td>,
 <td class="table-body__cell u-center-text">25</td>]

###### as we can observe that  'table-body__cell u-center-text' is for both matches and point so we will work with alternate index

In [626]:
no_of_matches=['18']             
points =['2,955']
cnt=0
for i in range(0,18):       # as there are 18 
    if cnt<20:
        if i%2==0:
            no_of_matches.append(matches[i].text.replace('\n',''))
        else:
            points.append(matches[i].text.replace('\n',''))
    cnt+=1

In [627]:
no_of_matches

['18', '24', '17', '20', '21', '12', '15', '5', '11', '2']

In [628]:
points

['2,955',
 '2,828',
 '1,993',
 '2,226',
 '1,947',
 '1,025',
 '1,101',
 '306',
 '519',
 '25']

In [629]:

ratings=soup6_1.find('td',class_='rankings-block__banner--rating u-text-right')
ratings

<td class="rankings-block__banner--rating u-text-right">
                            164
                            <span class="circle-branding circle-branding--top"></span>
<span class="circle-branding circle-branding--bottom"></span>
</td>

In [630]:
print(ratings.text)

                            164

In [631]:
ratings=soup6_1.find_all('td','table-body__cell u-text-right rating')
ratings

[<td class="table-body__cell u-text-right rating">118</td>,
 <td class="table-body__cell u-text-right rating">117</td>,
 <td class="table-body__cell u-text-right rating">111</td>,
 <td class="table-body__cell u-text-right rating">93</td>,
 <td class="table-body__cell u-text-right rating">85</td>,
 <td class="table-body__cell u-text-right rating">73</td>,
 <td class="table-body__cell u-text-right rating">61</td>,
 <td class="table-body__cell u-text-right rating">47</td>,
 <td class="table-body__cell u-text-right rating">13</td>]

In [632]:
ratings_no=['164']
cnt=1
for i in ratings:
    if cnt<10:
        ratings_no.append(i.text)
    cnt +=1

In [633]:
ratings_no

['164', '118', '117', '111', '93', '85', '73', '61', '47', '13']

In [634]:
print(len(team_name),len(no_of_matches),len(points),len(ratings_no))

10 10 10 10

In [635]:
import pandas as pd
Top_10_Womens_ODI_Teams=pd.DataFrame({})
Top_10_Womens_ODI_Teams['Team']=team_name
Top_10_Womens_ODI_Teams['Matches']=no_of_matches
Top_10_Womens_ODI_Teams['Points']=points
Top_10_Womens_ODI_Teams['Rating']=ratings_no

In [636]:
Top_10_Womens_ODI_Teams

           Team Matches Points Rating
0     Australia      18  2,955    164
1  South Africa      24  2,828    118
2       England      17  1,993    117
3         India      20  2,226    111
4   New Zealand      21  1,947     93
5   West Indies      12  1,025     85
6      Pakistan      15  1,101     73
7    Bangladesh       5    306     61
8     Sri Lanka      11    519     47
9       Ireland       2     25     13

In [637]:
page6_2=requests.get('https://www.icc-cricket.com/rankings/womens/player-rankings/odi/batting')
page6_2

In [638]:
page6_2.content

b'<!DOCTYPE html>\n<html lang="en">\n<head>\n\n    <meta name="twitter:title" content="Live Cricket Scores & News International Cricket Council"/>\n<meta property="og:type" content="website"/>\n<meta property="twitter:card" content="summary_large_image"/>\n<meta name="description" content="Official ICC Cricket website - live matches, scores, news, highlights, commentary, rankings, videos and fixtures from the International Cricket Council."/>\n<meta property="twitter:site" content="@icc"/>\n<meta name="twitter:description" content="Official ICC Cricket website - live matches, scores, news, highlights, commentary, rankings, videos and fixtures from the International Cricket Council."/>\n<meta name="twitter:image" content="https://www.icc-cricket.com/resources/ver/i/elements/default-thumbnail.jpg"/>\n<meta property="og:title" content="Live Cricket Scores & News International Cricket Council"/>\n<meta property="og:image" content="https://www.icc-cricket.com/resources/ver/i/elements/default-thumbnail.jpg"/>\n<title>Live Cricket Scores & News International Cricket Council</title>\n<meta property="og:description" content="Official ICC Cricket website - live matches, scores, news, highlights, commentary, rankings, videos and fixtures from the International Cricket Council."/>\n\n\t<!-- Designed and built by Pulselive - www.pulselive.com -->\n    \n<script>\n\n    var dataLayer = [{\n        \'user_language\':\'English\',\n        \'web_domain\':\'www.icc-cricket.com\',\n        \'page_type\':\'/rankings/womens/player-rankings/odi/batting\'  \n    }];\n\n</script>\n\n<!-- Google Tag Manager -->\n<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({\'gtm.start\':\nnew Date().getTime(),event:\'gtm.js\'});var f=d.getElementsByTagName(s)[0],\nj=d.createElement(s),dl=l!=\'dataLayer\'?\'&l=\'+l:\'\';j.async=true;j.src=\n\'https://www.googletagmanager.com/gtm.js?id=\'+i+dl;f.parentNode.insertBefore(j,f);\n})(window,document,\'script\',\'dataLayer\',\'GTM-T7DPH24\');</script>\n<!-- End Google Tag Manager -->\n\n\n    <meta charset="UTF-8">\n    <meta name="viewport" content="width=device-width, initial-scale=1">\n    <meta name="apple-itunes-app" content="app-id=956440606"/>\n\n    <link rel="manifest" href="/resources/prod/v8.15.0/manifest.json">\n\n    <link rel="shortcut icon" href="/resources/prod/v8.15.0/i/elements/favicon.ico" />\n\n    <link rel="publisher" href="https://plus.google.com/+ICC">\n\n    \n\n\n\n    <title>International Cricket Council</title>\n\n    \n\n<!-- google platform library -->\n<script src="https://apis.google.com/js/api:client.js?onload=startApp" async defer></script>\n\n<script>\n\n    var startApp = function() {\n        gapi.load(\'auth2\', function(){\n            // Retrieve the singleton for the GoogleAuth library and set up the client.\n            auth2 = gapi.auth2.init({\n                client_id: \'844310787835-1rirg6e5plp2jou6v701br43iuo0lkcu.apps.googleusercontent.com\'\n                // Request scopes in addition to \'profile\' and \'email\'\n                //scope: \'additional_scope\'\n            });\n        });\n    };\n</script>\n\n\n    <link href="https://fonts.googleapis.com/css?family=Hind+Siliguri:300,400,500,600" rel="stylesheet">\n\n    <!-- Polyfill service provided by the FT - https://github.com/Financial-Times/polyfill-service -->\n\t<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=default,fetch"></script>\n\n    <link rel="stylesheet" href="/resources/prod/v8.15.0/styles/screen.css" />\n\n    <script>\n\t\twindow.RESOURCE_VERSION = \'prod/v8.15.0\';\n\t</script>\n\n</head>\n<body>\n\n    \n<!-- Google Tag Manager (noscript) -->\n<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-T7DPH24"\nheight="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>\n<!-- End Google Tag Manager (noscript) -->\n\n<div class="u-hide" data-widget="analytics-geolocation" data-script="icc_analytics-geolocation"></div>\n\n<!--\n    Start of Floodlight Tag: Please do not removeActivity name of this tag: ICC Website - VisitationURL of the webpage where the tag is expected to be placed: This tag must be placed between the <body> and </body> tags, as close as possible to the opening tag. Creation Date: 10/01/2019\n-->\n\n<iframe src="https://9282652.fls.doubleclick.net/activityi;src=9282652;type=iccre0;cat=iccwe0;u1=[user_language];u2=[user_country];u3=[page_type];u4=[web_domain];dc_lat=;dc_rdid=;tag_for_child_directed_treatment=;tfua=;npa=;ord=[SessionID]?" width="1" height="1" frameborder="0" style="display:none"></iframe>\n\n<!-- End of Floodlight Tag: Please do not remove -->\n\n    \n\n<script>\n    window.fbAsyncInit = function() {\n        FB.init({\n            appId            : 159513024983374,\n            autoLogAppEvents : true,\n            xfbml            : true,\n            version          : \'v3.0\'\n        });\n    };\n\n    (function(d, s, id){\n        var js, fjs = d.getElementsByTagName(s)[0];\n        if (d.getElementById(id)) {return;}\n        js = d.createElement(s); js.id = id;\n        js.src = "https://connect.facebook.net/en_US/sdk.js";\n        fjs.parentNode.insertBefore(js, fjs);\n    }(document, \'script\', \'facebook-jssdk\'));\n</script>\n\n\n    \n<div class="user-account-overlay js-user-account-overlay"></div>\n<section class="user-account js-user-account" data-script="sso_user-account" data-widget="user-account">\n\n    <div class="user-account__wrapper js-panel-account u-hide">\n\n        <div class="user-account__header">\n\n            <div class="user-account__close js-account-slider-close-btn" role="button">\n                <svg class="icon"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="/resources/prod/v8.15.0/i/svg-output/icons.svg#icn-close"></use></svg>\n            </div>\n\n            <div class="user-account__user-wrapper">\n                <div class="user-account__image">\n                    <img src="#" class="u-hide js-account-user-img" alt="User Image">\n                </div>\n                <div class="user-account__user-info">\n                    <p class="user-account__user-info__text js-account-user">Name Lastname</p>\n                    <p class="user-account__user-info__profile js-profile-completion-info u-hide">\n                        <svg class="icon"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="/resources/prod/v8.15.0/i/svg-output/icons.svg#icn-alert"></use></svg>\n                        Profile <span class="js-profile-completion-percentage"></span>% Complete\n                    </p>\n                </div>\n            </div>\n\n            <div class="user-account__tabs-nav js-tabs-wrapper"></div>\n        </div>\n\n        <div class="account-message js-account-message"></div>\n\n        <form id="user-account" name="user-account" autocomplete="off">\n\n            <div data-ui-tab="My Account" class="user-account__tab">\n                <div class="user-account__social-wrapper js-social-wrapper u-hide"></div>\n\n<fieldset>\n\n    <div class="form-group-multiple">\n        <div class="form-group">\n            <label class="form-group__label" for="given_name">First name *</label>\n            <input class="form-group__element" type="text" required name="given_name" id="given_name" pattern="^[A-Za-z-\\s]+$" maxlength="50"/>\n            <p class="js-error form-error"></p>\n        </div>\n\n        <div class="form-group">\n            <label class="form-group__label" for="family_name">Last name *</label>\n            <input class="form-group__element" type="text" required name="family_name" id="family_name" pattern="[A-Za-z-\\s]+$" maxlength="50"/>\n            <p class="js-error form-error"></p>\n        </div>\n    </div>\n\n    <div class="form-group-multiple form-group-multiple--with-button">\n        <div class="form-group is-disabled js-change-email-input">\n            <label class="form-group__label" for="email">Email address *</label>\n            <input class="form-group__element" type="email" name="email" id="email" autocomplete="off" maxlength="50" disabled/>\n            <p class="js-error form-error"></p>\n            <p class="js-email-exists form-error form-error--email">Email address not available.</p>\n        </div>\n        <div class="form-group form-group--button">\n            <button class="form-btn form-btn--outlined js-change-email" type="button" novalidate>Change Email</button>\n        </div>\n    </div>\n\n    <div class="form-group-multiple form-group-multiple--with-button js-account-password">\n        <div class="form-group is-disabled js-change-password-input">\n            <label class="form-group__label" for="password">Password *</label>\n            <input class="form-group__element" type="password" name="password" id="password" placeholder="******" autocomplete="off" disabled/>\n            <p class="js-error form-error"></p>\n        </div>\n        <div class="form-group form-group--button">\n            <button class="form-btn form-btn--outlined js-change-password" type="button" novalidate>Change Password</button>\n        </div>\n    </div>\n\n    <div class="form-block form-block">\n        <div class="form-block__label form-block__label--dob">Date of Birth</div>\n\n        <div class="form-group-multiple">\n            <div class="form-group">\n                <label class="form-group__label" for="day">Day *</label>\n                <input class="form-group__element" type="number" required name="day" placeholder="dd" id="day" min="0" />\n                <p class="js-error form-error"></p>\n\n            </div>\n            <div class="form-group">\n                <label class="form-group__label" for="month">Month *</label>\n                <input class="form-group__element" type="number" required name="month" placeholder="mm" id="month" min="0"/>\n                <p class="js-error form-error"></p>\n            </div>\n            <div class="form-group">\n                <label class="form-group__label" for="year">Year *</label>\n                <input class="form-group__element" type="number" required name="year" placeholder="yyyy" id="year" min="0"/>\n                <p class="js-error form-error"></p>\n            </div>\n        </div>\n        <p class="js-date-error form-error form-error--date">The date of birth is not valid</p>\n    </div>\n\n    <div class="form-block" data-widget="form-dropdown" data-dropdown-type="SSO_COUNTRY">\n        <div class="form-block__label">Country of residence</div>\n        <div class="form-dropdown js-dropdown-wrapper"></div>\n    </div>\n\n</fieldset>\n\n            </div>\n            <div data-ui-tab="My Preferences" class="user-account__tab">\n                <div class="js-account-prefs u-hide">\n    <fieldset>\n\n        <div class="form-block" data-widget="form-dropdown" data-dropdown-type="SSO_TEAM">\n            <div class="form-block__label">Your favourite team</div>\n            <div class="form-dropdown js-dropdown-wrapper"></div>\n        </div>\n\n        <div class="js-contact-prefs user-account__contact-prefs-wrapper">\n\n            <div class="user-account__alert">\n                <svg class="icon"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="/resources/prod/v8.15.0/i/svg-output/icons.svg#icn-alert"></use></svg>\n                <span>Sorry, but your contact preferences will take up to 24hrs to update</span>\n            </div>\n\n            <div class="user-account__contact-prefs">\n                <div class="form-block form-block--no-margin">\n                    <div class="form-group form-group--checkbox">\n                        <input class="form-group__element" type="checkbox" name="allow-contacting" id="allow-contacting"/>\n                        <label class="form-group__label" for="allow-contacting">I\'m happy for the ICC to contact me</label>\n                    </div>\n                    <p class="js-error form-error"></p>\n                </div>\n\n                <div class="form-block form-block--no-margin">\n                    <div class="form-group form-group--checkbox">\n                        <input class="form-group__element" type="checkbox" name="allow-partner-contacting" id="allow-partner-contacting"/>\n                        <label class="form-group__label" for="allow-partner-contacting">I\'m happy for the ICC\'s partners to contact me</label>\n                    </div>\n                    <p class="js-error form-error"></p>\n                </div>\n            </div>\n\n        </div>\n\n    </fieldset>\n</div>\n\n<div class="overlay__loader__small js-loader-prefs">\n    Hold on! Loading your preferences <div class="loader loader--small"></div>\n</div>\n\n            </div>\n\n            <div class="user-account__buttons-wrapper">\n                <div class="user-account__account-actions js-buttons-wrapper">\n                    <button class="form-btn form-btn--grey is-disabled js-cancel" disabled>Cancel</button>\n                    <button class="form-btn is-disabled js-submit" type="submit" disabled>Save Changes</button>\n                    <div class="loader js-loader u-hide"></div>\n                </div>\n                <button class="form-btn form-btn--grey js-account-signout u-show-tablet">Sign Out<svg class="icon"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="/resources/prod/v8.15.0/i/svg-output/icons.svg#icn-sign-out"></use></svg></button>\n            </div>\n        </form>\n\n    </div>\n\n    <div class="user-account__wrapper js-panel-account-password u-hide">\n        <form id="account-edit-password" name="account-edit-password" novalidate>\n    <div class="user-account__tabs-wrapper">\n\n        <h1 class="overlay__title">\n            Edit your password\n            <span class="overlay__title__option"><a href="#" class="form-cta js-cancel-password">back</a></span>\n        </h1>\n\n        <div class="form-group form-group--password">\n            <div class="form-group__password-action js-toggle-password">Show</div>\n            <label class="form-group__label" for="current-password">Current Password *</label>\n            <input class="form-group__element" type="password" required name="current-password" id="current-password" />\n            <p class="js-error form-error"></p>\n            <p class="js-current-pwd-error form-error form-error--email">Invalid current password</p>\n        </div>\n\n        <a class="form-cta form-cta--right" href="/forgot-password">Forgot password?</a>\n\n        <div class="form-block">\n            <div class="form-group form-group--password">\n                <div class="form-group__password-action js-toggle-password">Show</div>\n                <label class="form-group__label" for="new-password">New password *</label>\n                <input class="form-group__element" type="password" required name="new-password" id="new-password" />\n                <div class="form-block__verify-password form-block__verify-password--slider js-verify-password">\n                    Password must include...\n                    <ul class="form-block__verify-list">\n                        <li class="js-verify-length">8 or more characters</li>\n                        <li class="js-verify-letters">At least one upper and lower case letter</li>\n                        <li class="js-verify-number">At least one number or symbol</li>\n                    </ul>\n                </div>\n                <p class="js-error form-error"></p>\n                <p class="js-new-pwd-error form-error form-error--email">The new password needs to be different than the current one.</p>\n            </div>\n        </div>\n\n        <div class="form-group form-group--password">\n            <div class="form-group__password-action js-toggle-password">Show</div>\n            <label class="form-group__label" for="confirm-password">Confirm new password *</label>\n            <input class="form-group__element" type="password" required name="confirm-password" id="confirm-password" />\n            <p class="js-error form-error"></p>\n            <p class="js-confirm-pwd-error form-error form-error--email">The confirmation does not match your new password</p>\n        </div>\n    </div>\n\n    <div class="user-account__buttons-wrapper">\n        <div class="user-account__account-actions">\n            <button class="form-btn form-btn--grey js-cancel-password" type="button">Cancel</button>\n            <button class="form-btn is-disabled js-submit-password" type="submit" disabled>Change Password</button>\n            <div class="loader js-password-loader u-hide"></div>\n        </div>\n    </div>\n</form>\n\n    </div>\n\n</section>\n\n\n<div class="js-mobile-banner mobile-banner " data-widget="mobile-banner">\n    <div class="wrapper">\n        <div class="col-12">\n            <div class="mobile-banner__wrapper">\n                <p class="mobile-banner__header">Official ICC App</p>\n                <p class="mobile-banner__subheader"><strong>Your App for international cricket.</strong> The official ICC app provides coverage across all of the current international action including fixtures, results, videos, ICC news, rankings and more. Don\xe2\x80\x99t miss a moment and keep up with the latest from around the world of cricket!</p>\n                <div class="mobile-banner__app-buttons">\n                    <a target="_blank" href="https://www.icc-cricket.com/mobile" class="btn">Find Out More</a>\n                </div>\n            </div>\n        </div>\n    </div>\n    <a class="mobile-banner__close js-mobile-banner-close">\n        <svg class="icon"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="/resources/prod/v8.15.0/i/svg-output/icons.svg#icn-close"></use></svg>\n    </a>\n</div>\n\n\t<div class="global-header ">\n\t\t<ul class="global-header__list">\n                    <li class="global-header__item ">\n            \t\t\t<a href="http://www.icctravelandtours.com/" class="global-header__link"><svg class="icon plane"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="/resources/prod/v8.15.0/i/svg-output/icons.svg#icn-plane"></use></svg>ICC Travel & Tours</a>\n            \t\t</li>\n                    <li class="global-header__item ">\n            \t\t\t<a href="https://tickets.t20worldcup.com/content/wt20/home.aspx" class="global-header__link"><svg class="icon tickets"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="/resources/prod/v8.15.0/i/svg-output/icons.svg#icn-tickets"></use></svg>ICC Tickets</a>\n            \t\t</li>\n                    <li class="global-header__item ">\n            \t\t\t<a href="https://www.t20worldcupshop.com/" class="global-header__link"><svg class="icon shopping-cart"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="/resources/prod/v8.15.0/i/svg-output/icons.svg#icn-shopping-cart"></use></svg>T20 Shop</a>\n            \t\t</li>\n\t\t</ul>\n\t\t\n    <ul class="global-header-social__list">\n            <li class="global-header-social__item">\n                <a href="https://www.facebook.com/icc/" class="global-header-social__link global-header-social__link--facebook-f" target="_blank">\n                    <svg class="icon"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="/resources/prod/v8.15.0/i/svg-output/icons.svg#icn-facebook-f"></use></svg>\n                </a>\n            </li>\n            <li class="global-header-social__item">\n                <a href="https://twitter.com/ICC" class="global-header-social__link global-header-social__link--twitter" target="_blank">\n                    <svg class="icon"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="/resources/prod/v8.15.0/i/svg-output/icons.svg#icn-twitter"></use></svg>\n                </a>\n            </li>\n            <li class="global-header-social__item">\n                <a href="https://www.instagram.com/icc/" class="global-header-social__link global-header-social__lin

In [639]:
soup6_2=BeautifulSoup(page6_2.content)

In [640]:
#print(soup6_2.prettify())

In [641]:
name=soup6_2.find('div',class_='rankings-block__banner--name-large')
name

In [642]:
name=soup6_2.find_all('td',class_='table-body__cell rankings-table__name name')
name

[<td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/1785">Lizelle Lee</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/466">Alyssa Healy</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/573">Stafanie Taylor</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/469">Meg Lanning</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/487">Amy Satterthwaite</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/1809">Smriti Mandhana</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/558">Mithali Raj</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/1800">Natalie Sciver</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/3176">Laura Wolvaardt</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/471">Ellyse Perry</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/600">Chamari Athapaththu</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/552">Heather Knight</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/465">Rachael Haynes</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/559">Harmanpreet Kaur</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/417">Mignon du Preez</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/1817">Beth Mooney</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/568">Poonam Raut</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/474">Suzie Bates</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/478">Sophie Devine</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/3192">Deepti Sharma</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/424">Marizanne Kapp</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/635">Nahida Khan</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/806">Amy Jones</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/631">Javeria Khan</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/629">Bismah Maroof</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/430">Dane van Niekerk</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/3126">Hayley Matthews</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/1758">Nicole Bolton</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/1824">Fargana Hoque</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/4128">Ashleigh Gardner</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/1830">Rumana Ahmed</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/1013">Chloe-Lesleigh Tryon</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/484">Katie Perkins</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/3210">Aliya Riaz</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/557">Danielle Wyatt</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/428">Sune Luus</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/3756">Amelia Kerr</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/468">Jess Jonassen</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/547">Katherine Brunt</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/636">Nida Dar</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/418">Trisha Chetty</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/482">Katey Martin</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/3202">Harshitha Madavi</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/">Brooke Halliday</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/1801">Fran Wilson</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/5051">Jemimah Rodriques</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/1813">Shikha Pandey</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/1790">Maddie Green</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/574">Shemaine Campbelle</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/607">Dilani Manodara</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/3204">Nigar Sultana</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/5311">Umaima Sohail</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/5074">Priya Punia</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/4049">Lara Goodall</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/3172">Lauren Winfield</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/562">Jhulan Goswami</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/4325">Chedean Nation</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/1004">Rachel Priest</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/1017">Kyshona Knight</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/579">Kycia Knight</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/5007">Lauren Down</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/1008">Sidra Ameen</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/597">Nilakshi Silva</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/892">Nicola Carey</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/1792">Hayley Jensen</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/5294">Sheneta Grimmond</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/1818">Salma Khatun</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/5068">Taniya Bhatia</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/4041">Georgia Wareham</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/1814">Poonam Yadav</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/">Anne Bosch</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/1836">Andrie Steyn</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/891">Avanthika Mendis</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/555">Anya Shrubsole</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/1018">Natasha McLean</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/1832">Sharmin Supta</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/3168">Rajeshwari Gayakwad</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/3160">Leigh Kasperek</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/3264">Anushka Sanjeewani</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/1798">Kate Cross</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/603">Inoka Ranaweera</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/1005">Lea Tahuhu</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/578">Stacy-Ann King</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/997">Megan Schutt</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/1015">Oshadi Ranasinghe</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/4315">Nashra Sandhu</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/3167">Sushma Verma</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/1837">Chinelle Henry</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/3124">Shamilia Connell</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/1825">Sanjida Islam</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/">Jess Kerr</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/3163">Hannah Rowe</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/423">Shabnim Ismail</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/3125">Afy Fletcher</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/3337">Sophie Ecclestone</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/1006">Diana Baig</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/3209">Sidra Nawaz</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/1829">Panna Ghosh</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/3199">Ama Kanchana</a>
 </td>]

In [643]:
players_name=['Tammy Beauont']             
cnt=1
for i in name:
    if cnt<10:
        players_name.append(i.text.replace('\n',''))
        cnt+=1
players_name

['Tammy Beauont',
 'Lizelle Lee',
 'Alyssa Healy',
 'Stafanie Taylor',
 'Meg Lanning',
 'Amy Satterthwaite',
 'Smriti Mandhana',
 'Mithali Raj',
 'Natalie Sciver',
 'Laura Wolvaardt']

In [644]:
team=soup6_2.find('div',class_='rankings-block__banner--nationality')
team.text

'\n\nENG\n                    '

In [645]:
Team=soup6_2.find_all('span',class_='table-body__logo-text')
Team

[<span class="table-body__logo-text">SA</span>,
 <span class="table-body__logo-text">AUS</span>,
 <span class="table-body__logo-text">WI</span>,
 <span class="table-body__logo-text">AUS</span>,
 <span class="table-body__logo-text">NZ</span>,
 <span class="table-body__logo-text">IND</span>,
 <span class="table-body__logo-text">IND</span>,
 <span class="table-body__logo-text">ENG</span>,
 <span class="table-body__logo-text">SA</span>,
 <span class="table-body__logo-text">AUS</span>,
 <span class="table-body__logo-text">SL</span>,
 <span class="table-body__logo-text">ENG</span>,
 <span class="table-body__logo-text">AUS</span>,
 <span class="table-body__logo-text">IND</span>,
 <span class="table-body__logo-text">SA</span>,
 <span class="table-body__logo-text">AUS</span>,
 <span class="table-body__logo-text">IND</span>,
 <span class="table-body__logo-text">NZ</span>,
 <span class="table-body__logo-text">NZ</span>,
 <span class="table-body__logo-text">IND</span>,
 <span class="table-body__logo-text">SA</span>,
 <span class="table-body__logo-text">PAK</span>,
 <span class="table-body__logo-text">ENG</span>,
 <span class="table-body__logo-text">PAK</span>,
 <span class="table-body__logo-text">PAK</span>,
 <span class="table-body__logo-text">SA</span>,
 <span class="table-body__logo-text">WI</span>,
 <span class="table-body__logo-text">AUS</span>,
 <span class="table-body__logo-text">BAN</span>,
 <span class="table-body__logo-text">AUS</span>,
 <span class="table-body__logo-text">BAN</span>,
 <span class="table-body__logo-text">SA</span>,
 <span class="table-body__logo-text">NZ</span>,
 <span class="table-body__logo-text">PAK</span>,
 <span class="table-body__logo-text">ENG</span>,
 <span class="table-body__logo-text">SA</span>,
 <span class="table-body__logo-text">NZ</span>,
 <span class="table-body__logo-text">AUS</span>,
 <span class="table-body__logo-text">ENG</span>,
 <span class="table-body__logo-text">PAK</span>,
 <span class="table-body__logo-text">SA</span>,
 <span class="table-body__logo-text">NZ</span>,
 <span class="table-body__logo-text">SL</span>,
 <span class="table-body__logo-text">NZ</span>,
 <span class="table-body__logo-text">ENG</span>,
 <span class="table-body__logo-text">IND</span>,
 <span class="table-body__logo-text">IND</span>,
 <span class="table-body__logo-text">NZ</span>,
 <span class="table-body__logo-text">WI</span>,
 <span class="table-body__logo-text">SL</span>,
 <span class="table-body__logo-text">BAN</span>,
 <span class="table-body__logo-text">PAK</span>,
 <span class="table-body__logo-text">IND</span>,
 <span class="table-body__logo-text">SA</span>,
 <span class="table-body__logo-text">ENG</span>,
 <span class="table-body__logo-text">IND</span>,
 <span class="table-body__logo-text">WI</span>,
 <span class="table-body__logo-text">NZ</span>,
 <span class="table-body__logo-text">WI</span>,
 <span class="table-body__logo-text">WI</span>,
 <span class="table-body__logo-text">NZ</span>,
 <span class="table-body__logo-text">PAK</span>,
 <span class="table-body__logo-text">SL</span>,
 <span class="table-body__logo-text">AUS</span>,
 <span class="table-body__logo-text">NZ</span>,
 <span class="table-body__logo-text">WI</span>,
 <span class="table-body__logo-text">BAN</span>,
 <span class="table-body__logo-text">IND</span>,
 <span class="table-body__logo-text">AUS</span>,
 <span class="table-body__logo-text">IND</span>,
 <span class="table-body__logo-text">SA</span>,
 <span class="table-body__logo-text">SA</span>,
 <span class="table-body__logo-text">SL</span>,
 <span class="table-body__logo-text">ENG</span>,
 <span class="table-body__logo-text">WI</span>,
 <span class="table-body__logo-text">BAN</span>,
 <span class="table-body__logo-text">IND</span>,
 <span class="table-body__logo-text">NZ</span>,
 <span class="table-body__logo-text">SL</span>,
 <span class="table-body__logo-text">ENG</span>,
 <span class="table-body__logo-text">SL</span>,
 <span class="table-body__logo-text">NZ</span>,
 <span class="table-body__logo-text">WI</span>,
 <span class="table-body__logo-text">AUS</span>,
 <span class="table-body__logo-text">SL</span>,
 <span class="table-body__logo-text">PAK</span>,
 <span class="table-body__logo-text">IND</span>,
 <span class="table-body__logo-text">WI</span>,
 <span class="table-body__logo-text">WI</span>,
 <span class="table-body__logo-text">BAN</span>,
 <span class="table-body__logo-text">NZ</span>,
 <span class="table-body__logo-text">NZ</span>,
 <span class="table-body__logo-text">SA</span>,
 <span class="table-body__logo-text">WI</span>,
 <span class="table-body__logo-text">ENG</span>,
 <span class="table-body__logo-text">PAK</span>,
 <span class="table-body__logo-text">PAK</span>,
 <span class="table-body__logo-text">BAN</span>,
 <span class="table-body__logo-text">SL</span>]

In [646]:
team_name=['ENG']            
cnt=1
for i in Team:
    if cnt<10:
        team_name.append(i.text.replace('\n',''))
        cnt+=1
team_name

['ENG', 'SA', 'AUS', 'WI', 'AUS', 'NZ', 'IND', 'IND', 'ENG', 'SA']

In [647]:
rating =soup6_2.find('div',class_='rankings-block__banner--rating')
rating.text

'765'

In [648]:
Rating=soup6_2.find_all('td',class_='table-body__cell rating')
Rating

[<td class="table-body__cell rating">758</td>,
 <td class="table-body__cell rating">756</td>,
 <td class="table-body__cell rating">746</td>,
 <td class="table-body__cell rating">723</td>,
 <td class="table-body__cell rating">715</td>,
 <td class="table-body__cell rating">710</td>,
 <td class="table-body__cell rating">709</td>,
 <td class="table-body__cell rating">685</td>,
 <td class="table-body__cell rating">683</td>,
 <td class="table-body__cell rating">679</td>,
 <td class="table-body__cell rating">667</td>,
 <td class="table-body__cell rating">666</td>,
 <td class="table-body__cell rating">657</td>,
 <td class="table-body__cell rating">636</td>,
 <td class="table-body__cell rating">620</td>,
 <td class="table-body__cell rating">600</td>,
 <td class="table-body__cell rating">593</td>,
 <td class="table-body__cell rating">577</td>,
 <td class="table-body__cell rating">573</td>,
 <td class="table-body__cell rating">568</td>,
 <td class="table-body__cell rating">560</td>,
 <td class="table-body__cell rating">560</td>,
 <td class="table-body__cell rating">536</td>,
 <td class="table-body__cell rating">536</td>,
 <td class="table-body__cell rating">520</td>,
 <td class="table-body__cell rating">498</td>,
 <td class="table-body__cell rating">461</td>,
 <td class="table-body__cell rating">456</td>,
 <td class="table-body__cell rating">445</td>,
 <td class="table-body__cell rating">440</td>,
 <td class="table-body__cell rating">437</td>,
 <td class="table-body__cell rating">437</td>,
 <td class="table-body__cell rating">413</td>,
 <td class="table-body__cell rating">410</td>,
 <td class="table-body__cell rating">404</td>,
 <td class="table-body__cell rating">398</td>,
 <td class="table-body__cell rating">396</td>,
 <td class="table-body__cell rating">380</td>,
 <td class="table-body__cell rating">361</td>,
 <td class="table-body__cell rating">360</td>,
 <td class="table-body__cell rating">359</td>,
 <td class="table-body__cell rating">357</td>,
 <td class="table-body__cell rating">353</td>,
 <td class="table-body__cell rating">350</td>,
 <td class="table-body__cell rating">341</td>,
 <td class="table-body__cell rating">337</td>,
 <td class="table-body__cell rating">335</td>,
 <td class="table-body__cell rating">320</td>,
 <td class="table-body__cell rating">319</td>,
 <td class="table-body__cell rating">319</td>,
 <td class="table-body__cell rating">317</td>,
 <td class="table-body__cell rating">310</td>,
 <td class="table-body__cell rating">305</td>,
 <td class="table-body__cell rating">305</td>,
 <td class="table-body__cell rating">302</td>,
 <td class="table-body__cell rating">294</td>,
 <td class="table-body__cell rating">292</td>,
 <td class="table-body__cell rating">285</td>,
 <td class="table-body__cell rating">281</td>,
 <td class="table-body__cell rating">276</td>,
 <td class="table-body__cell rating">264</td>,
 <td class="table-body__cell rating">264</td>,
 <td class="table-body__cell rating">261</td>,
 <td class="table-body__cell rating">259</td>,
 <td class="table-body__cell rating">256</td>,
 <td class="table-body__cell rating">252</td>,
 <td class="table-body__cell rating">244</td>,
 <td class="table-body__cell rating">240</td>,
 <td class="table-body__cell rating">239</td>,
 <td class="table-body__cell rating">236</td>,
 <td class="table-body__cell rating">234</td>,
 <td class="table-body__cell rating">234</td>,
 <td class="table-body__cell rating">226</td>,
 <td class="table-body__cell rating">225</td>,
 <td class="table-body__cell rating">224</td>,
 <td class="table-body__cell rating">221</td>,
 <td class="table-body__cell rating">220</td>,
 <td class="table-body__cell rating">219</td>,
 <td class="table-body__cell rating">211</td>,
 <td class="table-body__cell rating">208</td>,
 <td class="table-body__cell rating">205</td>,
 <td class="table-body__cell rating">204</td>,
 <td class="table-body__cell rating">201</td>,
 <td class="table-body__cell rating">195</td>,
 <td class="table-body__cell rating">195</td>,
 <td class="table-body__cell rating">192</td>,
 <td class="table-body__cell rating">190</td>,
 <td class="table-body__cell rating">188</td>,
 <td class="table-body__cell rating">186</td>,
 <td class="table-body__cell rating">181</td>,
 <td class="table-body__cell rating">179</td>,
 <td class="table-body__cell rating">179</td>,
 <td class="table-body__cell rating">178</td>,
 <td class="table-body__cell rating">175</td>,
 <td class="table-body__cell rating">172</td>,
 <td class="table-body__cell rating">170</td>,
 <td class="table-body__cell rating">168</td>,
 <td class="table-body__cell rating">166</td>,
 <td class="table-body__cell rating">161</td>]

In [649]:
Ratings=['765']            
cnt=1
for i in Rating:
    if cnt<10:
        Ratings.append(i.text.replace('\n',''))
        cnt+=1
Ratings

['765', '758', '756', '746', '723', '715', '710', '709', '685', '683']

In [650]:
print(len(players_name),len(team_name),len(Ratings))

10 10 10

In [651]:
import pandas as pd
Top_10_Womens_ODI_Player=pd.DataFrame({})
Top_10_Womens_ODI_Player['Name']=players_name
Top_10_Womens_ODI_Player['Team']=team_name
Top_10_Womens_ODI_Player['Rating']=Ratings

In [652]:
Top_10_Womens_ODI_Player

                Name Team Rating
0      Tammy Beauont  ENG    765
1        Lizelle Lee   SA    758
2       Alyssa Healy  AUS    756
3    Stafanie Taylor   WI    746
4        Meg Lanning  AUS    723
5  Amy Satterthwaite   NZ    715
6    Smriti Mandhana  IND    710
7        Mithali Raj  IND    709
8     Natalie Sciver  ENG    685
9    Laura Wolvaardt   SA    683

##### 6.3  Top 10 women’s ODI all-rounder along with the records of their team and rating

In [653]:
page6_3=requests.get('https://www.icc-cricket.com/rankings/womens/player-rankings/odi/all-rounder')
page6_3

In [654]:
#page6_3.content

In [655]:
soup6_3=BeautifulSoup(page6_3.content)

In [656]:
#print(soup6_3.prettify())

In [657]:
name=soup6_3.find('div',class_='rankings-block__banner--name-large')
name.text

'Marizanne Kapp'

In [658]:
name=soup6_3.find_all('td',class_='table-body__cell rankings-table__name name')
name

[<td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/471">Ellyse Perry</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/573">Stafanie Taylor</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/1800">Natalie Sciver</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/3192">Deepti Sharma</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/468">Jess Jonassen</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/4128">Ashleigh Gardner</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/430">Dane van Niekerk</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/478">Sophie Devine</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/3756">Amelia Kerr</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/547">Katherine Brunt</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/1813">Shikha Pandey</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/562">Jhulan Goswami</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/552">Heather Knight</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/1830">Rumana Ahmed</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/3126">Hayley Matthews</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/559">Harmanpreet Kaur</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/600">Chamari Athapaththu</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/428">Sune Luus</a>
 </td>,
 <td class="table-body__cell rankings-table__name name">
 <a href="/rankings/womens/player-rankings/1814">Poonam Yadav</a>
 </td>]

In [659]:
allrounder_name=['Marizanne Kapp']             
cnt=1
for i in name:
    if cnt<10:
        allrounder_name.append(i.text.replace('\n',''))
        cnt+=1
allrounder_name

['Marizanne Kapp',
 'Ellyse Perry',
 'Stafanie Taylor',
 'Natalie Sciver',
 'Deepti Sharma',
 'Jess Jonassen',
 'Ashleigh Gardner',
 'Dane van Niekerk',
 'Sophie Devine',
 'Amelia Kerr']

In [660]:
team=soup6_3.find('div',class_='rankings-block__banner--nationality')
team.text

'\n\nSA\n                    '

In [661]:
Team=soup6_3.find_all('span',class_='table-body__logo-text')
Team

[<span class="table-body__logo-text">AUS</span>,
 <span class="table-body__logo-text">WI</span>,
 <span class="table-body__logo-text">ENG</span>,
 <span class="table-body__logo-text">IND</span>,
 <span class="table-body__logo-text">AUS</span>,
 <span class="table-body__logo-text">AUS</span>,
 <span class="table-body__logo-text">SA</span>,
 <span class="table-body__logo-text">NZ</span>,
 <span class="table-body__logo-text">NZ</span>,
 <span class="table-body__logo-text">ENG</span>,
 <span class="table-body__logo-text">IND</span>,
 <span class="table-body__logo-text">IND</span>,
 <span class="table-body__logo-text">ENG</span>,
 <span class="table-body__logo-text">BAN</span>,
 <span class="table-body__logo-text">WI</span>,
 <span class="table-body__logo-text">IND</span>,
 <span class="table-body__logo-text">SL</span>,
 <span class="table-body__logo-text">SA</span>,
 <span class="table-body__logo-text">IND</span>]

In [662]:
team_name=['SA']            
cnt=1
for i in Team:
    if cnt<10:
        team_name.append(i.text.replace('\n',''))
        cnt+=1
team_name

['SA', 'AUS', 'WI', 'ENG', 'IND', 'AUS', 'AUS', 'SA', 'NZ', 'NZ']

In [663]:
Rating=soup6_3.find_all('td',class_='table-body__cell rating')
Rating

[<td class="table-body__cell rating">418</td>,
 <td class="table-body__cell rating">410</td>,
 <td class="table-body__cell rating">349</td>,
 <td class="table-body__cell rating">343</td>,
 <td class="table-body__cell rating">307</td>,
 <td class="table-body__cell rating">252</td>,
 <td class="table-body__cell rating">243</td>,
 <td class="table-body__cell rating">242</td>,
 <td class="table-body__cell rating">236</td>,
 <td class="table-body__cell rating">236</td>,
 <td class="table-body__cell rating">204</td>,
 <td class="table-body__cell rating">200</td>,
 <td class="table-body__cell rating">189</td>,
 <td class="table-body__cell rating">179</td>,
 <td class="table-body__cell rating">176</td>,
 <td class="table-body__cell rating">167</td>,
 <td class="table-body__cell rating">164</td>,
 <td class="table-body__cell rating">153</td>,
 <td class="table-body__cell rating">151</td>]

In [664]:
Ratings=[]            
cnt=0
for i in Rating:
    if cnt<10:
        Ratings.append(i.text.replace('\n',''))
        cnt+=1
Ratings

['418', '410', '349', '343', '307', '252', '243', '242', '236', '236']

In [665]:
print(len(allrounder_name),len(team_name),len(Ratings))

10 10 10

In [666]:
import pandas as pd
Top_10_ODI_all_rounder=pd.DataFrame({})
Top_10_ODI_all_rounder['Name']=allrounder_name
Top_10_ODI_all_rounder['Team']=team_name
Top_10_ODI_all_rounder['Rating']=Ratings

In [667]:
Top_10_ODI_all_rounder

               Name Team Rating
0    Marizanne Kapp   SA    418
1      Ellyse Perry  AUS    410
2   Stafanie Taylor   WI    349
3    Natalie Sciver  ENG    343
4     Deepti Sharma  IND    307
5     Jess Jonassen  AUS    252
6  Ashleigh Gardner  AUS    243
7  Dane van Niekerk   SA    242
8     Sophie Devine   NZ    236
9       Amelia Kerr   NZ    236

# Assignment Question No 7

 Write a python program to scrape details of all the mobile phones under Rs. 20,000 listed on Amazon.in. 
    
 The scraped data should include Product Name, Price, Image URL and Average Rating.

In [722]:
page7=requests.get('https://www.amazon.in/Mobile-Phone-Under-20000-Rupees/s?k=Mobile+Phone+Under+20000+Rupees')
page7

In [723]:
#page7.content

In [724]:
soup7=BeautifulSoup(page7.content)

In [725]:
#print(soup7.prettify())

In [726]:
name2=soup7.find_all('h2',class_='a-size-mini a-spacing-none a-color-base s-line-clamp-2')
name2

[<h2 class="a-size-mini a-spacing-none a-color-base s-line-clamp-2">
 <a class="a-link-normal a-text-normal" href="/Samsung-Galaxy-Ocean-128GB-Storage/dp/B07HGGYWL6?dchild=1" target="_blank">
 <span class="a-size-base-plus a-color-base a-text-normal" dir="auto">Samsung Galaxy M31 (Ocean Blue, 6GB RAM, 128GB Storage)</span>
 </a>
 </h2>,
 <h2 class="a-size-mini a-spacing-none a-color-base s-line-clamp-2">
 <a class="a-link-normal a-text-normal" href="/Samsung-Galaxy-Midnight-Blue-Storage/dp/B07HGJJ559?dchild=1" target="_blank">
 <span class="a-size-base-plus a-color-base a-text-normal" dir="auto">Samsung Galaxy M21 (Midnight Blue, 4GB RAM, 64GB Storage)</span>
 </a>
 </h2>,
 <h2 class="a-size-mini a-spacing-none a-color-base s-line-clamp-2">
 <a class="a-link-normal a-text-normal" href="/Test-Exclusive-557/dp/B077PWJ8RS?dchild=1" target="_blank">
 <span class="a-size-base-plus a-color-base a-text-normal" dir="auto">Redmi Note 9 Pro Max (Interstellar Black, 6GB RAM, 64GB Storage) - 64MP Quad Camera &amp; Alexa Hands-Free Capable</span>
 </a>
 </h2>,
 <h2 class="a-size-mini a-spacing-none a-color-base s-line-clamp-2">
 <a class="a-link-normal a-text-normal" href="/Oppo-Mystery-Storage-Additional-Exchange/dp/B08444S68L?dchild=1" target="_blank">
 <span class="a-size-base-plus a-color-base a-text-normal" dir="auto">Oppo A31 (Mystery Black, 6GB RAM, 128GB Storage) with No Cost EMI/Additional Exchange Offers</span>
 </a>
 </h2>,
 <h2 class="a-size-mini a-spacing-none a-color-base s-line-clamp-2"><a class="a-link-normal a-text-normal" href="/Redmi-9A-2GB-32GB-Storage/dp/B08696XB4B?dchild=1" target="_blank"><span class="a-size-medium a-color-base a-text-normal">Redmi 9A (Nature Green, 2GB Ram, 32GB Storage) | 2GHz Octa-core Helio G25 Processor</span> </a> </h2>,
 <h2 class="a-size-mini a-spacing-none a-color-base s-line-clamp-2"><a class="a-link-normal a-text-normal" href="/Oppo-Fantasy-Storage-Additional-Exchange/dp/B08444SXZ6?dchild=1" target="_blank"><span class="a-size-medium a-color-base a-text-normal">Oppo A31 (Fantasy White, 6GB RAM, 128GB Storage) with No Cost EMI/Additional Exchange Offers</span> </a> </h2>,
 <h2 class="a-size-mini a-spacing-none a-color-base s-line-clamp-2"><a class="a-link-normal a-text-normal" href="/Oppo-Mystery-Storage-Additional-Exchange/dp/B08444S68L?dchild=1" target="_blank"><span class="a-size-medium a-color-base a-text-normal">Oppo A31 (Mystery Black, 6GB RAM, 128GB Storage) with No Cost EMI/Additional Exchange Offers</span> </a> </h2>,
 <h2 class="a-size-mini a-spacing-none a-color-base s-line-clamp-2"><a class="a-link-normal a-text-normal" href="/Vivo-Fusion-Storage-Additional-Exchange/dp/B07KX1S161?dchild=1" target="_blank"><span class="a-size-medium a-color-base a-text-normal">Vivo Y91i (Fusion Black, 2GB RAM, 32GB Storage) with No Cost EMI/Additional Exchange Offers</span> </a> </h2>,
 <h2 class="a-size-mini a-spacing-none a-color-base s-line-clamp-2"><a class="a-link-normal a-text-normal" href="/Redmi-Sky-Blue-64GB-Storage/dp/B08697N43N?dchild=1" target="_blank"><span class="a-size-medium a-color-base a-text-normal">Redmi 9 (Sky Blue, 4GB RAM, 64GB Storage)| 5000 mAh| 2.3GHz Mediatek Helio G35 Octa core Processor</span> </a> </h2>,
 <h2 class="a-size-mini a-spacing-none a-color-base s-line-clamp-2"><a class="a-link-normal a-text-normal" href="/Vivo-Storage-Additional-Exchange-Offers/dp/B07KXCKPZZ?dchild=1" target="_blank"><span class="a-size-medium a-color-base a-text-normal">Vivo Y91i (Ocean Blue, 2GB RAM, 32GB Storage) with No Cost EMI/Additional Exchange Offers</span> </a> </h2>,
 <h2 class="a-size-mini a-spacing-none a-color-base s-line-clamp-2"><a class="a-link-normal a-text-normal" href="/Samsung-Galaxy-Ocean-128GB-Storage/dp/B07HGGYWL6?dchild=1" target="_blank"><span class="a-size-medium a-color-base a-text-normal">Samsung Galaxy M31 (Ocean Blue, 6GB RAM, 128GB Storage)</span> </a> </h2>,
 <h2 class="a-size-mini a-spacing-none a-color-base s-line-clamp-2"><a class="a-link-normal a-text-normal" href="/Redmi-9A-3GB-32GB-Storage/dp/B086973W9M?dchild=1" target="_blank"><span class="a-size-medium a-color-base a-text-normal">Redmi 9A (Sea Blue, 3GB Ram, 32GB Storage) | 2GHz Octa-core Helio G25 Processor</span> </a> </h2>,
 <h2 class="a-size-mini a-spacing-none a-color-base s-line-clamp-2"><a class="a-link-normal a-text-normal" href="/Test-Dummy_March_2020_87-Black-128BG-Storage/dp/B086984LJV?dchild=1" target="_blank"><span class="a-size-medium a-color-base a-text-normal">Redmi 9 (Sky Blue, 4GB RAM, 128GB Storage) | 5000 mAh| 2.3GHz Mediatek Helio G35 Octa core Processor</span> </a> </h2>,
 <h2 class="a-size-mini a-spacing-none a-color-base s-line-clamp-2"><a class="a-link-normal a-text-normal" href="/Oppo-Twilight-Storage-Additional-Exchange/dp/B086KCDPMR?dchild=1" target="_blank"><span class="a-size-medium a-color-base a-text-normal">Oppo A52 (Twilight Black, 6GB RAM, 128GB Storage) with No Cost EMI/Additional Exchange Offers</span> </a> </h2>,
 <h2 class="a-size-mini a-spacing-none a-color-base s-line-clamp-2"><a class="a-link-normal a-text-normal" href="/Panasonic-Storage-Finger-4000mAh-Battery/dp/B08BV2T63X?dchild=1" target="_blank"><span class="a-size-medium a-color-base a-text-normal">Panasonic Eluga i7 (2GB RAM, 16GB Storage, Finger Print Sensor, 4000mAh Battery) (Black)</span> </a> </h2>,
 <h2 class="a-size-mini a-spacing-none a-color-base s-line-clamp-2"><a class="a-link-normal a-text-normal" href="/Samsung-Galaxy-Storage-Additional-Exchange/dp/B089MQ622N?dchild=1" target="_blank"><span class="a-size-medium a-color-base a-text-normal">Samsung Galaxy M01 Core (Black, 2GB RAM, 32GB Storage) with No Cost EMI/Additional Exchange Offers</span> </a> </h2>,
 <h2 class="a-size-mini a-spacing-none a-color-base s-line-clamp-2"><a class="a-link-normal a-text-normal" href="/Redmi-Note-Pebble-Grey-Storage/dp/B086977TR6?dchild=1" target="_blank"><span class="a-size-medium a-color-base a-text-normal">Redmi Note 9 (Pebble Grey, 4GB RAM 64GB Storage) - 48MP Quad Camera &amp; Full HD+ Display</span> </a> </h2>,
 <h2 class="a-size-mini a-spacing-none a-color-base s-line-clamp-2"><a class="a-link-normal a-text-normal" href="/Realme-C12-Power-Blue-RAM/dp/B08GKHY681?dchild=1" target="_blank"><span class="a-size-medium a-color-base a-text-normal">Realme C12 (Power Blue, 3GB RAM, 32GB Storage) Without Offer</span> </a> </h2>,
 <h2 class="a-size-mini a-spacing-none a-color-base s-line-clamp-2"><a class="a-link-normal a-text-normal" href="/Samsung-Galaxy-Midnight-Blue-Storage/dp/B07HGJJ559?dchild=1" target="_blank"><span class="a-size-medium a-color-base a-text-normal">Samsung Galaxy M21 (Midnight Blue, 4GB RAM, 64GB Storage)</span> </a> </h2>,
 <h2 class="a-size-mini a-spacing-none a-color-base s-line-clamp-2"><a class="a-link-normal a-text-normal" href="/Samsung-Galaxy-M12-Storage-Processor/dp/B08XGDN3TZ?dchild=1" target="_blank"><span class="a-size-medium a-color-base a-text-normal">Samsung Galaxy M12 (Blue,4GB RAM, 64GB Storage) 6000 mAh with 8nm Processor | True 48 MP Quad Camera | 90Hz Refresh Rate</span> </a> </h2>]

In [727]:
p_name2=[]
for i in name2:
    p_name2.append(i.text.replace('\n',''))
p_name2

['Samsung Galaxy M31 (Ocean Blue, 6GB RAM, 128GB Storage)',
 'Samsung Galaxy M21 (Midnight Blue, 4GB RAM, 64GB Storage)',
 'Redmi Note 9 Pro Max (Interstellar Black, 6GB RAM, 64GB Storage) - 64MP Quad Camera & Alexa Hands-Free Capable',
 'Oppo A31 (Mystery Black, 6GB RAM, 128GB Storage) with No Cost EMI/Additional Exchange Offers',
 'Redmi 9A (Nature Green, 2GB Ram, 32GB Storage) | 2GHz Octa-core Helio G25 Processor  ',
 'Oppo A31 (Fantasy White, 6GB RAM, 128GB Storage) with No Cost EMI/Additional Exchange Offers  ',
 'Oppo A31 (Mystery Black, 6GB RAM, 128GB Storage) with No Cost EMI/Additional Exchange Offers  ',
 'Vivo Y91i (Fusion Black, 2GB RAM, 32GB Storage) with No Cost EMI/Additional Exchange Offers  ',
 'Redmi 9 (Sky Blue, 4GB RAM, 64GB Storage)| 5000 mAh| 2.3GHz Mediatek Helio G35 Octa core Processor  ',
 'Vivo Y91i (Ocean Blue, 2GB RAM, 32GB Storage) with No Cost EMI/Additional Exchange Offers  ',
 'Samsung Galaxy M31 (Ocean Blue, 6GB RAM, 128GB Storage)  ',
 'Redmi 9A (Sea Blue, 3GB Ram, 32GB Storage) | 2GHz Octa-core Helio G25 Processor  ',
 'Redmi 9 (Sky Blue, 4GB RAM, 128GB Storage) | 5000 mAh| 2.3GHz Mediatek Helio G35 Octa core Processor  ',
 'Oppo A52 (Twilight Black, 6GB RAM, 128GB Storage) with No Cost EMI/Additional Exchange Offers  ',
 'Panasonic Eluga i7 (2GB RAM, 16GB Storage, Finger Print Sensor, 4000mAh Battery) (Black)  ',
 'Samsung Galaxy M01 Core (Black, 2GB RAM, 32GB Storage) with No Cost EMI/Additional Exchange Offers  ',
 'Redmi Note 9 (Pebble Grey, 4GB RAM 64GB Storage) - 48MP Quad Camera & Full HD+ Display  ',
 'Realme C12 (Power Blue, 3GB RAM, 32GB Storage) Without Offer  ',
 'Samsung Galaxy M21 (Midnight Blue, 4GB RAM, 64GB Storage)  ',
 'Samsung Galaxy M12 (Blue,4GB RAM, 64GB Storage) 6000 mAh with 8nm Processor | True 48 MP Quad Camera | 90Hz Refresh Rate  ']

In [728]:
mobile_name=[]
fname=''  
str2=')'
# declaring empty string for converting list item into individual list    
for i in range(0,len(p_name2)):
    names=p_name2[i]    # declaring individual item of list in a string
    if '|' in names:
        fname=names.split(')')
        mobile_name.append(fname[0]+str2)
    elif ')' in names:
        fname=names.split(')')
        mobile_name.append(fname[0]+str2)
    else:
        fname=names          # splitting the string into list
        mobile_name.append(fname+str2)

In [729]:
mobile_name

['Samsung Galaxy M31 (Ocean Blue, 6GB RAM, 128GB Storage)',
 'Samsung Galaxy M21 (Midnight Blue, 4GB RAM, 64GB Storage)',
 'Redmi Note 9 Pro Max (Interstellar Black, 6GB RAM, 64GB Storage)',
 'Oppo A31 (Mystery Black, 6GB RAM, 128GB Storage)',
 'Redmi 9A (Nature Green, 2GB Ram, 32GB Storage)',
 'Oppo A31 (Fantasy White, 6GB RAM, 128GB Storage)',
 'Oppo A31 (Mystery Black, 6GB RAM, 128GB Storage)',
 'Vivo Y91i (Fusion Black, 2GB RAM, 32GB Storage)',
 'Redmi 9 (Sky Blue, 4GB RAM, 64GB Storage)',
 'Vivo Y91i (Ocean Blue, 2GB RAM, 32GB Storage)',
 'Samsung Galaxy M31 (Ocean Blue, 6GB RAM, 128GB Storage)',
 'Redmi 9A (Sea Blue, 3GB Ram, 32GB Storage)',
 'Redmi 9 (Sky Blue, 4GB RAM, 128GB Storage)',
 'Oppo A52 (Twilight Black, 6GB RAM, 128GB Storage)',
 'Panasonic Eluga i7 (2GB RAM, 16GB Storage, Finger Print Sensor, 4000mAh Battery)',
 'Samsung Galaxy M01 Core (Black, 2GB RAM, 32GB Storage)',
 'Redmi Note 9 (Pebble Grey, 4GB RAM 64GB Storage)',
 'Realme C12 (Power Blue, 3GB RAM, 32GB Storage)',
 'Samsung Galaxy M21 (Midnight Blue, 4GB RAM, 64GB Storage)',
 'Samsung Galaxy M12 (Blue,4GB RAM, 64GB Storage)']

In [730]:
price=soup7.find_all('span',class_='a-price-whole')
price

[<span class="a-price-whole">14,999</span>,
 <span class="a-price-whole">12,499</span>,
 <span class="a-price-whole">14,999</span>,
 <span class="a-price-whole">11,990</span>,
 <span class="a-price-whole">6,799</span>,
 <span class="a-price-whole">11,990</span>,
 <span class="a-price-whole">11,990</span>,
 <span class="a-price-whole">7,490</span>,
 <span class="a-price-whole">8,799</span>,
 <span class="a-price-whole">7,490</span>,
 <span class="a-price-whole">14,999</span>,
 <span class="a-price-whole">7,499</span>,
 <span class="a-price-whole">9,999</span>,
 <span class="a-price-whole">14,990</span>,
 <span class="a-price-whole">5,000</span>,
 <span class="a-price-whole">6,199</span>,
 <span class="a-price-whole">10,999</span>,
 <span class="a-price-whole">8,445</span>,
 <span class="a-price-whole">12,499</span>,
 <span class="a-price-whole">10,999</span>]

In [731]:
prices=[]
for i in price:
    prices.append(i.text)

In [732]:
prices

['14,999',
 '12,499',
 '14,999',
 '11,990',
 '6,799',
 '11,990',
 '11,990',
 '7,490',
 '8,799',
 '7,490',
 '14,999',
 '7,499',
 '9,999',
 '14,990',
 '5,000',
 '6,199',
 '10,999',
 '8,445',
 '12,499',
 '10,999']

In [733]:
rating=soup7.find_all('span',class_="a-icon-alt")
rating

[<span class="a-icon-alt">4.3 out of 5 stars</span>,
 <span class="a-icon-alt">4.2 out of 5 stars</span>,
 <span class="a-icon-alt">4.2 out of 5 stars</span>,
 <span class="a-icon-alt">4.2 out of 5 stars</span>,
 <span class="a-icon-alt">4.2 out of 5 stars</span>,
 <span class="a-icon-alt">4.2 out of 5 stars</span>,
 <span class="a-icon-alt">4.2 out of 5 stars</span>,
 <span class="a-icon-alt">4.2 out of 5 stars</span>,
 <span class="a-icon-alt">4.2 out of 5 stars</span>,
 <span class="a-icon-alt">4.1 out of 5 stars</span>,
 <span class="a-icon-alt">4.3 out of 5 stars</span>,
 <span class="a-icon-alt">4.2 out of 5 stars</span>,
 <span class="a-icon-alt">4.2 out of 5 stars</span>,
 <span class="a-icon-alt">4.2 out of 5 stars</span>,
 <span class="a-icon-alt">3.0 out of 5 stars</span>,
 <span class="a-icon-alt">3.7 out of 5 stars</span>,
 <span class="a-icon-alt">4.3 out of 5 stars</span>,
 <span class="a-icon-alt">4.1 out of 5 stars</span>,
 <span class="a-icon-alt">4.2 out of 5 stars</span>,
 <span class="a-icon-alt">4.0 out of 5 stars</span>,
 <span class="a-icon-alt">4 Stars &amp; Up</span>,
 <span class="a-icon-alt">3 Stars &amp; Up</span>,
 <span class="a-icon-alt">2 Stars &amp; Up</span>,
 <span class="a-icon-alt">1 Star &amp; Up</span>]

In [734]:
del rating[-4:]               # last 4 ratings are taken from the sidebar of the html

In [735]:
image_url=soup7.find_all('div',class_='s-image')

In [736]:
from urllib.request import urlopen
from bs4 import BeautifulSoup
  
htmldata = urlopen('https://www.amazon.in/Mobile-Phone-Under-20000-Rupees/s?k=Mobile+Phone+Under+20000+Rupees')
soup = BeautifulSoup(htmldata, 'html.parser')
images = soup.find_all('img')

In [737]:
image_url=[]  
for item in images:
    #print(item['src'])
    image_url.append(item['src'])

In [738]:
image_url

['https://images-eu.ssl-images-amazon.com/images/G/31/gno/sprites/nav-sprite-global-1x-hm-dsk-reorg._CB405936311_.png',
 'https://images-eu.ssl-images-amazon.com/images/G/31/IN-hq/2021/img/Mobile_Traffic_/XCM_Manual_1321458_1651511_IN_3781247_400x39_en_IN._CB655944656_.jpg',
 'https://images-eu.ssl-images-amazon.com/images/S/amazon-avatars-global/b1979092-e160-4c8a-b5e8-fa8761b97e14._CR0,0,500,500_SX50_._TTW_.jpg',
 'https://m.media-amazon.com/images/I/71-Su4Wr0HL._AC_UL320_.jpg',
 'https://m.media-amazon.com/images/I/71dujTTJDZL._AC_UL320_.jpg',
 'https://m.media-amazon.com/images/I/71usqWEJleL._AC_UL320_.jpg',
 'https://m.media-amazon.com/images/I/71KCwNV6MuL._AC_UL320_.jpg',
 'https://m.media-amazon.com/images/I/71sxlhYhKWL._AC_UY218_.jpg',
 'https://m.media-amazon.com/images/I/61IhTtJUXJL._AC_UY218_.jpg',
 'https://m.media-amazon.com/images/I/71KCwNV6MuL._AC_UY218_.jpg',
 'https://m.media-amazon.com/images/I/51ZoulFBPGL._AC_UY218_.jpg',
 'https://m.media-amazon.com/images/I/71A9Vo1BatL._AC_UY218_.jpg',
 'https://m.media-amazon.com/images/I/51FnmxwFHDL._AC_UY218_.jpg',
 'https://m.media-amazon.com/images/I/71-Su4Wr0HL._AC_UY218_.jpg',
 'https://m.media-amazon.com/images/I/71sxlhYhKWL._AC_UY218_.jpg',
 'https://m.media-amazon.com/images/I/716nHhG9SWL._AC_UY218_.jpg',
 'https://m.media-amazon.com/images/I/71FPmXaDfbL._AC_UY218_.jpg',
 'https://m.media-amazon.com/images/I/41QsvcpKaZL._AC_UY218_.jpg',
 'https://m.media-amazon.com/images/I/71AYb2AGHXL._AC_UY218_.jpg',
 'https://m.media-amazon.com/images/I/71X5I1cVfbL._AC_UY218_.jpg',
 'https://m.media-amazon.com/images/I/31X1+mh8zPL._AC_UY218_.jpg',
 'https://m.media-amazon.com/images/I/71dujTTJDZL._AC_UY218_.jpg',
 'https://m.media-amazon.com/images/I/71yYaNztZ0L._AC_UY218_.jpg']

In [739]:
#as the first three url are of some another images, not related to our answer, so deleting them
del image_url [0:3]

In [740]:
image_url

['https://m.media-amazon.com/images/I/71-Su4Wr0HL._AC_UL320_.jpg',
 'https://m.media-amazon.com/images/I/71dujTTJDZL._AC_UL320_.jpg',
 'https://m.media-amazon.com/images/I/71usqWEJleL._AC_UL320_.jpg',
 'https://m.media-amazon.com/images/I/71KCwNV6MuL._AC_UL320_.jpg',
 'https://m.media-amazon.com/images/I/71sxlhYhKWL._AC_UY218_.jpg',
 'https://m.media-amazon.com/images/I/61IhTtJUXJL._AC_UY218_.jpg',
 'https://m.media-amazon.com/images/I/71KCwNV6MuL._AC_UY218_.jpg',
 'https://m.media-amazon.com/images/I/51ZoulFBPGL._AC_UY218_.jpg',
 'https://m.media-amazon.com/images/I/71A9Vo1BatL._AC_UY218_.jpg',
 'https://m.media-amazon.com/images/I/51FnmxwFHDL._AC_UY218_.jpg',
 'https://m.media-amazon.com/images/I/71-Su4Wr0HL._AC_UY218_.jpg',
 'https://m.media-amazon.com/images/I/71sxlhYhKWL._AC_UY218_.jpg',
 'https://m.media-amazon.com/images/I/716nHhG9SWL._AC_UY218_.jpg',
 'https://m.media-amazon.com/images/I/71FPmXaDfbL._AC_UY218_.jpg',
 'https://m.media-amazon.com/images/I/41QsvcpKaZL._AC_UY218_.jpg',
 'https://m.media-amazon.com/images/I/71AYb2AGHXL._AC_UY218_.jpg',
 'https://m.media-amazon.com/images/I/71X5I1cVfbL._AC_UY218_.jpg',
 'https://m.media-amazon.com/images/I/31X1+mh8zPL._AC_UY218_.jpg',
 'https://m.media-amazon.com/images/I/71dujTTJDZL._AC_UY218_.jpg',
 'https://m.media-amazon.com/images/I/71yYaNztZ0L._AC_UY218_.jpg']

In [741]:
print(len(p_name2),len(prices),len(rating),len(image_url))

20 20 20 20

In [742]:
import pandas as pd
Mobile_phones_under_20000=pd.DataFrame({})
Mobile_phones_under_20000['Product_name']=p_name2
Mobile_phones_under_20000['Price']=price
Mobile_phones_under_20000['Image Url']=image_url
Mobile_phones_under_20000['Rating']=rating

In [743]:
Mobile_phones_under_20000

,Product_name,Price,Image Url,Rating
0,"Samsung Galaxy M31 (Ocean Blue, 6GB RAM, 128GB...","[14,999]",https://m.media-amazon.com/images/I/71-Su4Wr0H...,[4.3 out of 5 stars]
1,"Samsung Galaxy M21 (Midnight Blue, 4GB RAM, 64...","[12,499]",https://m.media-amazon.com/images/I/71dujTTJDZ...,[4.2 out of 5 stars]
2,"Redmi Note 9 Pro Max (Interstellar Black, 6GB ...","[14,999]",https://m.media-amazon.com/images/I/71usqWEJle...,[4.2 out of 5 stars]
3,"Oppo A31 (Mystery Black, 6GB RAM, 128GB Storag...","[11,990]",https://m.media-amazon.com/images/I/71KCwNV6Mu...,[4.2 out of 5 stars]
4,"Redmi 9A (Nature Green, 2GB Ram, 32GB Storage)...","[6,799]",https://m.media-amazon.com/images/I/71sxlhYhKW...,[4.2 out of 5 stars]
5,"Oppo A31 (Fantasy White, 6GB RAM, 128GB Storag...","[11,990]",https://m.media-amazon.com/images/I/61IhTtJUXJ...,[4.2 out of 5 stars]
6,"Oppo A31 (Mystery Black, 6GB RAM, 128GB Storag...","[11,990]",https://m.media-amazon.com/images/I/71KCwNV6Mu...,[4.2 out of 5 stars]
7,"Vivo Y91i (Fusion Black, 2GB RAM, 32GB Storage...","[7,490]",https://m.media-amazon.com/images/I/51ZoulFBPG...,[4.2 out of 5 stars]
8,"Redmi 9 (Sky Blue, 4GB RAM, 64GB Storage)| 500...","[8,799]",https://m.media-amazon.com/images/I/71A9Vo1Bat...,[4.2 out of 5 stars]
9,"Vivo Y91i (Ocean Blue, 2GB RAM, 32GB Storage) ...","[7,490]",https://m.media-amazon.com/images/I/51FnmxwFHD...,[4.1 out of 5 stars]
10,"Samsung Galaxy M31 (Ocean Blue, 6GB RAM, 128GB...","[14,999]",https://m.media-amazon.com/images/I/71-Su4Wr0H...,[4.3 out of 5 stars]
11,"Redmi 9A (Sea Blue, 3GB Ram, 32GB Storage) | 2...","[7,499]",https://m.media-amazon.com/images/I/71sxlhYhKW...,[4.2 out of 5 stars]
12,"Redmi 9 (Sky Blue, 4GB RAM, 128GB Storage) | 5...","[9,999]",https://m.media-amazon.com/images/I/716nHhG9SW...,[4.2 out of 5 stars]
13,"Oppo A52 (Twilight Black, 6GB RAM, 128GB Stora...","[14,990]",https://m.media-amazon.com/images/I/71FPmXaDfb...,[4.2 out of 5 stars]
14,"Panasonic Eluga i7 (2GB RAM, 16GB Storage, Fin...","[5,000]",https://m.media-amazon.com/images/I/41QsvcpKaZ...,[3.0 out of 5 stars]
15,"Samsung Galaxy M01 Core (Black, 2GB RAM, 32GB ...","[6,199]",https://m.media-amazon.com/images/I/71AYb2AGHX...,[3.7 out of 5 stars]
16,"Redmi Note 9 (Pebble Grey, 4GB RAM 64GB Storag...","[10,999]",https://m.media-amazon.com/images/I/71X5I1cVfb...,[4.3 out of 5 stars]
17,"Realme C12 (Power Blue, 3GB RAM, 32GB Storage)...","[8,445]",https://m.media-amazon.com/images/I/31X1+mh8zP...,[4.1 out of 5 stars]
18,"Samsung Galaxy M21 (Midnight Blue, 4GB RAM, 64...","[12,499]",https://m.media-amazon.com/images/I/71dujTTJDZ...,[4.2 out of 5 stars]
19,"Samsung Galaxy M12 (Blue,4GB RAM, 64GB Storage...","[10,999]",https://m.media-amazon.com/images/I/71yYaNztZ0...,[4.0 out of 5 stars]

# Assignment Question No 8

Write a python program to extract information about the local weather from the National Weather Service website of USA, https://www.weather.gov/ for the city, San Francisco. You need to extract data about 7 day extended forecast display for the city. The data should include period, short description, temperature and description.

In [744]:
page8=requests.get('https://forecast.weather.gov/MapClick.php?lat=37.777120000000025&lon=-122.41963999999996#.YJL0dLUzZPY')
page8

In [745]:
#page8.content

In [746]:
soup8=BeautifulSoup(page8.content)

In [747]:
#print(soup8.prettify())

In [748]:
period=soup8.find_all('p',class_='period-name')
period

[<p class="period-name">Today<br/><br/></p>,
 <p class="period-name">Tonight<br/><br/></p>,
 <p class="period-name">Monday<br/><br/></p>,
 <p class="period-name">Monday<br/>Night</p>,
 <p class="period-name">Tuesday<br/><br/></p>,
 <p class="period-name">Tuesday<br/>Night</p>,
 <p class="period-name">Wednesday<br/><br/></p>,
 <p class="period-name">Wednesday<br/>Night</p>,
 <p class="period-name">Thursday<br/><br/></p>]

In [749]:
period_name=[]
for i in period:
    period_name.append(i.text)
period_name

['Today',
 'Tonight',
 'Monday',
 'MondayNight',
 'Tuesday',
 'TuesdayNight',
 'Wednesday',
 'WednesdayNight',
 'Thursday']

In [750]:
short_Descr=soup8.find_all('p',class_='short-desc')
short_Descr

[<p class="short-desc">Sunny</p>,
 <p class="short-desc">Clear</p>,
 <p class="short-desc">Sunny</p>,
 <p class="short-desc">Mostly Clear</p>,
 <p class="short-desc">Sunny</p>,
 <p class="short-desc">Mostly Clear</p>,
 <p class="short-desc">Sunny</p>,
 <p class="short-desc">Partly Cloudy</p>,
 <p class="short-desc">Mostly Sunny</p>]

In [751]:
short_description=[]
for i in short_Descr:
    short_description.append(i.text)
short_description

['Sunny',
 'Clear',
 'Sunny',
 'Mostly Clear',
 'Sunny',
 'Mostly Clear',
 'Sunny',
 'Partly Cloudy',
 'Mostly Sunny']

In [752]:
temp=soup8.find_all('p',class_='temp')
temp

[<p class="temp temp-high">High: 71 °F</p>,
 <p class="temp temp-low">Low: 52 °F</p>,
 <p class="temp temp-high">High: 77 °F</p>,
 <p class="temp temp-low">Low: 52 °F</p>,
 <p class="temp temp-high">High: 75 °F</p>,
 <p class="temp temp-low">Low: 51 °F</p>,
 <p class="temp temp-high">High: 69 °F</p>,
 <p class="temp temp-low">Low: 51 °F</p>,
 <p class="temp temp-high">High: 67 °F</p>]

In [753]:
temperature=[]
for i in temp:
    temperature.append(i.text)
temperature

['High: 71 °F',
 'Low: 52 °F',
 'High: 77 °F',
 'Low: 52 °F',
 'High: 75 °F',
 'Low: 51 °F',
 'High: 69 °F',
 'Low: 51 °F',
 'High: 67 °F']

In [754]:
descr=soup8.find_all('div',class_='col-sm-10 forecast-text')
descr

[<div class="col-sm-10 forecast-text">Sunny, with a high near 71. West wind 7 to 15 mph, with gusts as high as 20 mph. </div>,
 <div class="col-sm-10 forecast-text">Clear, with a low around 52. West wind 6 to 14 mph, with gusts as high as 18 mph. </div>,
 <div class="col-sm-10 forecast-text">Sunny, with a high near 77. Light west northwest wind becoming west 10 to 15 mph in the afternoon. Winds could gust as high as 20 mph. </div>,
 <div class="col-sm-10 forecast-text">Mostly clear, with a low around 52. West wind 5 to 14 mph. </div>,
 <div class="col-sm-10 forecast-text">Sunny, with a high near 75. Light west northwest wind becoming west 10 to 15 mph in the afternoon. Winds could gust as high as 20 mph. </div>,
 <div class="col-sm-10 forecast-text">Mostly clear, with a low around 51.</div>,
 <div class="col-sm-10 forecast-text">Sunny, with a high near 69.</div>,
 <div class="col-sm-10 forecast-text">Partly cloudy, with a low around 51.</div>,
 <div class="col-sm-10 forecast-text">Mostly sunny, with a high near 67.</div>,
 <div class="col-sm-10 forecast-text">Partly cloudy, with a low around 51.</div>,
 <div class="col-sm-10 forecast-text">Mostly sunny, with a high near 65.</div>,
 <div class="col-sm-10 forecast-text">Partly cloudy, with a low around 51.</div>,
 <div class="col-sm-10 forecast-text">Mostly sunny, with a high near 65.</div>]

In [755]:
description=[]
for i in descr:
    description.append(i.text)
description

['Sunny, with a high near 71. West wind 7 to 15 mph, with gusts as high as 20 mph. ',
 'Clear, with a low around 52. West wind 6 to 14 mph, with gusts as high as 18 mph. ',
 'Sunny, with a high near 77. Light west northwest wind becoming west 10 to 15 mph in the afternoon. Winds could gust as high as 20 mph. ',
 'Mostly clear, with a low around 52. West wind 5 to 14 mph. ',
 'Sunny, with a high near 75. Light west northwest wind becoming west 10 to 15 mph in the afternoon. Winds could gust as high as 20 mph. ',
 'Mostly clear, with a low around 51.',
 'Sunny, with a high near 69.',
 'Partly cloudy, with a low around 51.',
 'Mostly sunny, with a high near 67.',
 'Partly cloudy, with a low around 51.',
 'Mostly sunny, with a high near 65.',
 'Partly cloudy, with a low around 51.',
 'Mostly sunny, with a high near 65.']

In [756]:
del description[-4:]

In [757]:
print(len(period_name),len(short_description),len(temperature),len(description))

9 9 9 9

In [758]:
import pandas as pd
San_Francisco_weather_info=pd.DataFrame({})
San_Francisco_weather_info['Period']=period_name
San_Francisco_weather_info['Short_Description']=short_description
San_Francisco_weather_info['Temperature']=temperature
San_Francisco_weather_info['Description']=description

In [759]:
San_Francisco_weather_info

,Period,Short_Description,Temperature,Description
0,Today,Sunny,High: 71 °F,"Sunny, with a high near 71. West wind 7 to 15 ..."
1,Tonight,Clear,Low: 52 °F,"Clear, with a low around 52. West wind 6 to 14..."
2,Monday,Sunny,High: 77 °F,"Sunny, with a high near 77. Light west northwe..."
3,MondayNight,Mostly Clear,Low: 52 °F,"Mostly clear, with a low around 52. West wind ..."
4,Tuesday,Sunny,High: 75 °F,"Sunny, with a high near 75. Light west northwe..."
5,TuesdayNight,Mostly Clear,Low: 51 °F,"Mostly clear, with a low around 51."
6,Wednesday,Sunny,High: 69 °F,"Sunny, with a high near 69."
7,WednesdayNight,Partly Cloudy,Low: 51 °F,"Partly cloudy, with a low around 51."
8,Thursday,Mostly Sunny,High: 67 °F,"Mostly sunny, with a high near 67."